### ISSUE TITLE
Ask a question: V3

### ISSUE THREAD

**Issue by kotp** [exercism/v3#101]
Should there be a link to the github page generated for this repository in the README? or at least in the description of the repository?  https://exercism.github.io/v3 is built via actions, and seems to be pretty key to help people stay up to date on what is happening.

**Comment by ErikSchierboom** [comment]
There is a link to that page on the first line of the README: 

> Note: This file, and the other docs in this repository, can be viewed on GitHub or as a website with easier navigation.

Perhaps that is not clear enough?

**Comment by kotp** [comment]
I think I am used to seeing it near the top of the repository, where we see "The work-in-progress project for developing v3 tracks" I kind of expected to see the page.

![customary_link_location_for_convenience](https://user-images.githubusercontent.com/16747/72555090-f157b500-3869-11ea-9a0d-2d3f708582b7.png)

**Comment by iHiD** [comment]
Thanks for clarifying. Done.
