### ISSUE TITLE
[C# / F#] Can the Skip string be improved?

### ISSUE THREAD

**Issue by wolf99** [exercism/v3#1047]
During review of a change on the C# track we found that the string used for the Skip attribute was not ideal https://github.com/exercism/v3/pull/994#discussion_r399814943

The same will apply to the F# track I think

```csharp
[Fact(Skip = "Remove to run test")]
public void SomeTest() => // ...
```

It could be unclear to students exactly what it is they should remove to run the test... the string? The `Skip` and the string ? The `Skip`, the string and the parenthesis? The full `[Fact]` attribute?

Perhaps this is explained elsewhere in the C# and F# tracks? If not though, can the string be improved?

A suggestion for improvement: `"Remove this Skip to run this test"`

Note that per Erik's comment on the linked review, changes to the string would require a change to the tooling (https://github.com/exercism/csharp/blob/master/test.ps1#L55) as well as changes to the existing C# and F# exercises.

Follows on from the issue #972 and the related PR #994.

**Comment by ErikSchierboom** [comment]
I like the suggestion. Maybe be slightly more explicit and have: `"Remove this Skip property to run this test"`?

**Comment by robkeim** [comment]
Thanks for taking care of this @wolf99!
