### ISSUE TITLE
[C#] Proposal for Implementors' Guide

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#1087]
While we are waiting for the call for action and the rush of volunteers to implement the roughly 150 exercises, should we think about producing a C# implementors’ user guide (a one stop shop)  or are there other more pressing issues?

Examples are invaluable but fleshing them out with some precepts (you can’t say concepts, these days) might help some people.  A guide could combine workflow and file descriptions borrowed from the V3 generic documentation with C# specific examples,  a style guide and standards sections. 

As a personal aide-memoire I have produced a list of things I learnt from implementing an exercise which could for the basis for some of the user guide text.  Whatever we decide I will probably share that with anybody I’m working with who shows an interest.

We have a lot of documentation already but if you think it’ll be just a write only text that never gets read then please let me know.

Things I learnt when creating an exercise.

- [ ] instructions.md has two halves.  The first half is a narrative (brief enough not to bore or confuse the student).  This first half should contain no code.
- [ ] The second half of the instructions.md contains task by task details.   It can contain code - in the case of the properties exercise was a number of statements demonstrating usage but in other exercises I have seen this to be a simple expression.
- [ ] The code in the tasks should not be the same as the tests - not sure why - I overlooked this point.
- [ ] introduction.md was the most difficult document to get my head round.  First it wasn’t detailed enough and then it was too detailed.  One thing I did get was that it was a good place to stick equivalent terminology from other languages.
- [ ] There is something call a “slug” which seems to be a concept name.  The relationships between concepts are plotted in track specific config.json files.  They directly relate to the concept name and prerequisites as detailed in the exercise creation GitHub issue and design.md which should use the slugs.
- [ ] Keep the number of dependencies small.  In the case of my properties exercise this meant not introducing the idea of a struct when a class would do.
- [ ] Where we wanted to push the student to constrain the properties in some way (e.g. make an accessor private) it turned out that this had to be done by the Anayzer.   Although tests could detect the absence of the constraint (using reflection) there was no way to pitch this to the student as a learnable experience.
- [ ] Apart from the point above I remain vague about what might go into the Analyzer and Presenter sections of design.md.
- [ ] Story lines that might even remotely taken amiss should be avoided.  I learnt that the editor (reviewer) can push you to raise your game.
- [ ] I felt I understood what should go into after.md having watched Jeremy Walker’s video - xxx despite the fact that his thoughts were still evolving.  It seems to be the place where knowledge about the concept is consolidated, points outside the scope of the exercise are discussed.
- [ ] Each task in instructions.md should comprise a brief heading a short description and some illustrative code.
- [ ] Quoted code in markdown should give the markdown language attribute, csharp, json etc.
- [ ] hints.md should not contain code.
- [ ] Only code e.g. keywords is wrapped in quotes.  - not sure about this.  I would have thought we use back ticks.
- [ ] Avoid using choosing a language term for a general term even if it is clear from the context.  I was discouraged from using “attribute” in its normal English sense as “attribute" it is a C# language feature.
- [ ] Consistently use the footnote approach to hyperlinks.
- [ ] Consistency is important.
- [ ] hints.md should not show code but should show a section for each task.  Best is to have an external link covering the topic but in the absence of that a codeless explanation of some sort.
- [ ] Remember not to mention concepts outside the scope in any text other than after.md.  I started talking about `protected` access when inheritance was not a prerequisite.
- [ ] In GitHub when you have hundreds of review points snippets and dozens of commits the PR can become confusing.  This is particularly the case when clicking “Suggested Commit”.  The page refreshes and you completely lose your place. It is best to use batch commits from the Files tab.
- [ ] Item numbers on hints.md should be followed by a full stop.  “1.” rather than “1”
- [ ] If you have several similar concepts (in my case stones, pounds and ounces) find a way to reduce the number without damaging the story too much - pounds and ounces.
- [ ] Where a comma is in the vicinity of a line break than it should go at the end of the first line.
- [ ] Don’t indent code blocks in instructions.md.
- [ ] instructions.md when describing a task be specific about what needs to happen such as return values and type of exceptions thrown.  Note that in-browser users will not see the tests.
- [ ] Don’t include identifiers from the code in the first description part of instructions.md.  Naming should be sufficiently good to enable the student to connect the code in the tasks with ideas from the story.
- [ ] Whitespace consistency: newline before and after code block, a space between “[Fact(“ and “Skip…" (the C# part will be fixed in #1230; the markdown part is being discussed in #863).
- [ ] Bearing in mind the international audience, try to avoid recherché english.  Yes I know!
- [ ] The only file outside fo the exercise directory itself I had to change was config.json in v3/languages/csharp.

Some what late in the day I discovered (despite having been pointed at them on a number of occasions:

https://exercism.github.io/v3/#/

and in particular for C#

https://exercism.github.io/v3/#/languages/csharp/README

**Comment by ErikSchierboom** [comment]
> While we are waiting for the call for action and the rush of volunteers to implement the roughly 150 exercises, should we think about producing a C# implementors’ user guide (a one stop shop)  or are there other more pressing issues?

So for C#, that would be [this document](https://github.com/exercism/v3/blob/master/languages/csharp/reference/implementing-a-concept-exercise.md), which is the basis for any GitHub issues created (and for [this example issue](https://github.com/exercism/v3/blob/master/languages/csharp/reference/examples/new-concept-exercise-arrays.md)).

> Examples are invaluable but fleshing them out with some precepts (you can’t say concepts, these days) might help some people.  A guide could combine workflow and file descriptions borrowed from the V3 generic documentation with C# specific examples,  a style guide and standards sections. 

Agreed.

> As a personal aide-memoire I have produced a list of things I learnt from implementing an exercise which could for the basis for some of the user guide text.  Whatever we decide I will probably share that with anybody I’m working with who shows an interest.
>
> We have a lot of documentation already but if you think it’ll be just a write only text that never gets read then please let me know.
>
> Things I learnt when creating an exercise.

Thanks so much for keeping track of these things! Anything we can do to improve the documentation's clarity is highly welcome. I'll respond to your individual points below.

> 1. instructions.md has two halves.  The first half is a narrative (brief enough not to bore or confuse the student).  This first half should contain no code.

Excellent point.

> 2. The second half of the instructions.md contains task by task details.   It can contain code - in the case of the properties exercise was a number of statements demonstrating usage but in other exercises I have seen this to be a simple expression.

Well, the simple expression is also code? Each task _must_ show an example of what the code the student should implement returns for an example input. This is described in the [documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-2-add-docsinstructionsmd), or is it not clear enough?

> 3. The code in the tasks should not be the same as the tests - not sure why - I overlooked this point.

We're getting back on this. It might actually be very useful to also test the cases that are in the tasks. We are also considering being able to run the example code in a task's description too, as an easy way to check your current implementation when working from the browser.

> 4. introduction.md was the most difficult document to get my head round.  First it wasn’t detailed enough and then it was too detailed.  One thing I did get was that it was a good place to stick equivalent terminology from other languages.

This is a hard document to get right. We did update the [documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-1-add-docsintroductionmd) recently, but maybe that is not enough? I've found that getting this right will be an iterative process. I have changed the contents of these files tons of times, sometimes even after the exercise was merged due to additional insight.

> 5. There is something call a “slug” which seems to be a concept name.  The relationships between concepts are plotted in track specific config.json files.  They directly relate to the concept name and prerequisites as detailed in the exercise creation GitHub issue and design.md which should use the slugs.

The slug is the exercise's name as it appears on the file system (`exercise/concept/<slug>`) and in the `config.json` file. We have them relate to the concept name for convenience.

> 6. Keep the number of dependencies small.  In the case of my properties exercise this meant not introducing the idea of a struct when a class would do.

Definitely something that we should be mentioning. Reducing the number of dependencies means that the exercise itself is more "focused" and will also be opened up for students sooner. 

> 7. Where we wanted to push the student to constrain the properties in some way (e.g. make an accessor private) it turned out that this had to be done by the Anayzer.   Although tests could detect the absence of the constraint (using reflection) there was no way to pitch this to the student as a learnable experience.

Good point. We should make it clearer when something should be in an analyzer (it should be a last resort).

> 8. Apart from the point above I remain vague about what might go into the Analyzer and Presenter sections of design.md.

See previous comment.

> 9. Story lines that might even remotely taken amiss should be avoided.  I learnt that the editor (reviewer) can push you to raise your game.

:)

> 10. I felt I understood what should go into after.md having watched Jeremy Walker’s video - xxx despite the fact that his thoughts were still evolving.  It seems to be the place where knowledge about the concept is consolidated, points outside the scope of the exercise are discussed.

Isn't this explained in the [existing documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-4-add-docsaftermd)?

> 11. Each task in instructions.md should comprise a brief heading a short description and some illustrative code.

The heading part is a nice addition. Isn't the illustrative code already covered in the [existing documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-2-add-docsinstructionsmd)?

> 12. Quoted code in markdown should give the markdown language attribute, csharp, json etc.

This should be added to the [open PR for a style guide](https://github.com/exercism/v3/pull/970), possibly after it is merged.

> 13. hints.md should not contain code.

Isn't this in the [existing documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-3-add-docshintsmd)?

> 14. Only code e.g. keywords is wrapped in quotes.  - not sure about this.  I would have thought we use back ticks.

We do indeed use backticks for code. Did I suggest wrapping keywords in quotes somewhere?

> 15. Avoid using choosing a language term for a general term even if it is clear from the context.  I was discouraged from using “attribute” in its normal English sense as “attribute" it is a C# language feature.

Yep. The general reason here being to be as unambiguous as possible.

> 16. Consistently use the footnote approach to hyperlinks.

This is in the [open PR for a style guide](https://github.com/exercism/v3/pull/970).

> 17. Consistency is important.

I think it might be helpful if the C# issues would also link to sample files like the generic instructions do.

> 18. hints.md should not show code but should show a section for each task.  Best is to have an external link covering the topic but in the absence of that a codeless explanation of some sort.

The first part is something we should indeed include. As for the second part, isn't that covered in the [existing documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-3-add-docshintsmd)?

>> The hints should not spell out the solution, but instead point to a resource describing the solution (e.g. linking to documentation for the function to use).

> 19. Remember not to mention concepts outside the scope in any text other than after.md.  I started talking about `protected` access when inheritance was not a prerequisite.

I hoped this was covered by the " The aim is to give the student just enough context to figure out the solution themselves" mention in [this document](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-1-add-docsintroductionmd), but maybe we need to expand on that?

> 20. In GitHub when you have hundreds of review points snippets and dozens of commits the PR can become confusing.  This is particularly the case when clicking “Suggested Commit”.  The page refreshes and you completely lose your place. It is best to use batch commits from the Files tab.

I wonder where we would fit this in the documentation. 

> 21. Item numbers on hints.md should be followed by a full stop.  “1.” rather than “1”

Good point.

> 22. If you have several similar concepts (in my case stones, pounds and ounces) find a way to reduce the number without damaging the story too much - pounds and ounces.

The general idea behind this is to have the exercise instructions be as short as possible. This helps the student focus on the exercise's Concept(s) instead of trying to figure out the "rules" of the exercise. So in general: keep things as simple as possible.

> 23. Where a comma is in the vicinity of a line break than it should go at the end of the first line.

I think mostly this is adhering to the default coding styles as used in the official document (e.g. the [enum documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum)). Maybe we should state something like this.

> 24. Don’t indent code blocks in instructions.md.

Yep. Another way to phrase this is to have the code blocks align to the left with the other text.

> 25. instructions.md when describing a task be specific about what needs to happen such as return values and type of exceptions thrown.  Note that in-browser users will not see the tests.

Yes, each task should make it clear what is to be returned if there is potential confusion. For example, all exercise where there is no stub should be very clear about what is expected. However, when there are stubs, we don't necessarily have to mention that a specific type is returned if we can reasonably expect the student to understand it. See [this example](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/strings/.docs/instructions.md#1-get-message-from-a-log-line), where I don't think we would necessarily need to mention that a `string` is being returned. That said, it is a fine line and we should always consider if things are clear enough for the student.

> 26. Don’t include identifiers from the code in the first description part of instructions.md.  Naming should be sufficiently good to enable the student to connect the code in the tasks with ideas from the story.

Excellent point. Basically this is about the separation of the instructions document into two parts: the theme/context (no code references) which is followed by the actual C# tasks (which have code reference by definition).

> 27. Whitespace consistency: newline before and after code block, a space between “[Fact(“ and “Skip…"

The simplest way we can make sure formatting is consistent is to use the `dotnet format` global tool (see [this page](https://github.com/dotnet/format)).

> 28. Bearing in mind the international audience, try to avoid recherché english.  Yes I know!

There is [an open PR for a style guide](https://github.com/exercism/v3/pull/970). This would be a great point to add.

> 29. The only file outside fo the exercise directory itself I had to change was config.json in v3/languages/csharp.

I think this is mostly due to me forgetting to point out which other files to edit :) The `config.json` file change is definitely the most important one, but there are more, see [step 7](https://github.com/exercism/v3/blob/master/languages/csharp/reference/examples/new-concept-exercise-arrays.md#step-7-update-the-general-concept-document) and [step 8](https://github.com/exercism/v3/blob/master/languages/csharp/reference/examples/new-concept-exercise-arrays.md#step-8-updating-list-of-implemented-exercises).

**Comment by mikedamay** [comment]
> > While we are waiting for the call for action and the rush of volunteers to implement the roughly 150 exercises, should we think about producing a C# implementors’ user guide (a one stop shop)  or are there other more pressing issues?
> 
> So for C#, that would be [this document](https://github.com/exercism/v3/blob/master/languages/csharp/reference/implementing-a-concept-exercise.md), which is the basis for any GitHub issues created (and for [this example issue](https://github.com/exercism/v3/blob/master/languages/csharp/reference/examples/new-concept-exercise-arrays.md)).
> 
> > Examples are invaluable but fleshing them out with some precepts (you can’t say concepts, these days) might help some people.  A guide could combine workflow and file descriptions borrowed from the V3 generic documentation with C# specific examples,  a style guide and standards sections.
> 
> Agreed.
> 
> > As a personal aide-memoire I have produced a list of things I learnt from implementing an exercise which could for the basis for some of the user guide text.  Whatever we decide I will probably share that with anybody I’m working with who shows an interest.
> > We have a lot of documentation already but if you think it’ll be just a write only text that never gets read then please let me know.
> > Things I learnt when creating an exercise.
> 
> Thanks so much for keeping track of these things! Anything we can do to improve the documentation's clarity is highly welcome. I'll respond to your individual points below.
> 
> > 1. instructions.md has two halves.  The first half is a narrative (brief enough not to bore or confuse the student).  This first half should contain no code.
> 
> Excellent point.
> 
> > 1. The second half of the instructions.md contains task by task details.   It can contain code - in the case of the properties exercise was a number of statements demonstrating usage but in other exercises I have seen this to be a simple expression.
> 
> Well, the simple expression is also code? Each task _must_ show an example of what the code the student should implement returns for an example input. This is described in the [documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-2-add-docsinstructionsmd), or is it not clear enough?

Indeed, an expression is code.  My thrust was that sometimes multiple statements were required as in the case of properties and sometimes a single expression was appropriate as for strings.  On reflection, they are both demonstrations of usage so this would require some rewording.

> 
> > 1. The code in the tasks should not be the same as the tests - not sure why - I overlooked this point.
> 
> We're getting back on this. It might actually be very useful to also test the cases that are in the tasks. We are also considering being able to run the example code in a task's description too, as an easy way to check your current implementation when working from the browser.
> 
> > 1. introduction.md was the most difficult document to get my head round.  First it wasn’t detailed enough and then it was too detailed.  One thing I did get was that it was a good place to stick equivalent terminology from other languages.
> 
> This is a hard document to get right. We did update the [documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-1-add-docsintroductionmd) recently, but maybe that is not enough? I've found that getting this right will be an iterative process. I have changed the contents of these files tons of times, sometimes even after the exercise was merged due to additional insight.

I suppose I favour more "hand holding".  For example to give links to specific examples.  I know there is a general steer towards 2 or 3 examples but for specific docs specific examples might be good.

> 
> > 1. There is something call a “slug” which seems to be a concept name.  The relationships between concepts are plotted in track specific config.json files.  They directly relate to the concept name and prerequisites as detailed in the exercise creation GitHub issue and design.md which should use the slugs.
> 
> The slug is the exercise's name as it appears on the file system (`exercise/concept/<slug>`) and in the `config.json` file. We have them relate to the concept name for convenience.

Somebody has kindly explained to me the derivation and usage of slug (as a key distinguishing part of a URL for some purpose).  I'm sure I'm not the ony one this has passed by.

> 
> > 1. Keep the number of dependencies small.  In the case of my properties exercise this meant not introducing the idea of a struct when a class would do.
> 
> Definitely something that we should be mentioning. Reducing the number of dependencies means that the exercise itself is more "focused" and will also be opened up for students sooner.
> 
> > 1. Where we wanted to push the student to constrain the properties in some way (e.g. make an accessor private) it turned out that this had to be done by the Anayzer.   Although tests could detect the absence of the constraint (using reflection) there was no way to pitch this to the student as a learnable experience.
> 
> Good point. We should make it clearer when something should be in an analyzer (it should be a last resort).
> 
> > 1. Apart from the point above I remain vague about what might go into the Analyzer and Presenter sections of design.md.
> 
> See previous comment.
> 
> > 1. Story lines that might even remotely taken amiss should be avoided.  I learnt that the editor (reviewer) can push you to raise your game.
> 
> :)
> 
> > 1. I felt I understood what should go into after.md having watched Jeremy Walker’s video - xxx despite the fact that his thoughts were still evolving.  It seems to be the place where knowledge about the concept is consolidated, points outside the scope of the exercise are discussed.
> 
> Isn't this explained in the [existing documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-4-add-docsaftermd)?

Not really.  And according to Jeremy's video this was/is still fluid.  But the point that resonated is that this is a kind of reference for the student back to the exercise.  They can remind themselves of what they learnt and put it in some context, e.g. If they encounter the concept in the wild and feel it doesn't quite gell with their memory this would be the place for a refresher.

> 
> > 1. Each task in instructions.md should comprise a brief heading a short description and some illustrative code.
> 
> The heading part is a nice addition. Isn't the illustrative code already covered in the [existing documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-2-add-docsinstructionsmd)?

Again I am favouring a slightly more "hand holding" approach.  I am a lazy person and we respond to detailed instructions that require less thought so I am possibly catering to the lazy demographic.
> 
> > 1. Quoted code in markdown should give the markdown language attribute, csharp, json etc.
> 
> This should be added to the [open PR for a style guide](https://github.com/exercism/v3/pull/970), possibly after it is merged.
> 
> > 1. hints.md should not contain code.
> 
> Isn't this in the [existing documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-3-add-docshintsmd)?

The doc says "The hints should not spell out the solution" which is not quite the same thing as saying "don't give any code".

> 
> > 1. Only code e.g. keywords is wrapped in quotes.  - not sure about this.  I would have thought we use back ticks.
> 
> We do indeed use backticks for code. Did I suggest wrapping keywords in quotes somewhere?

I used quotes referring to "properties".  It was probably bad style irrespective of the question of keywords.

> 
> > 1. Avoid using choosing a language term for a general term even if it is clear from the context.  I was discouraged from using “attribute” in its normal English sense as “attribute" it is a C# language feature.
> 
> Yep. The general reason here being to be as unambiguous as possible.

So much easier said than done.  I'm not sure what the make up of the exercise contributors will be but I have not found the answer to the possibly relevant question of what English style suits Google translate.
> 
> > 1. Consistently use the footnote approach to hyperlinks.
> 
> This is in the [open PR for a style guide](https://github.com/exercism/v3/pull/970).

https://github.com/aldraco/v3/blob/update-docs-concept-exercise/docs/maintainers/concept-exercise-style-guide.md (note for me)

> 
> > 1. Consistency is important.
> 
> I think it might be helpful if the C# issues would also link to sample files like the generic instructions do.

Understood
> 
> > 1. hints.md should not show code but should show a section for each task.  Best is to have an external link covering the topic but in the absence of that a codeless explanation of some sort.
> 
> The first part is something we should indeed include. As for the second part, isn't that covered in the [existing documentation](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-3-add-docshintsmd)?

Interesting.  I think that the example I was following had all tasks linked externally.  Including specific wording about what constitutes a hint rather than "They might link to..." gives context to the example document.

> 
> > > The hints should not spell out the solution, but instead point to a resource describing the solution (e.g. linking to documentation for the function to use).
> 
> > 1. Remember not to mention concepts outside the scope in any text other than after.md.  I started talking about `protected` access when inheritance was not a prerequisite.
> 
> I hoped this was covered by the " The aim is to give the student just enough context to figure out the solution themselves" mention in [this document](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-1-add-docsintroductionmd), but maybe we need to expand on that?

Of course but it's very easy to include an out-of-scope concept in some inconsequential "for instance" in the text so a reminder might be useful.
> 
> > 1. In GitHub when you have hundreds of review points snippets and dozens of commits the PR can become confusing.  This is particularly the case when clicking “Suggested Commit”.  The page refreshes and you completely lose your place. It is best to use batch commits from the Files tab.
> 
> I wonder where we would fit this in the documentation.
> 
> > 1. Item numbers on hints.md should be followed by a full stop.  “1.” rather than “1”
> 
> Good point.
> 
> > 1. If you have several similar concepts (in my case stones, pounds and ounces) find a way to reduce the number without damaging the story too much - pounds and ounces.
> 
> The general idea behind this is to have the exercise instructions be as short as possible. This helps the student focus on the exercise's Concept(s) instead of trying to figure out the "rules" of the exercise. So in general: keep things as simple as possible.

I know what you mean and I know it is difficult to provide guidance but I think within document guidance / style guide the phrase "as simple as possible" needs fleshing out with a brief discussion of trade-offs or a few examples showing the limits.
> 
> > 1. Where a comma is in the vicinity of a line break than it should go at the end of the first line.
> 
> I think mostly this is adhering to the default coding styles as used in the official document (e.g. the [enum documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum)). Maybe we should state something like this.

It's worth reminding exercise contributors that they should examine the pre-requisite exercise from a stylistic/code standards stand point.  I didn't think of doing that.
> 
> > 1. Don’t indent code blocks in instructions.md.
> 
> Yep. Another way to phrase this is to have the code blocks align to the left with the other text.
> 
> > 1. instructions.md when describing a task be specific about what needs to happen such as return values and type of exceptions thrown.  Note that in-browser users will not see the tests.
> 
> Yes, each task should make it clear what is to be returned if there is potential confusion. For example, all exercise where there is no stub should be very clear about what is expected. However, when there are stubs, we don't necessarily have to mention that a specific type is returned if we can reasonably expect the student to understand it. See [this example](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/strings/.docs/instructions.md#1-get-message-from-a-log-line), where I don't think we would necessarily need to mention that a `string` is being returned. That said, it is a fine line and we should always consider if things are clear enough for the student.
> 
> > 1. Don’t include identifiers from the code in the first description part of instructions.md.  Naming should be sufficiently good to enable the student to connect the code in the tasks with ideas from the story.
> 
> Excellent point. Basically this is about the separation of the instructions document into two parts: the theme/context (no code references) which is followed by the actual C# tasks (which have code reference by definition).
> 
> > 1. Whitespace consistency: newline before and after code block, a space between “[Fact(“ and “Skip…"
> 
> The simplest way we can make sure formatting is consistent is to use the `dotnet format` global tool (see [this page](https://github.com/dotnet/format)).

Good point.  I think we should mention `dotnet format`.  Some of this was markdown.  I think consistency serves us well.  However, I am loath to force whitespaces on contributors unless a) I, personally, think that their presence/absence is reducing clarity or b) there is a style guide which mandates (in the nicest possible way) it.  We should avoid "cargo culting".
> 
> > 1. Bearing in mind the international audience, try to avoid recherché english.  Yes I know!
> 
> There is [an open PR for a style guide](https://github.com/exercism/v3/pull/970). This would be a great point to add.
> 
> > 1. The only file outside fo the exercise directory itself I had to change was config.json in v3/languages/csharp.
> 
> I think this is mostly due to me forgetting to point out which other files to edit :) The `config.json` file change is definitely the most important one, but there are more, see [step 7](https://github.com/exercism/v3/blob/master/languages/csharp/reference/examples/new-concept-exercise-arrays.md#step-7-update-the-general-concept-document) and [step 8](https://github.com/exercism/v3/blob/master/languages/csharp/reference/examples/new-concept-exercise-arrays.md#step-8-updating-list-of-implemented-exercises).

I would highlight this as it is the only shared document that needs to be updated.  You get used to working within the comfort of your own directory tree.

**Comment by ErikSchierboom** [comment]
Thanks for the responses. We'd be more than happy to take PR's for improvements if you are interested in doing that :)

**Comment by iHiD** [comment]
I've turned Mike's original post into a list of checkboxes. We should tick each off as we get them onto master somewhere.

**Comment by ErikSchierboom** [comment]
Excellent! Thanks @iHiD
