### ISSUE TITLE
[Ruby] Use new naming rules for config.json concepts

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1133]
We've recently introducing rules regarding the [naming of concepts](https://github.com/exercism/v3/blob/master/docs/maintainers/determining-concepts.md#naming-concepts) in `config.json` files. 

The Ruby track's [config.json](https://github.com/exercism/v3/blob/master/languages/ruby/config.json) file should be updated to conform to the new naming rules.

**Comment by pvcarrera** [comment]
Hi @ErikSchierboom, I think the `config.json` on the Ruby track already follows the conventions, maybe we can close this issue.

**Comment by ErikSchierboom** [comment]
@pvcarrera Well, almost :)

If you check the [concept for the `strings` exercise](https://github.com/exercism/v3/blob/master/languages/ruby/config.json#L16), it uses `strings-basic`. This implies a hierarchy and goes against the rules. The fix is simple: use `strings` instead of `strings-basic`.
