### ISSUE TITLE
[ALL] can we use prettier to enforce consistent markdown formatting?

### ISSUE THREAD

**Issue by efx** [exercism/v3#1162]
# the problem

The flexible nature of Markdown means each contributor will write it slightly differently. This creates a cognitive load on maintainers reviewing pull requests. I originally wanted to nudge users using editorconfig but discussing with @ErikSchierboom he mentioned prettier. [Prettier](https://prettier.io/) is a JavaScript tool that automatically applies "opinionated formatting".  

# possible implementation approaches

- use prettier in a GitHub action to rewrite staged markdown file changes
- use prettier as a linter

# alternatives
- editorconfig #863, #1150  

How would you feel about doing this? Do thumbs up or down to vote. And certainly chime in with discussion to cover other angles or share some experience.

**Comment by workingjubilee** [comment]
Discussion of #863 should continue in a single issue rather than being split amongst multiple issues.

**Comment by ErikSchierboom** [comment]
Agreed. I missed the other issue.

**Comment by workingjubilee** [comment]
Thank you!
