### ISSUE TITLE
[Go] Add exercises to config.json

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1195]
I've just noticed that the Go track has implemented Concept Exercises, but that they are not yet defined in the Go track's [`config.json` file](https://github.com/exercism/v3/blob/master/languages/go/config.json):

```json
"exercises": {
    "concept": [],
```

Please add entries for the created Concept Exercises. For an example what each entry should look like, see [this document](https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md#step-5-update-languagestrackconfigjson) or [this example](https://github.com/exercism/v3/blob/master/languages/csharp/config.json).

**Comment by ErikSchierboom** [comment]
CC @exercism/go

**Comment by oanaOM** [comment]
I can help with this. Just one question. Where do I find the uuid?

**Comment by SleeplessByte** [comment]
@oanaOM generate a new unique one for each exercise. For example:

https://duckduckgo.com/?q=uuid&atb=v184-1&ia=answer

**Comment by ErikSchierboom** [comment]
@oanaOM The default UUID generator that we usually use is https://www.uuidgenerator.net/version4, but any unique UUID would do.

**Comment by oanaOM** [comment]
Thanks everyone!
I've just submitted a PR with the new config.json file.

**Comment by tehsphinx** [comment]
Seems to be done
