### ISSUE TITLE
[CI] Remove status/in-progress label from closed issues

### ISSUE THREAD

**Issue by aimorris** [exercism/v3#1215]
The `status/in-progress` label should automatically be removed from issues when they are closed, as they are no longer in progress.

**Comment by aimorris** [comment]
https://github.com/marketplace/actions/simple-issue-labeler

**Comment by angelikatyborska** [comment]
This repository is being deprecated and all track-specific changes from it are being brought back into track repositories. I think that means that each track would need to decide for themselves if they want to use github.com/marketplace/actions/simple-issue-labeler to automatically add and remove labels.
