### ISSUE TITLE
[CI] Simplify workflows checking for modifications

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1282]
Some of the existing workflows (such as the valid-links workflows) use `git diff` to see what files have been changed. In [this PR](https://github.com/exercism/v3/pull/1278/files#diff-2dcaf572306716b16aff8280a08b3a62R31) we're using the GH API to detect that, which makes for much simpler code. We should consider using the GH API for those other workflows too.

**Comment by angelikatyborska** [comment]
I believe this issue becomes obsolete after exploding the v3 repo into track repos.
