### ISSUE TITLE
[Elixir] Implement new Concept Exercise: pattern-matching

### ISSUE THREAD

**Issue by fireproofsocks** [exercism/v3#1286]
[Use this issue template to describe how to implement a new concept exercises. Please fill in the issue template, and remove any sections wrapped in square brackets (such as this section!).]

This issue describes how to implement the `pattern-matching` concept exercise for the Elixir track.

## Goal

The goal of this exercise is to introduce the fundamentals of pattern matching in Elixir, focusing on tuples and maps.

## Learning objectives

- Know that the `=` is the _match operator_ (not merely an assignment operator)
- Know how to match on a scalar value (string, integer, boolean, etc)
- Know how to match a single value out of a tuple
- Know how to match on maps
- Understand that `%{}` matches on ANY map whereas `[]` matches only EMPTY lists (!)

## Out of scope

- guard clauses
- multi-clause functions
- tail | head syntax in lists
- pin operator 

## Concepts

[List the concepts this exercise teaches. These concepts can be more fine-grained than their overarching concepts.

For example:

- `pattern-matching` (basic)

## Prerequisites

- `basics` 

## Resources to refer to

[Pattern Matching](https://elixir-lang.org/getting-started/pattern-matching.html)

## Representer

TODO

## Analyzer

TODO

## Implementing

TODO

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by neenjaw** [comment]
A couple thoughts:
- probably  `lists` and `tuples` and `maps` would be your prerequisites for this
- I like the edge cases for matching on lists, this is an important concept in elixir/erlang/prolog
- including maps in this could make it too big, but feel it out
    - whatever coding exercise you use for this, could be extended for a second pattern matching lesson on maps

**Comment by fireproofsocks** [comment]
Yeah, it might make sense to break maps out separately... 
Also, it would make sense to break out any binary matching into its own exercise (I'm thinking anything beyond simple string prefix matching.

I'm finding it's tricky to think of creative ways to test this...

**Comment by neenjaw** [comment]
You could build it on top of something as simple as `["two", "parts"] = String.split("two:parts", ":")`

**Comment by neenjaw** [comment]
It might even be most simple to teach basic pattern matching as part of a `case` statement

**Comment by neenjaw** [comment]
I'm going to close this for now, feel free to reopen if you come back to revisit this.
