### ISSUE TITLE
[JavaScript] Improve exercise: concept/strings

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/v3#1298]
### The current state

The `strings` exercise currently relies on using a few more advanced features:

- "destructuring" it into an `array`.
- reversing said `array`.
- joining that `array` back into a string.

Additionally, there is no `after.md`

### The improved version

We need to find a way to get rid of the `reverse` task, and replace it with something more `string`-like. The story should be changed accordingly. Options here are, but not limited to:

- Doing something with the value such as `.trim()`, `.replace()`, `.substring()`, `.padEnd()`, `.padStart()`
- Searching / Satifiying a property, such as: `.startsWith()`, `.endsWith()`, `.includes()`.

We should also add `after.md`

----

If you intend to take this issue, please first complete the exercise yourself, to get a feeling for the story. You can [play the exercise here][playground].

[playground]: https://exercism-playground.derk-jan.com/javascript/play/concept/strings

**Comment by hayashi-ay** [comment]
@SleeplessByte Can I work on it?

**Comment by SleeplessByte** [comment]
Of course! @hayashi-ay . Feel free to post here any questions or ideas you have, or submit a PR.

**Comment by hayashi-ay** [comment]
I'm not sure why we need to implement `reverse`. A backdoor password is made up of the last letter of each sentences plus ', please', so I think `reverse` function is not needed.
Am I misunderstood something?

Also, a telestich is reversed  at [L95] and then it wan reversed again at L96.

[L95]:https://github.com/exercism/v3/blob/master/languages/javascript/exercises/concept/strings/strings.spec.js#L95

**Comment by SleeplessByte** [comment]
> The guard will tell you all the letters you've responded with at once, but in reverse:
> You need to format the letters as a capitalised word

This is _why_ we needed to reverse it per the instructions. However, I don't want array functions in there, so if we just _remove_ `generateReversal` we can remove the need to `reverse`.

This is also _why_ it was reversing the value to test on L95 and then testing against the original on L96.

**Comment by hayashi-ay** [comment]
Thanks. I missed the phrase, "but in reverse".
 I'll think about an alternative of `reverse`  a bit more.

**Comment by hayashi-ay** [comment]
@SleeplessByte How about changing the story like:
```
The guard will tell you all the letters you've responded with at once,
but there are spaces after each sentence
```

So, a sentence would be like "Stands so high&nbsp;&nbsp;&nbsp;" and it need to be trimmed by String#trim.

**Comment by SleeplessByte** [comment]
Instead, let's just add _ocasional_ whitespace to the original text, so that you need to trim it when determining the last letter. I like the idea of having to add trim, on top of .length - 1.
