### ISSUE TITLE
[JavaScript] Improve exercise: concept/booleans

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/v3#1299]
### The current state

The `booleans` exercise currently has a decently chaotic `instructions.md` and lacks commentary in the code file (which prevents autocompletion in many IDEs):

- Each task duplicates what a variable means to both text and code example
- Each task duplicates what it should return based on the function name and text
- The "character state" higher up could use some highlights to visually separate the actions (for example **bold**) and the characters (for example _italics_). This is no issue when initially reading the instructions, but it makes it impossible to skim.
- Some of the hints lead to more questions without being able to answer them.

### The improved version

1. Find a way to remove the duplication (information overload) in the tasks
2. Add highlights to the character instructions
3. Ensure that each hint references to, for example, MDN (as MDN mostly has _tutorial-like_ instructions for each function. This is the case for short-circuiting and precedence).
4. Add code comments. The following for example will recognise that there are no functions on `knightIsAwake` (other than `Boolean.getValue`) and will show "error" messages when the return value is not a `boolean`.
  ```javascript
  /**
   * @param {boolean} knightIsAwake 
   * @return {boolean}
   */
```
----

If you intend to take this issue, please first complete the exercise yourself, to get a feeling for the story. You can [play the exercise here][playground].

[playground]: https://exercism-playground.derk-jan.com/javascript/play/concept/booleans

**Comment by rishiosaur** [comment]
Can I take a go at it?

**Comment by rishiosaur** [comment]
I'm going to try to find some MDN articles about the instructions given in the hints.

**Comment by rishiosaur** [comment]
I've added in the highlights and simplified the text a little bit, @SleeplessByte. Can you take a look at #1323 and let me know what you think?

**Comment by SleeplessByte** [comment]
@rishiosaur Already reviewed!

**Comment by SleeplessByte** [comment]
Thank you @rishiosaur for taking care of it (and thank you @peterchu999 for the additional changes).
