### ISSUE TITLE
[JavaScript] Improve exercise: concept/arrays

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/v3#1300]
### The current state

The `arrays` exercise is great, and has a few items that can be improved:

- The "fill array" task requires looping. It's meant to teach `.push`, but [_searching_](https://www.google.com/search?hl=en&q=fill%20array%20with%20value%20javascript) will lead to `Array.fill` and its cousins. 
- Removing from top as a task (`.pop`) exists, but removing from bottom (`.shift`) does not.
- Adding to "top" as a task (`.push`) exists, but inserting at bottom (`.unshift`) does not.

### The improved version

1. Add code comments. The following for example will recognise the array and provide code completion. If `TypeScript` is supported (it's not on the playground at moment of writing, but will be later), there will also be an error message if you don't return an array.
  ```javascript
  /**
   * @param {number[]} array
   * @param {number} index
   * @param {number} newValue
   * 
   * @returns {number[]}
   */
```
2. Remove the `prefillArray` task, and replace it with one where we need to `.push`, explicitely.
3. Add a new task to `.shift`.
4. Add a new task to `.unshift`.

The idea is to have one or two more exercises built on top of this, which teach iteration/transformation and analysing respectively. (Thank you Josh for writing this for me)

```text
transforms / loops

- map
- forEach
- reverse
- sort
- filter
- flat
- reduce

analysis

- includes
- every
- some
- find
- indexOf
```

----

If you intend to take this issue, please first complete the exercise yourself, to get a feeling for the story. You can [play the exercise here][playground].

[playground]: https://exercism-playground.derk-jan.com/javascript/play/concept/arrays

**Comment by rishiosaur** [comment]
Is anyone doing this issue right now? I'd love to take a crack at it.

**Comment by peterchu999** [comment]
Hey can i take a go at it ?

**Comment by SleeplessByte** [comment]
Thank you @peterchu999 for taking care of this.
