### ISSUE TITLE
[Common Lisp] Standardising the test file stub

### ISSUE THREAD

**Issue by TheLostLambda** [exercism/v3#1345]
Just putting this together to see is anyone has suggestions for how we lay out test files. After we settle on something, we can put together some tools for auto-generating these sort of files. This is what I have so far:

```lisp
(load "slug")
(ql:quickload :fiveam)
(defpackage slug-test
  (:use :cl :fiveam :slug)
  (:export :run-tests))
(in-package :slug-test)

(def-suite slug-suite)
(in-suite slug-suite)

(defun run-tests (&optional (explain t))
  (let ((tests (run 'slug-suite)))
    (if explain (explain! tests) tests)))
```

If we wanted, we could add this tweak to allow the test-file to be compiled:

```lisp
(eval-when (:compile-toplevel :load-toplevel :execute)
  (load "slug")
  (ql:quickload :fiveam))
...
```

What do you think? Anything else we should add or tweak?

**Comment by verdammelt** [comment]
I think this would be a good idea and good for us to do early before we do too many exercises.

A (semi-)random thought: could/should we add some small comments to let the student know what these mysterious things are doing? we are not *teaching* them but it could start to give them some idea of what is going on? Do you think that would be beneificial.

**Comment by TheLostLambda** [comment]
Yeah actually, I think that would be a good idea! It will probably help us maintainers keep it straight too (or at least my forgetful self).

Do you feel strongly about the `eval-when` addition?

**Comment by verdammelt** [comment]
re: `eval-when`: I wish we could not have it - I think it adds extra complexity that would be nice to keep out of the student's face until later... but as we found out - it is necessary. So I vote for its inclusion.

**Comment by TheLostLambda** [comment]
Alright, I think that's fair. I'll look into putting a model test file up on the repo with some comments and `eval-when`. I'll set up a PR soon!
