### ISSUE TITLE
[Elixir] Implement new Concept Exercise: tail-recursion

### ISSUE THREAD

**Issue by fireproofsocks** [exercism/v3#1359]
This issue describes how to implement the `tail-recursion` concept exercise for the Elixir track.

## Goal

This exercise will teach how recursive functions are written in Elixir, specifically those implementing "tail-recursion".

## Learning objectives

For example:

- Understand how and when to write multi-clause functions.
- Understand how an accumulator works.

## Out of scope

- guard clauses
 
## Concepts

- `recursion`
- `pattern-matching`

## Prerequisites

- `lists`
- `pattern-matching`

## Resources to refer to

The official docs on [recursion](https://elixir-lang.org/getting-started/recursion.html)

## Representer

The solution should not require any private functions.

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by angelikatyborska** [comment]
To keep https://github.com/exercism/v3/issues/1490 simple, I am not mentioning accumulators in that exercise, assuming they will be taught in this one.

**Comment by neenjaw** [comment]
This may end up being closed by #1505
