### ISSUE TITLE
[CI] Check for invalid Windows characters in file names

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1369]
[PR 1350](https://github.com/exercism/v3/pull/1350) introduced files whose names were not valid on Windows. This made working with the repo not possible anymore on Windows. We should add checks for invalid Windows characters in file names. [Here is a list of possibly invalid characters](https://github.com/exercism/v3/pull/1350#issuecomment-621134467).

**Comment by SaschaMann** [comment]
Maybe a simple way to avoid these issues would be a CI run that just tries to clone and pull the repo on all available OSes.

**Comment by ErikSchierboom** [comment]
That could work.

**Comment by SleeplessByte** [comment]
That is a simple way to solve it, indeed.
