### ISSUE TITLE
[CI] Better Prettier output?

### ISSUE THREAD

**Issue by wolf99** [exercism/v3#1463]
Can we get some better output for Prettier in the CI?

I think I recall that it isn't intended that we should need to run Prettier locally, but the existing output basically just says "No" 😅  e..g. I have no idea why this is failing: https://github.com/exercism/v3/pull/1209/checks?check_run_id=681542207

I'm not familiar with prettier so I don't know if this is possible, but what I would like to see here instead is: "No, because X is wrong on line N"

@ErikSchierboom, because IIRC this is your area of expertise. Please adjust if incorrect though.

**Comment by wolf99** [comment]
Oh. This is actually the verify job rather than the actual format job itself. Shouldn't the format job run also? Maybe I've misunderstood the expected flow here?

**Comment by ErikSchierboom** [comment]
@wolf99 We don't automatically run the formatter if the verification fails. This is to not have files change automatically without people knowing it.

I don't think there is a way to get the output you want, but feel free to try out some options with the Prettier CLI to see if you can improve it: https://prettier.io/docs/en/cli
