### ISSUE TITLE
Add filename restrictions to CI.

### ISSUE THREAD

**Issue by iHiD** [exercism/v3#1465]
All filenames should only include `[a-zA-Z0-9]` and `-_.`. 

We need a CI enforcement for this. I think we can enforce this globally on this repo as the easiest way of achieving it.

(cc @ErikSchierboom @SaschaMann as candidates for GHA magic :))

**Comment by SaschaMann** [comment]
Could be combined with #1369 

---

I know you mentioned it before, but I don't know where: what's the reason for this restriction again?

**Comment by iHiD** [comment]
Mitigating things like [directory traversal attacks](https://en.wikipedia.org/wiki/Directory_traversal_attack). As the files are written to the OS with the names they are submitted with, we need to limit characters to protect us from a range of attacks. Ideally we'd not allow user-input to be written to the OS, but we don't really have a choice as files' contents can be (and are in many languages) tightly coupled to their names.
