### ISSUE TITLE
[C#] Invalid Error Message on "Run Concept Checks" Action

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#1496]
Saw the following inappropriate error message when pushing to my own forked repo:

`ERROR: LoadError: ArgumentError: "./languages/c/reference/concepts.csv" is not a valid file`

I think I had made changes only to the C# branch so there seems to be no reason to be concerned about a C file.

I eliminated the error message by adding my recently added concept "dictionaries" to the `languages/csharp/exercises/concept/README.md` so some reference in this direction would be a useful error message where the concept reference is missing.

**Comment by ErikSchierboom** [comment]
@mikedamay I don't think the error message was eliminated by the addition to the README. I think this is a bug that @SaschaMann knows about.

**Comment by mikedamay** [comment]
Sounds good
