### ISSUE TITLE
[Rust] Add entries to config.json

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1502]
Rust's [config.json file](https://github.com/exercism/v3/blob/master/languages/rust/config.json) does not contain any exercises, even though there are three exercises in the [languages/rust/exercises/concept directory](https://github.com/exercism/v3/tree/master/languages/rust/exercises/concept). Is this intentional? If not, please add entries for the exercises to the config.json file. Here is the [documentation regarding the config.json file](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md#configjson).

**Comment by efx** [comment]
See also https://github.com/exercism/v3/pull/1462 for how to add one.
