### ISSUE TITLE
[Docs] Improve Website View of Documentation

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#1507]
The key document (https://exercism.github.io/v3/#/docs/concept-exercises)[https://exercism.github.io/v3/#/docs/concept-exercises] does not show up in the contents/index sidebar in the web view of exercism.github.io/v3.

**Comment by ErikSchierboom** [comment]
I can't seem to reproduce:

![image](https://user-images.githubusercontent.com/135246/82894936-b2421a80-9f53-11ea-89cc-1c2abe791a9c.png)

If I go to https://exercism.github.io/v3/#/, I can see it in the sidebar. Am I looking in the wrong place?

**Comment by mikedamay** [comment]
Difficult to argue with that except that I saw the first heading in the "Concept Exercises >" doc "What do we mean by concepts?", thought "I know all about that" and moved on to "Docs for Maintainers" where I came across the key documents as links in the FAQ.  I expect it's just me.

**Comment by ErikSchierboom** [comment]
Let's keep an eye out if anyone else has the same issue.
