### ISSUE TITLE
[DOCS] Repo Wide List of Implemented Exercises

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#1510]
Is there a list of implemented exercises for the whole repo showing exercise/concept name and implemented language?  If not, can we have one?  It would be useful when looking for an exercise to fork.

**Comment by ErikSchierboom** [comment]
We don't have a list per implemented language, but we do have something like that: https://github.com/exercism/v3/blob/master/reference/stories/README.md

**Comment by mikedamay** [comment]
That's useful.  Thanks.  I think something dynamically generated just to save on looking down the tree into each language would be good.  Let's see if anybody else raises the issue.
