### ISSUE TITLE
[Swift] Please bootstrap Swift track

### ISSUE THREAD

**Issue by wneumann** [exercism/v3#1514]
After some time reading docs, listening to the calls, etc. I believe I'm ready to start building up the Swift v3 track. Assuming you're still looking to add languages to v3, please bootstrap the Swift v3 track.

I've been putting in some work on concepts and a test runner, and am ready to jump in.

**Comment by ErikSchierboom** [comment]
@wneumann This is brilliant! I've created https://github.com/exercism/v3/pull/1532 to bootstrap the track. Could you do the following:

- [Add yourself as a maintainer to the track](https://github.com/exercism/swift/blob/master/config/maintainers.json). This will ensure that you have the right permissions in this repo. Please add yourself with the `show_on_website` key set to `false`.
- Once https://github.com/exercism/v3/pull/1532 has been merged, could you add yourself as a contributing maintainer to the [`languages/swift/maintainers.md` file](https://github.com/exercism/v3/pull/1532/files#diff-047e833e7c47b80dd1b29da370b82c4d)? For the correct format, see [this example file](https://github.com/exercism/v3/blob/master/languages/ruby/maintainers.md).
- [Create an issue for a test runner repository](https://github.com/exercism/automated-tests/issues/new?assignees=&labels=&template=new-test-runner.md&title=%5BNew+Test+Runner%5D+). This will result in someone from the Exercism team creating a repository for your test runner.

Great to have you on board!

**Comment by wneumann** [comment]
@ErikSchierboom I took care of the first step, though one of the CircleCi checks is failing with the following error while trying to install a gem:

```
Fetching: danger-8.0.0.gem (100%)
ERROR:  Error installing danger:
	danger requires Ruby version >= 2.4.0.
```

**Comment by ErikSchierboom** [comment]
@wneumann I'm not a Swift maintainer, so I don't know if and how to fix that. What I would suggest you do, is to use this invitation to join our Slack channel: https://join.slack.com/t/exercism-team/shared_invite/enQtNDEyMDM0OTgzNzY1LTU2ZDE2MGIzZmJmMDY3MDc1M2MxMzA0YjkwNjYyY2E1ZWJmNDRjNjVhMzc4OGQzOTU3Y2JkMTQ3ZTA5MWI3OGU

There you will find a lot of channels but there are two that are of specific interest to you:
- #v3: A discussion space for the development of Exercism v3
- #maintaining-swift: A space where you can work with other maintainers to plan out and action the creation of your v3 track.

Please introduce yourself to the community in #introductions, and also add a note to the #maintaining-swift channel saying you'll be helping as a new maintainer. You can ask the maintainers there about the CI failure and what to do with it.

**Comment by ErikSchierboom** [comment]
@wneumann With the permissions not yet sorted, I've gone and merged https://github.com/exercism/v3/pull/1532 so that you can start building the v3 Swift track! Let me know if you need any help/pointers.
