### ISSUE TITLE
[Nim] Please bootstrap Nim track

### ISSUE THREAD

**Issue by ynfle** [exercism/v3#1562]
We have mostly completed the test-runner.
Looking forward to contributing to v3!!!!

**Comment by ErikSchierboom** [comment]
@ynfle It's great that you'll be working on the Nim track! I've created a [PR to bootstrap the Nim track](#1566). We'll get it merged this afternoon. Once it is merged, you can submit a PR to add yourself to the `languages/nim/maintainers.md` document (you're a contributing maintainer). In parallel, you should submit a PR to the add yourself 
to the [Nim track's maintainers.json file](https://github.com/exercism/nim/blob/master/config/maintainers.json), as that will assign you the correct permissions for this repo once merged. Note: please add yourself as a maintainer with the `show_on_website` field set to `false`.

**Comment by ynfle** [comment]
Thanks! Looking forward
