### ISSUE TITLE
[Nim] Add nim to v3 dashboard

### ISSUE THREAD

**Issue by ynfle** [exercism/v3#1574]
The Nim track was recently bootstrapped, can it be added to the [v3 dashboard](https://v3.exercism.io)?

**Comment by SleeplessByte** [comment]
You can PR it [to this file](https://github.com/exercism/v3-dashboard/blob/master/src/data/tracks.json) !

**Comment by ynfle** [comment]
Thanks @SleeplessByte, I assumed because it looked the same as https://tracks.exercism.io, that you were the maintainer. I guess @ErikSchierboom liked your design so much.

**Comment by SleeplessByte** [comment]
@ynfle we actually had a discussion about how we'd do this for v3, and I told him a fork would be best so that they can actually diverge 💯
