### ISSUE TITLE
[DOCS] Repo Wide List of Implemented Exercises - again

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#1606]
In (#1510) I asked:

Is there a list of implemented exercises for the whole repo showing exercise/concept name and implemented language? If not, can we have one? It would be useful when looking for an exercise to fork.

@ErikSchierboom replied:

We don't have a list per implemented language, but we do have something like that: https://github.com/exercism/v3/blob/master/reference/stories/README.md

I acquiesced.

@Ihid Can we reconsider reprioritising the idea of a dynamic list of repo-wide language/exercise pairs to sit along side the curated story list?  I almost missed out on @neenjaw's excellent tuples exercise in elixir when considering the C# one because it does not appear in the curated list.

I would claim this is a prerequisite before getting the mass of contributors on board.

**Comment by ErikSchierboom** [comment]
@iHiD Yep, I definitely could. @mikedamay could you create an issue for this at https://github.com/exercism/v3-dashboard?

**Comment by mikedamay** [comment]
Issue 45 created in https://github.com/exercism/v3-dashboard
