### ISSUE TITLE
[CI] Format workflow file error

### ISSUE THREAD

**Issue by neenjaw** [exercism/v3#1609]
In the last day I have received a few emails regarding a failed workflow on the master branch:

https://github.com/exercism/v3/actions/runs/131261191

Which is saying that there is an error in the workflow file:

> The workflow is not valid. .github/workflows/format-code.yml (Line: 20, Col: 13): Unexpected symbol: '"false"'. Located at position 34 within expression: steps.fork_check.outputs.fork == "false"

See `.github/workflows/format-code.yml`:

https://github.com/exercism/v3/blob/b2fa50a2df34d3aacfe2339ce523fa1b793f599a/.github/workflows/format-code.yml#L20

Tagging @SaschaMann and @ErikSchierboom just because they are mentioned in the `gitblame`

**Comment by SaschaMann** [comment]
Should be fixed by https://github.com/exercism/v3/commit/2b62cd89d1fdb9e549ac5e6e43600338bc609a76
