### ISSUE TITLE
[Go] How to implement a Go concept exercise

### ISSUE THREAD

**Issue by tehsphinx** [exercism/v3#161]
[This document](https://github.com/exercism/v3/blob/master/languages/go/docs/implementing-a-concept-exercise.md) needs a first implementation. It should be targeted at non-maintainers that want to help out on a one-off basis.

As a start I suggest to look at [C#'s implementation guide](https://github.com/exercism/v3/blob/master/languages/csharp/docs/implementing-a-concept-exercise.md) and adjust that to Go's needs. From there it can be improved as we as maintainers get a better understanding of the process ourselves.

As a base we can copy this:  https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md

**Comment by sultanarif-p** [comment]
okkk

**Comment by tehsphinx** [comment]
@sebito91: Is there any progress on this already we can build on or should I just start something?

**Comment by tehsphinx** [comment]
I'm going to go ahead on this.
