### ISSUE TITLE
[C#] Modify instructions.md: chars

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#1610]
The exercise currently quietly allows for an empty string to be output as an identifier.  Change story to show that an empty string should be treated as an error condition.  Ensure that empty input strings are also mentioned.  

I'm trying to avoid adding complexity to the code.

**Comment by mikedamay** [comment]
The original discussion was as follows:

 ErikSchierboom on 11 Jun Member

Story-wise, having empty identifiers is the only thing left that might not make much sense (how would one use an empty identifier?). Was there a specific reason that you wanted to allow for empty identifiers?
@mikedamay
mikedamay on 11 Jun Author Member

I will raise a subsequent PR to tweak the wording. I want to avoid checks for empty output strings as that will increase complexity. I currently have no feel for the sort of problems exercises pose to presenters but can only imagine that simpler is better.
@ErikSchierboom
ErikSchierboom on 11 Jun Member

Okay, makes sense.

The current instruction reads:

Note that the Clean method should treat an empty string as valid.

I suggest we change it to:

If the `Clean()` method returns an empty string this should be treated by the caller as an error.  Note, in addition that empty strings can be passed to the `Clean()` routine and an empty string should be returned (indicating an error).

**Comment by ErikSchierboom** [comment]
I'm fine with that!
