### ISSUE TITLE
[Docs] Giving credit and citing sources

### ISSUE THREAD

**Issue by SaschaMann** [exercism/v3#163]
This is a write-up of an [AMA question](https://exercism-team.slack.com/archives/CR91YFNG3/p1579275473054100) on Slack, which itself was a follow-up question to a [previous discussion](https://exercism-team.slack.com/archives/CR91YFNG3/p1579125573041000). It's meant as a discussion starter.

@NobbZ, @Stargator, @iHiD, @ErikSchierboom, @SleeplessByte, @kotp thanks for engaging in the discussion around my question. Please edit the post and correct me if you feel that I've misrepresented one of your points in this write-up. Despite the topic, I chose to not cite everyone individually to keep it more concise, I hope that's okay with you.

---

Right now, the [concept docs](https://github.com/exercism/v3/tree/master/reference) lack any kind of consistency when it comes to citing the sources they're based on. [Some](https://github.com/exercism/v3/blob/master/reference/concepts/ascii.md) are direct quotes but lack any kind of source, [others](https://github.com/exercism/v3/blob/master/reference/concepts/multiple-dispatch.md) have an APA style citation, and some are original works not based on an existing source.

There seemed to be a consensus that if sources are used, they should be properly attributed. However, what "properly attributed" means is unclear. Therefore it would be useful to agree on a minimum standard.

Sidenote: This is primarily about the concept documents used "internally", not the docs exposed to students.

**Why should sources be cited?**

- Legal reasons (although the documents are for "internal" purposes, they're still publicly available).
- A way to thank the original creator for creating a wonderful resource.
- The documents are a source of truth and need to be verifiable.
- They can help understand the concept/problem better.
- The docs can also contain info that can be readily copy-pasted into exercise READMEs.

**How should they be cited?**

There was no consensus on this. The following ways were brought up:

- Link dump (a list of links used while creating the source)
- Only adding sources for direct quotes, otherwise adding links where one can find more but not directly citing non-quoted content.
- Deep-linking could be hard to maintain in the long run.
- Cite the original author, URL, date of creation/last modification (explicitely state if those are not available), publisher.
- Putting the citation in a comment.

This brings up further questions that need to be considered:

- Does every document **need** to have sources or are documents written purely from pre-existing knowledge okay, too?
- Are the citations purely for giving attribution or do they also serve as a way to verify the contents of the doc?
- Do we even want a citation guide to refer to, or do we leave it up to whomever submits and reviews the PR?

**Comment by SaschaMann** [comment]
My own preference would be a **mandatory** list of all sources that were used at the bottom of each concept document. Numbering them and adding footnotes behind statements/definitions would be nice to have but overkill for this context. Writing things purely based on pre-existing knowledge comes with a high risk of introducing mistakes. Since these documents are to some extent a source of truth, they should be reliable. This will also make it easier to copy contents into the READMEs.

As for the format, I agree with @NobbZ suggestion to list the author, title, URL, date and publisher. If it's an URL that looks unstable (e.g. a blog post), perhaps it makes sense to create an archive link. When citing Wikipedia, a book or anything else that has an easy available way to create a citation, that should be used, even if the format differs or contains additional information.

**Comment by kotp** [comment]
Citations may be complicated to maintain if we have documents contained within documents.

**Comment by kotp** [comment]
That said, [ZoteroBib](https://zbib.org/) might be a decent occasional use tool, no plugins, no software to install.

**Comment by SleeplessByte** [comment]
> Do we even want a citation guide to refer to, or do we leave it up to whomever submits and reviews the PR?

I rather have some consistency. I really like what @kotp linked because it's _straightforward_. Dump the url into the bar, press `cite` and press copy. I think we should make this the guideline.

For that reason I've kicked it off with #179. I have added a _lot_ of content to the concepts, and only those in a quote block are direct copies. You can google the content to find the source right now, but if someone feels like updating them alll, please do.

> While it's a bit more work than a simple link, there are tools1 to make it easy to create a reference for any website and the benefits outweigh the extra 10 seconds in the long run, IMO. I don't care about the format as long as the relevant information is there.

I don't agree with this. It's easy enough to go into the wayback machine, because you have the date and the URL. I think _requiring_ someone to take the url, cite it, archive it and replace it, will be (at least for me) _too much_ effort to even want to cite anything.

**Comment by SaschaMann** [comment]
> I don't agree with this. It's easy enough to go into the wayback machine, because you have the date and the URL. I think requiring someone to take the url, cite it, archive it and replace it, will be (at least for me) too much effort to even want to cite anything.

I mostly meant that the extra step of going to ZoteroBib is more work than just a link. I agree that archiving it is probably overkill. Also just realised that our CI should catch links that disappear, so it would only take one person to change the link to the wayback machine when that happens.

**Comment by kotp** [comment]
> You can google the content to find the source right now

That was the problem I ran against with ASCII concept information.  I searched (but did not "Google" to find the source, and found many sources, but can't find _the_ source.

**Comment by NobbZ** [comment]
> Also just realised that our CI should catch links that disappear

Content can dissapear while the link stays alive.

Just consider my personal blog. After I missed a deadline for renewal years ago, the domain was grabbed within minutes after becomming available again.

The "this domain is for sale" was online and available within the DNS timeout. Regardless of the path you query, regardless of the method. You get a page back.

This is an extreme example.

But a simple edit or reorganizing of pages is possible with improper mapping between old and new URLs.

This does not mean that I am in favor of self-archiving cited content, but I'm only the opinion that the linkchecker might not only give false negatives in case of network or maintanence hickups, but also false positives.

**Comment by kotp** [comment]
@aimorris Any reason the status/help-wanted label was removed?

**Comment by iHiD** [comment]
I think we should keep help-wanted for wanting help *outside* of the maintainer group, ie when we want to welcome general contributors to work on an issue. I will add/refactor some tags tomorrow including making sure there is one for something like status/want-maintainers-opinions.

**Comment by iHiD** [comment]
That said, as a rule I don't think maintainers should remove labels that other maintainers add, without something tangible having changed, or consulting then first.

**Comment by aimorris** [comment]
@kotp This is just a discussion isn't it? No one has actually specified what they want some third-party to help with.

**Comment by kotp** [comment]
Right, I just thought it was odd that the one that added it wasn't asked or was the one that removed it.

**Comment by iHiD** [comment]
> This is just a discussion isn't it? No one has actually specified what they want some third-party to help with.

@aimorris I think the key thing here is asking the maintainer why they added it, rather than overruling their addition of it. As I said, I agree with not having the label, but I think it's important to ask the person that asked it before arbitrarily changing things.

**Comment by SaschaMann** [comment]
> I think we should keep help-wanted for wanting help outside of the maintainer group, ie when we want to welcome general contributors to work on an issue.

Ah okay, I used the label to show that I want input from other maintainers. It's not relevant to the actual issue though, so I'm gonna hide the responses.

**Comment by ErikSchierboom** [comment]
I really like the format @SleeplessByte used in https://github.com/exercism/v3/pull/179/files#diff-d1e6e01454ea0ecb4ae4245174990dc2. Is everyone happy with that style?

**Comment by kotp** [comment]
> I really like the format @SleeplessByte used in https://github.com/exercism/v3/pull/179/files#diff-d1e6e01454ea0ecb4ae4245174990dc2. Is everyone happy with that style?

To show the content here: 

```
## Sources

1. ‘ASCII’. Wikipedia, 12 Jan. 2020. Wikipedia, https://en.wikipedia.org/w/index.php?title=ASCII&oldid=935468511.
```

The only thing that I think may be missing for a Wikipedia reference like that is the phrase "as accessed (whatever date it was accessed)".

**Comment by ErikSchierboom** [comment]
@kotp Isn't that the "12 Jan. 2020" part?

**Comment by kotp** [comment]
> @kotp Isn't that the "12 Jan. 2020" part?

I thought that was the published date, not the accessed date.

**Comment by ErikSchierboom** [comment]
Right!

**Comment by SleeplessByte** [comment]
It's the *accessed date*. The published date doesn't make sense for living documents such as that. It _links_ to the actual version at moment of "access", and not the living document.' If you keep "published" date, then you also have to keep revisions.

When citing a book, you'll cite the revision, not the original publication.

**Comment by neenjaw** [comment]
Is it resolved? Is this the settled way?

**Comment by iHiD** [comment]
@SleeplessByte In the example above, why does it say "Wikipedia" twice? Could you write out the format with placeholders as an example pls?

**Comment by kotp** [comment]
#783 recently made use of "Science of Computer Programming" style as [described here](https://paperpile.com/s/science-of-computer-programming-citation-style/#examples-website-citations).  It is the form that I most often use given the subject matter.

**Comment by iHiD** [comment]
OK. We're going to standardise on that. Thank you all for the discussion. I'll put a PR in.
