### ISSUE TITLE
[C#] Exercises in Priority Order

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#1645]
Supersedes #1533

**Comment by mikedamay** [comment]
The following is a list of exercises based on [the concept doc](https://github.com/exercism/v3/blob/master/languages/csharp/reference/README.md).

The list is split into 4 sections
1.  Introduction to C#
2. Introduction to C# (Duplicates & Non-Exercises)
3. Essential C# Topics (not covered by C# Introduction)
4. Advanced C# Topics

If we wanted to do a beta then section 1 provides a coherent set of topics sufficient to allow a graduate to write console programs in a fluent fashion (assuming we explain `Main()` to them).  There are exactly 42 topics, a number that speaks for itself.  Some of the decisions hurt in reducing the number of topic to around 40 so I hope any commenter will also support the ambition to minimize the number of topics.

A minimum full track would require 23 more topics (the first 23 lines of section 3).

The columns are as folllows:
- Row number
- Name of exercise of concept
- Priority (Rank)
- Status
- Link
- Further Information


Rank has the following meaning - these are the original ranks roughly agreed between @mikedamay and @ErikSchierboom and I have not touched them.  They relate to the full track rather than an introductory track.

Rank:
- 5 means exercise already implemented
- 10 - 49 general C# exercises in priority order
- 50 - 55 LINQ related exercises
- 700 - Possible exercises or possibly just background info
- 800 - assumed duplicate / handled in a previous exercise (denoted by Further Information)
- 997 - 998 I did not really understand how these fitted in.
- 999 - assumed these were meant to be headings (in the original concepts doc).

Status:
- E = exercise (where _Further Info_ contains a link to the design doc)
- I = new concept exercise issue raised  (where _Further Info_ contains a link to the issue)
- D = duplicate (concept included in another exercise) (where _Further Info_ is the main exercise)

|     |Concept Name                                                          | Rank|      Status| Link| Further Info
|----|----------------------------------------------------------------------|-----|------------|------------|-----|
| |                                                                      | |            | | |99999|
| |Introduction To C#                                                    | |            | | |99999|
| |                                                                      | |            | | |99999|
|   6|- [Classes][classes]                                                  |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/classes/.meta/design.md )| |   11|
|   7|- [Inheritance][inheritance]                                          |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/inheritance/.meta/design.md )| |   16|
|   8| basics (including methods)                                           |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/basics/.meta/design.md )| |   19|
|   9|  - Constructors                                                      |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/constructors/.meta/design.md )| |   20|
|  10|  - Method overloading                                                |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/method-overloading/.meta/design.md )| |   27|
|  11|- Properties                                                          |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/properties/.meta/design.md )| |   33|
|  12|- Null                                                                |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/nullability/.meta/design.md )| |   95|
|  13|- Numbers                                                             |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/numbers/.meta/design.md )| |  100|
|  14|- [Booleans][bool]                                                    |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/booleans/.meta/design.md )| |  129|
|  15|- [Characters][char]                                                  |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/chars/.meta/design.md )| |  130|
|  16|  - [Arrays][array]                                                   |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/arrays/.meta/design.md )| |  132|
|  17|  - [Dictionaries][map]                                               |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/dictionaries/.meta/design.md )| |  133|
|  18|- Dates                                                               |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/datetimes/.meta/design.md )| |  141|
|  19|- Enums                                                               |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/enums/.meta/design.md )| |  144|
|  20|  - Floating point numbers                                            |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/floating-point-numbers/.meta/design.md )| |  150|
|  21|- [Strings][string]                                                   |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/strings/.meta/design.md )| |  154|
|  22|Flag Enums                                                            |    5|           E|[Link]( https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/flag-enums/.meta/design.md )| | 2006|
|  23|- [Interfaces][interfaces]                                            |   10|           I|[Link]( https://github.com/exercism/v3/issues/1225 )| |   17|
|  24|  - Method arguments / parameters                                     |   10|           I|[Link]( https://github.com/exercism/v3/issues/1128 )| |   23|
|  25|  - [Equality][equality] (`Equals`, `GetHashCode`)                    |   10|           I|[Link]( https://github.com/exercism/v3/issues/1016 )| |   75|
|  26|  - Signed integers                                                   |   10|           I|[Link]( https://github.com/exercism/v3/issues/780 )| |  151|
|  27|Constants/readonly                                                    |   10|           I|[Link]( https://github.com/exercism/v3/issues/1044 )| | 2008|
|  28|  - Conditionals: do-while                                            |   12|           I|[Link]( https://github.com/exercism/v3/issues/1631 )| |   82|
|  29|  - Conditionals: switch                                              |   13|           I|[Link]( https://github.com/exercism/v3/issues/1633 )| |   83|
|  30|  - [Conditionals: if][conditionals]                                  |   11|           I|[Link]( https://github.com/exercism/v3/issues/1634 )| |   85|
|  31|  - [Conditionals: ternary][conditionals]                             |   14|           I|[Link]( https://github.com/exercism/v3/issues/1635 )| |   86|
|  32|- Exceptions                                                          |   15|           I|[Link]( https://github.com/exercism/v3/issues/966 )| |   94|
|  33|  - [Lists][list]                                                     |   15|           I|[Link]( https://github.com/exercism/v3/issues/958 )| |  136|
|  34|  - Object initializers                                               |   20|           I|[Link]( https://github.com/exercism/v3/issues/1637 )| |   31|
|  35|- Structs                                                             |   20|           I|[Link]( https://github.com/exercism/v3/issues/1017 )| |   36|
|  36|- Expression-bodied members                                           |   20|           I|[Link]( https://github.com/exercism/v3/issues/1145 )| |   42|
|  37|  - Namespaces                                                        |   20|           I|[Link]( https://github.com/exercism/v3/issues/1127 )| |  114|
|  38|- String formatting                                                   |   20|           I|[Link]( https://github.com/exercism/v3/issues/962 )| |  117|
|  39|- [Tuples][tuple]                                                     |   20|           I|[Link]( https://github.com/exercism/v3/issues/963 )| |  157|
|  40|User Defined Exceptions                                               |   20|           I|[Link]( https://github.com/exercism/v3/issues/1141 )| | 2004|
|  41|- Regular Expressions                                                 |   24|           I|[Link]( https://github.com/exercism/v3/issues/1638 )| |  106|
|  42|  - Resource cleanup (`IDisposable`)                                  |   28|           I|[Link]( https://github.com/exercism/v3/issues/1639 )| |  108|
|  43|  - Resource lifetime                                                 |   28|           I|[Link]( https://github.com/exercism/v3/issues/1640 )| |  109|
|  44|- Randomness                                                          |   29|           I|[Link]( https://github.com/exercism/v3/issues/1642 )| |  104|
|  45|  - Arithmetic overflow                                               |   30|           I|[Link]( https://github.com/exercism/v3/issues/1138 )| |  101|
|  46|- Nested types                                                        |   30|           I|[Link]( https://github.com/exercism/v3/issues/1643 )| |  148|
|  47|- Time                                                                |   30|           I|[Link]( https://github.com/exercism/v3/issues/1644 )| |  156|
| |                                                                      | |            | | |99999|
| |Introduction To C# (Duplicates & Non-exercises)                       | |            | | |99999|
| |                                                                      | |            | | |99999|
|  51|- [Composition][composition]                                          |  700|            | | background|   12|
|  52|- Expressions vs statements                                           |  700|            | | background|   43|
|  53|- [Pattern matching][pattern_matching]                                |  700|            | | background|   54|
|  54|- [Encapsulation][encapsulation]                                      |  800|           D| | classes|   13|
|  55|- Fields                                                              |  800|           D| | classes|   14|
|  56|  - Explicit Interface Implementation                                 |  800|           D| | interfaces|   18|
|  57|    - Named arguments                                                 |  800|           D| | method arguments|   24|
|  58|    - Out parameters                                                  |  800|           D| | method arguments|   25|
|  59|    - [Optional arguments][optional_arguments]                        |  800|           D| | method arguments|   26|
|  60|  - Return values                                                     |  800|           D| | basics|   28|
|  61|- [Mutation][mutation]                                                |  800|           D| | basics|   29|
|  62|- [Objects][objects]                                                  |  800|           D| | classes|   30|
|  63|- [Polymorphism][polymorphism]                                        |  800|           D| | inheritance|   32|
|  64|- [State][state]                                                      |  800|           D| | classes|   34|
|  65|- [Functions][functions]                                              |  800|           D| | basics|   44|
|  66|- [Type inference][type_inference]                                    |  800|           D| | basics|   56|
|  67|- Collections                                                         |  800|           D| | |   62|
|  68|- Comments                                                            |  800|           D| | basics|   73|
|  69|- Conditionals                                                        |  800|           D| | numbers|   80|
|  70|  - Boolean logic                                                     |  800|           D| | booleans|   81|
|  71|  - Conditionals: while                                               |  800|           D| | floating point numbers|   84|
|  72|  - Implicit                                                          |  800|           D| | explicit casts|   90|
|  73|  - Null-coalescing operator                                          |  800|           D| | null|   96|
|  74|  - Null-conditional operator                                         |  800|           D| | null|   97|
|  75|  - Null-forgiving operator                                           |  800|           D| | null|   98|
|  76|  - Nullable values                                                   |  800|           D| | null|   99|
|  77|  - Bitwise manipulation                                              |  800|           D| | flag-ennums|  102|
|  78|  - Math operators                                                    |  800|           D| | numbers|  103|
|  79|- Scoping                                                             |  800|           D| | basics|  112|
|  80|  - Visibility (`public`, `private`, etc.)                            |  800|           D| | classes|  115|
|  81|  - Formatting types                                                  |  800|           D| | string formatting|  118|
|  82|  - Interpolation                                                     |  800|           D| | string formatting|  119|
|  83|  - StringBuilder                                                     |  800|           D| | string formatting|  120|
|  84|- [Variables][variables]                                              |  800|           D| | basics|  122|
|  85|  - Assignment                                                        |  800|           D| | numbers|  123|
|  86|  - Default values (a `bool` being `false` by default, etc.)          |  800|           D| | classes|  124|
|  87|- Numbers                                                             |  800|           D| | numbers|  149|
|  88|  - Unsigned integers                                                 |  800|           D| | signed integers|  152|
|  89|Abstract classes and members                                          |  800|           D| | inheritance| 1001|
|  90|Pattern Matching Constants                                            |  800|           D| | enums| 2001|
|  91|Marker interfaces                                                     |  800|           D| | Equality and Interfaces-(discussion only)| 2102|
|  92|Generics Introduction                                                 |  800|           D| | Lists|   70|
|  93|  - Explicit (casts)                                                  |  800|          ID|[Link]( https://github.com/exercism/v3/issues/1142 )| signed integers|   89|
|  94|Indexers Introduction                                                 |  800|           D| | dictionaries|   70|
|  95|  - Imports (usings)                                                  |  800|           D| | namespaces|  113|
|  96|  - [Sets][set]                                                       |  800|            | | Equality|  139|
|  97|  - Ordering                                                          |  997|            | | |   76|
|  98|- Indexes                                                             |  998|            | | |  146|
|  99|- Comparison                                                          |  999|            | | |   74|
| 100|- Conversions                                                         |  999|            | | |   87|
| 101|- Enumeration                                                         |  999|            | | |   91|
| 102|- Resources                                                           |  999|            | | |  107|
| 103|- Collections                                                         |  999|            | | |  131|
| |                                                                      | |            | | |99999|
| |Essential C# Topics (Not Covered By Introduction)                     | |            | | |99999|
| |                                                                      | |            | | |99999|
| 107|- Delegates                                                           |   18|            | | |  143|
| 108|- Attributes                                                          |   25|           I|[Link]( https://github.com/exercism/v3/issues/1176 )| |   61|
| 109|- Reflection                                                          |   25|            | | |  105|
| 110|- Events                                                              |   30|            | | |  145|
| 111|- Streams                                                             |   35|            | | |  153|
| 112|- Tasks                                                               |   35|            | | |  155|
| 113|- Asynchronous programming                                            |   40|            | | |   60|
| 114|    - Generics Constraints                                            |   40|            | | |   71|
| 115|    - Covariance/Contravariance                                       |   40|            | | |   72|
| 116|  - Concurrent collections                                            |   40|            | | |   78|
| 117|  - Locks                                                             |   40|            | | |   79|
| 118|Serialization                                                         |   45|            | | | 2101|
| 119|  - Extension methods                                                 |   50|           I|[Link]( https://github.com/exercism/v3/issues/1070 )| LINQ|   22|
| 120|- Statics                                                             |   50|            | | LINQ|   35|
| 121|  - [Anonymous functions][anonymous_functions]                        |   50|            | | LINQ|   45|
| 122|  - [Higher-order functions][higher_order_functions]                  |   50|            | | LINQ|   46|
| 123|- [LINQ][linq]                                                        |   50|            | | LINQ|   49|
| 124|- Anonymous types                                                     |   50|            | | LINQ|  128|
| 125|  - Enumerables                                                       |   50|            | | LINQ|  134|
| 126|  - Advanced (GroupBy, Join, Zip, Cast, GroupJoin, AsEnumerable)      |   55|            | | LINQ|   50|
| 127|  - Query Syntax                                                      |   55|            | | LINQ|   52|
| 128|  - SelectMany                                                        |   55|            | | LINQ|   53|
| 129|  - Iterators (yield)                                                 |   55|            | | LINQ|   68|
| 130|- [Immutability][immutability]                                        |  700|            | | background|   48|
| 131|  - Method Classification (deferred, non-streaming etc.)              |  700|            | | background|   51|
| 132|- Concurrency                                                         |  700|            | | background|   77|
| 133|  - Collections: combining                                            |  800|           D| | See LINQ|   63|
| 134|  - Collections: filtering                                            |  800|           D| | See LINQ|   64|
| 135|  - Collections: mapping                                              |  800|           D| | See LINQ|   65|
| 136|  - Collections: ordering                                             |  800|           D| | See LINQ|   66|
| 137|  - Collections: reducing                                             |  800|           D| | See LINQ|   67|
| 138|  - [Generics][generics]                                              |   40|            | | This refers to user-defined generics.|   70|
| 139|- Indexers                                                            |   20|            | | This refers to user-defined indexers|   15|
| 140|- [Recursion][recursion]                                              |   30|            | | |   55|
| 141|Pattern Matching Types                                                |   30|[Link]( https://github.com/exercism/v3/issues/546 )| | 2002|
| 142|Pattern Matching Tuples                                               |   30|           I|[Link]( https://github.com/exercism/v3/issues/964 )| | 2003|
| 143|  - [Enumeration: for loop][enumeration]                              |  997|            | | |   92|
| 144|  - [Enumeration: foreach loop][enumeration]                          |  997| | |   93|
| |                                                                      | |            | | |99999|
| |Advanced C# Topics                                                    | |            | | |99999|
| |                                                                      | |            | | |99999|
| 148|  - Immutable collections                                             |   28|            | | |  135|
| 149|  - Resource passing (by reference/by value)                          |   30|            | | |  110|
| 150|  - [Resource allocation][memory_allocation]                          |   30|           I|[Link]( https://github.com/exercism/v3/issues/1018 )| |  111|
| 151|  - [Queues][queue]                                                   |   30|            | | |  137|
| 152|  - [Ranges][range]                                                   |   30|            | | |  138|
| 153|  - Time zones                                                        |   30|            | | |  142|
| 154|Resource Pooling                                                      |   30|           I|[Link]( https://github.com/exercism/v3/issues/1146 )| | 2005|
| 155|dynamic                                                               |   30|            | | | 2103|
| 156|  - [Local functions][local_functions]                                |   45|            | | |   47|
| 157|  - Boxing/unboxing                                                   |   45|            | | |   88|
| 158|- Slicing                                                             |   45|            | | |  116|
| 159|- Unsafe code                                                         |   45|            | | |  121|
| 160|- Lazy&lt;T&gt;                                                       |   45|            | | |  147|
| 161|Pointers                                                              |   45|           I|[Link]( https://github.com/exercism/v3/issues/1147 )| | 2007|
| 162|multi-dimensional array (incl Array.CreateInstance                    |   45|            | | | 2100|
| 163|  - [Stacks][stack]                                                   |   48|            | | |  140|
| 164|  - Destructors                                                       |   49|            | | |   21|
| 165|    - Async iterators                                                 |   49|            | | |   69|

**Comment by mikedamay** [comment]
This is superseded by the exercise-report action introduced by PR #2162 

See https://github.com/exercism/v3/blob/master/languages/csharp/reference/README.md

**Comment by ErikSchierboom** [comment]
Awesome!
