### ISSUE TITLE
[Clojure] Missing exercise entries in config.json

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1701]
The track's `config.json` file is missing an entry for the following exercise:

- `lists`

**Comment by ErikSchierboom** [comment]
FYI @exercism/clojure

**Comment by bemself** [comment]
@ErikSchierboom Thanks for reminding, raised pr [[Clojure] config.json: add lists, and minor update in doc by bemself · Pull Request #1721 · exercism/v3](https://github.com/exercism/v3/pull/1721)

by the way, we have more concepts than lists, but those PRs not yet merged, possible to merge a few of them now?

**Comment by porkostomus** [comment]
I reworked the `basic-functions` into just `basics` and it is currently in draft. I csuppose we could merge it for now but I keep telling myself I just just finish it...

**Comment by ErikSchierboom** [comment]
> I suppose we could merge it for now but I keep telling myself I should just finish it...

I'm fine with merging it and then improving it later if you like that.

**Comment by porkostomus** [comment]
Fixed by #2775
