### ISSUE TITLE
[Elixir] Missing exercise entries in config.json

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1702]
The track's `config.json` file is missing an entry for the following exercise:

- `access`

**Comment by ErikSchierboom** [comment]
FYI @exercism/elixir

**Comment by neenjaw** [comment]
Interesting.

**Comment by ErikSchierboom** [comment]
@neenjaw This is probably because the directory name is `access` and the slug is `access-behaviour` from a quick inspection.

**Comment by neenjaw** [comment]
Ah, yes, that's why.  We changed it from access to access-behaviour and didn't rename the directory. I can fix that.
