### ISSUE TITLE
[Swift] Missing exercise entries in config.json

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1704]
The track's `config.json` file is missing an entry for the following exercise:

- `arrays`
- `basics`
- `conditionals`
- `numbers`
- `optionals`
- `strings`

**Comment by ErikSchierboom** [comment]
FYI @exercism/swift

**Comment by wneumann** [comment]
I'll take care of this today.

**Comment by wneumann** [comment]
Created a PR to address this (https://github.com/exercism/v3/pull/1724).

It just needs a review from exercism/swift.

**Comment by wneumann** [comment]
This was closed with PR https://github.com/exercism/v3/pull/1724
