### ISSUE TITLE
[C#] strings - add concatenation to introduction

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1746]
## Goal

The [`introduction.md` document of the `strings` exercise](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/strings/.docs/introduction.md) does not introduce the syntax needed to concatenate strings, which the student _does_ need to do. An short explanation and syntax example should be added to the `introduction.md` document on how to use the `+` operator or string interpolation to format strings. The contents for this can be extracted from the [`after.md` document](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/strings/.docs/after.md).

## Help

If you have any questions while improving the exercise, please post the questions as comments in this issue.

**Comment by aes421** [comment]
@ErikSchierboom I will do this as part of hacktoberfest.  I don't understand what you mean in the last sentence "The contents for this can be extracted from the after.md document."

**Comment by ErikSchierboom** [comment]
@aes421 Great! The `after.md` document has been replaced. You can now look for the concatenation text in: https://github.com/exercism/v3/blob/master/languages/csharp/concepts/strings/about.md. 

Note that the links should be removed.
