### ISSUE TITLE
[CI] Summary of summary suggestions

### ISSUE THREAD

**Issue by SaschaMann** [exercism/v3#1756]
Some suggestions regarding the summaries in no particular order. Some of them have been brought up in review comments before but I'm repeating them here to make it easier to find them.

- Automatically request a review from the person who merged the PR that triggered the push event. Otherwise nobody will be notified.
- Create a label `type/auto-generated` for easy filtering
  - Additionally, use a different tag than `[CI]`
- Move all auto-generated branches into one "folder" of branches, e.g. `auto/summaries/...` or `summaries/...`
- Mark auto-generated files as generated in `.gitattributes`
- Consider auto-merging the summary PRs through an app or machine user

@iHiD @ErikSchierboom

**Comment by iHiD** [comment]
> Automatically request a review from the person who merged the PR that triggered the push event. Otherwise nobody will be notified.

Suggest auto-review from @ErikSchierboom as well.

> Mark auto-generated files as generated in .gitattributes

What does this do?

> Consider auto-merging the summary PRs through an app or machine user

For this we'd need two bots - one to approve and another to merge.

**Comment by SaschaMann** [comment]
> What does this do?

Hides them from repo stats and diffs: https://help.github.com/en/github/administering-a-repository/customizing-how-changed-files-appear-on-github

**Comment by ErikSchierboom** [comment]
These are all nice suggestions. I'll implement them

**Comment by ErikSchierboom** [comment]
See #1759
