### ISSUE TITLE
[C#] Improve Concept Exercise: datetimes

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#1804]
DateTmesTests.cs rely on a supposed `UseCultureAttribute` provided by _Xunit_ to ensure that the US culture is used in tests.  This doesn't appear to be a thing in the latest xunit.  Broken links and general sadness.  [This](https://github.com/xunit/xunit/issues/1605) delves into the state of affairs.

We will have done something to address this in the `time` exercise.

In fact the following did the trick
```
public TimeTests()  // constructor
{
    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
}
```

**Comment by ErikSchierboom** [comment]
> DateTmesTests.cs rely on a supposed UseCultureAttribute provided by Xunit to ensure that the US culture is used in tests.

We implement that attribute ourselves at the bottom of the file: https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/datetimes/DateTimesTests.cs#L162 BUt I agree that your solution is simpler and thus preferrable.

**Comment by mikedamay** [comment]
@ErikSchierboom 

> I agree that your solution is simpler and thus preferrable

Do we want to close this issue or modify DateTimesTests.cs?

I don't think it can be classed as a "good first issue" any more.

**Comment by ErikSchierboom** [comment]
> Do we want to close this issue or modify DateTimesTests.cs?

I would prefer modifying the `DataTimesTests.cs` file to use your solution.

> I don't think it can be classed as a "good first issue" any more.

It isn't? I think adding the constructor code and removing the existing `UseCultureAttribute` is something that is easy to do for someone, or do you disagree?

**Comment by mikedamay** [comment]
I have replaced this with #1811.

> It isn't? 

My thinking was that if I was new on the project and picked up an issue where the OP was under a misapprehension about the problem and the original developer had not been explicit about the proposed resolution I would give it a wide birth.

**Comment by ErikSchierboom** [comment]
The new issue is better 👍
