### ISSUE TITLE
[C#] Outstanding exercises for introductory track

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#1810]
There are some outstanding areas in putting together a basic set of 40 or so introductory exercises.  Assuming others are on board with the idea of having an viable introductory set of exercises we should start thinking about them now.

Firstly, basic exercises whose issues have been assigned and have not been active for a while:

- Interfaces - PR #1472 
- Signed Integers- Issue #780
- Exceptions - PR #1655
- Lists - Issue #958

Both PRs are considerably advanced.  Issue 780 was closed and re-opened.

Secondly, there are a bunch of concepts that might be dealt with better as refactoring exercises and we need a decision on refactoring:

- const/readonly - #1044
- ternary conditionals - #1635
- expression bodied members - #1145
- nested types - #1643 
- operator overloading - #1712 

Thirdly, possibly the biggest challenge to date:

- namespaces - #1127 

Any thoughts would be welcome.

**Comment by ErikSchierboom** [comment]
The `exceptions` PR has seen activity over the last days, so that will be added relatively soon. The `lists` one can be forked from F# I think.

> Secondly, there are a bunch of concepts that might be dealt with better as refactoring exercises and we need a decision on refactoring:

I'll get in contact with Jeremy on this.

> Thirdly, possibly the biggest challenge to date:
>
> - namespaces

The main problem with namespaces is coming up with something interesting I feel. We can have students create classes in multiple namespaces, but I feel that we probably need to combine this with another concept to make it interesting enough. Maybe something with "using" statements? E.g. by having students use built-in functionality from a certain namespace?

**Comment by mikedamay** [comment]
> by having students use built-in functionality from a certain namespace

Students are doing that quite a lot - with collections etc.

I thought about combining namespaces with nested types.  But, I think it just doubles the problem.

I thought about having classes with the same name that do something... but what and why?

The only thing I have used them for when mentoring is to suggest that mentees stick their extra tests in a namespace on the main submitted file.

I'm not that keen on code that doesn't compile but I can't see how to avoid that so I'm disheartened from the start.

**Comment by ErikSchierboom** [comment]
> Students are doing that quite a lot - with collections etc.

But don't we already include those namespaces in the stub to have it compile? If so, the student won't have added them by themselves.

> I thought about combining namespaces with nested types. But, I think it just doubles the problem.

Yeah, I'm not a fan of this combination. It will probably be quite confusing to the student.

> I thought about having classes with the same name that do something... but what and why?

Ehm, tough one. I could imagine having a legacy and non-legacy version of a class, but I can't imagine an exercise for that.

> I'm not that keen on code that doesn't compile but I can't see how to avoid that so I'm disheartened from the start.

Me neither. I don't think we can get away with having compilable code here.

**Comment by mikedamay** [comment]
> But don't we already include those namespaces in the stub to have it compile? 

Not when the collection is an Implementation detail such as in the equality exercise.  I hope we can avoid making custom namespaces a prerequisite for that and any others that don't expose the collection.  I sort of thought/hoped `using` might have been covered in basics.

**Comment by ErikSchierboom** [comment]
It wasn't, as that `introduction.md` is already quite a bit one.

**Comment by ErikSchierboom** [comment]
> Secondly, there are a bunch of concepts that might be dealt with better as refactoring exercises and we need a decision on refactoring:

I've had a chat with Jeremy, and we both agree that concept exercises can be refactoring exercises. There are two things we need to be careful about with refactoring exercises:

1. Complexity. We shouldn't have these major files that require refactoring, which is one of the issues with the existing v2 refactoring exercises.
1. Make the exercises interesting enough. Usually refactorings are relatively simple, so we should make sure that the exercises are still engaging and fun to work on.
