### ISSUE TITLE
[C#] structs - ensure exercise compiles when first downloaded.

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#1846]
Currently we ask the student to implement the `Plot` struct in this exercise.  Because of this the code provided by the CLI (Structs.cs, Structs.csproj, StructsTests.cs) will not compile.

Please replace calls to `new Plot(...)` with a `CreatePlot()` method and use reflection to call the constructor if an appropriate one is present otherwise throw an `InvalidOperationException`.

This should enable the code to build "out of the box".

**Comment by aes421** [comment]
@mikedamay I would like to try my hand at this for Hacktoberfest.  Just to be clear - we are talking about adding the CreatePlot method in this file correct? https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/structs/StructsTests.cs

**Comment by mikedamay** [comment]
> we are talking about adding the CreatePlot method in this file correct?

Yes.  I'll be around on Saturday if you want to discuss.

It's great that you are getting involved.

**Comment by aes421** [comment]
@mikedamay Thank you.  I made a PR and it's ready for your review.  Could you add the label hacktoberfest-accepted if it meets your standards?  Thank you
