### ISSUE TITLE
[Python] Improve Concept Exercise: strings (specify function to implement)

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1849]
The tasks in the `strings` exercise's [instructions](https://github.com/exercism/v3/blob/master/languages/python/exercises/concept/strings/.docs/instructions.md#1-extract-a-message-from-a-log-line) all mention something like:

> Implement a function to return a log line's message:

These should be made more specific, like:

> Implement the `extract_message` function to return the log line's message:

**Comment by InfiniteVerma** [comment]
I'd like to work on this.

**Comment by ErikSchierboom** [comment]
@InfiniteVerma I've assigned you to the issue!
