### ISSUE TITLE
[Ruby] Implement new Concept Exercise: booleans

### ISSUE THREAD

**Issue by biancapower** [exercism/v3#1904]
This issue describes how to implement the `booleans` concept exercise for the Ruby track.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before diving into the implementation, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

Please also watch the following video:

- [The Anatomy of a Concept Exercise](https://www.youtube.com/watch?v=gkbBqd7hPrA).

## Goal

The goal of this exercise is to teach the student the Concept of Booleans in Ruby.

## Learning objectives

- Know how to use ternary expressions - using the `?:` operator.

## Out of scope

N/A

## Concepts

- Booleans
  - know the two Boolean values
  - know the "boolean" nature of Ruby methods
- Conditional statements
  - know the difference in precedence between `and` and `&&`, `or` and `||`
- know about operators that are used with conditional statements
- know how to build logical expressions with boolean operators

## Prerequisites

- `basics`

### Hints

- [Booleans Ruby](https://learn.co/lessons/booleans-ruby-readme)

### After

- [Why Ruby doesn't have a Boolean Class](https://www.rubytapas.com/2019/01/08/boolean/)
- [Understanding Boolean Values in Ruby](https://www.rubyguides.com/2019/02/ruby-booleans/)

## Representer

This exercise does not require any specific representation logic to be added to the [representer](https://github.com/exercism/ruby-representer).

## Analyzer

This exercise does not require any specific analyzer logic to be added to the [analyzer](https://github.com/exercism/ruby-analyzer).

## Implementing

To implement this exercise, please [follow these instructions](https://github.com/exercism/v3/blob/master/languages/ruby/reference/implementing-a-concept-exercise.md).

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by biancapower** [comment]
Assigned myself to implement this.

**Comment by dvik1950** [comment]
I opened a similar Issue a while ago but haven't been able to complete it: #1624  . I haven't done much work regarding the exercise so no double effort has been made but I think it makes sense to look at the existing issues to see if a similar one already exists. I also see that @neenjaw has implemented this and made a pull request yesterday #2025. I might be completely wrong here because I'm a bit out of the loop but I think this should be sorted out so no double effort is made :)

**Comment by neenjaw** [comment]
Ya it's been a bit of a ride to go through several nil exercises to what there is now in #2023 followed by #2025. I've been meaning to tag this issue with those events.

**Comment by neenjaw** [comment]
Also the already committed `numbers` exercise touches on booleans a little, so there is need for some reconfiguration of the track. as [iHiD pointed out](https://github.com/exercism/v3/pull/2025#pullrequestreview-451011486)

**Comment by neenjaw** [comment]
Is this complete then? Should be closed?
