### ISSUE TITLE
[v3]  Wanted to join but see some problems 

### ISSUE THREAD

**Issue by ghost** [exercism/v3#1909]
Hello, 

I m be asked by the Pharo language team to investigate if and how Pharo can be a part of the new version. The biggest problem is that Pharo langauge is a image based language where the ide is a part of the language. So I think we need to discuss if and how to make this work with browser coding and if there is a way this can work 

@iHiD

**Comment by iHiD** [comment]
In-browser coding isn't a compulsory requirement, and for Phara, from what I understand, it's an unachievable goal. So we'll have to do without. 

So the main priority would starting to be building out Concept Exercises.

**Comment by RoelofWobben** [comment]
maybe I can work 

As far as I understand it , submit, fetch an exercise and fetch the md file are "just"  api calls.  I or the other maintainer could make code to make that call. And I know that a image can be booted from prompt in linux. So maybe it can work if the code and the test are done with the Pharo IDE but the rest could be done with api calls

**Comment by RoelofWobben** [comment]
@ErikSchierboom

**Comment by ErikSchierboom** [comment]
I don't know. This is really a hard problem. 

> So the main priority would starting to be building out Concept Exercises.

I would also like to emphasize that building Concept Exercises is probably more important than getting the in-browser coding working, especially with Pharo's unique IDE.

**Comment by RoelofWobben** [comment]
Oke, then can I work in the same repo as v2 or maybe clone the v3  repo to my own and work from that 
@ErikSchierboom

**Comment by ErikSchierboom** [comment]
Yeah that could definitely work. Whichever you prefer.

**Comment by RoelofWobben** [comment]
oke, then I think I will make a seperate solution so I can test things alone. 
Is there then a repo where a sort of mock up is for a exercise or a v3 repo which I can use

**Comment by ErikSchierboom** [comment]
> Is there then a repo where a sort of mock up is for a exercise or a v3 repo which I can use

You mean a version of the v3 website?

**Comment by RoelofWobben** [comment]
no, I mean a repo where the new structure of a exercise is shown so I can use it.

**Comment by ErikSchierboom** [comment]
Right. You can find a general description of what the structure looks like here: https://github.com/exercism/v3/blob/master/docs/maintainers/generic-how-to-implement-a-concept-exercise.md

Individual tracks will add language-specific files (stub, example, tests, possibly more) to their exercises too, but that is dependent on the language. For an example of a fully-implemented exercise, see https://github.com/exercism/v3/tree/master/languages/csharp/exercises/concept/strings

**Comment by RoelofWobben** [comment]
Thanks, it will take more time then I thought. As far as I see it now we have to rewrite a lot of code to make it the output the v3 wants.

**Comment by ErikSchierboom** [comment]
Good luck with it!

**Comment by RoelofWobben** [comment]
Thanks, Luckily my co-maintainer is some-one who knows more about smalltalk so I think we can solve it together. 
Not a lot of fun when you must work with code some-one else wrote which is not active working on it. But we get there im sure of it..

**Comment by iHiD** [comment]
> As far as I see it now we have to rewrite a lot of code to make it the output the v3 wants.

@RoelofWobben Could you explain this a little more pls? When you say "output" what exactly do you mean?

**Comment by RoelofWobben** [comment]
with output I mean the structure 
So I folder named .meta with the right output
a folder named .docs with the right output 
and then a mockup and a test file in the root

**Comment by iHiD** [comment]
Ah, you mean the moving around of things in [this file](https://github.com/exercism/pharo-smalltalk/blob/master/dev/src/ExercismDev/ExercismGenerator.class.st#L63-L68)?

**Comment by RoelofWobben** [comment]
Could be, or around this file : https://github.com/exercism/pharo-smalltalk/blob/master/dev/src/ExercismDev/ExercismGenerator.class.st#L99-L136
