### ISSUE TITLE
[Go] Implement new Concept Exercise: constants

### ISSUE THREAD

**Issue by oanaOM** [exercism/v3#1919]
This issue describes how to implement the `constants` concept exercise for the Go track.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before diving into the implementation, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

Please also watch the following video:

- [The Anatomy of a Concept Exercise](https://www.youtube.com/watch?v=gkbBqd7hPrA).

## Goal

The goal of this exercise is to teach the student the basics of the Concept of Constants in Go.

## Learning objectives

- Understand the purpose of `const`.
- Know when to define `const` values.
- Know how to define `const` values.
- Know how many types of `const` exists.

## Concepts

- `const`
- `iota`

## Prerequisites

- `basics`
- `comments`

## Resources to refer to

- [Constants in Go](https://blog.golang.org/constants)
- [Untyped Constants](https://yourbasic.org/golang/untyped-constants/)

## Representer

This exercise does not require any specific representation logic to be added to the representer.

## Analyzer

This exercise does not require any specific analyzer logic to be added to the [analyzer](https://github.com/exercism/go-analyzer).

## Implementing

To implement this exercise, please follow these [instructions](https://github.com/exercism/v3/blob/master/languages/go/reference/implementing-a-concept-exercise.md).

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by jamessouth** [comment]
would this one include `iota`?

**Comment by oanaOM** [comment]
I would say yes. @tehsphinx what do you think?

**Comment by tehsphinx** [comment]
Yes, I agree. That is a good idea!

**Comment by tehsphinx** [comment]
Note that this is also about the restrictions of constants. e.g a `map` cannot be a `const` as it is a mutable type and Go does not really have a concept of immutability.

@jamessouth: do you want to take a shot at this?

**Comment by jamessouth** [comment]
I can take this one if available.

**Comment by tehsphinx** [comment]
@jamessouth: go head :)

**Comment by oanaOM** [comment]
Since the merge has been done, I'll close this issue now.
