### ISSUE TITLE
[CI] Don't check max-file-size for auto-generated JSON files

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1976]
The CI bot creates three auto-generated JSON files:

- `languages/languages.json`
- `references/references.json`
- `references/stories/stories.json`

The first of these files currently exceeds the max-file-size limit we imposed: https://github.com/exercism/v3/pull/1975/checks?check_run_id=868333040 We should exclude these three files from the check.

**Comment by SaschaMann** [comment]
Since they're only used for storage, it may also be a good idea to push them via lfs or to a separate repo (where they're automerged and nobody has access) in case they're expected to grow too large eventually. (cc @iHiD)
