### ISSUE TITLE
[Java] Implement new Concept Exercise: inheritance

### ISSUE THREAD

**Issue by mirkoperillo** [exercism/v3#1997]
This issue describes how to implement the `inheritance` concept exercise for the Java track.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before diving into the implementation, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

Please also watch the following video:

- [The Anatomy of a Concept Exercise](https://www.youtube.com/watch?v=gkbBqd7hPrA).

## Goal

The goal of this exercise is to teach the student the Concept of Inheritance in Java.

## Learning objectives

- Know what inheritance is.
- Know how to inherit from a class.
- Know that all types inherit from object.

## Out of scope

N/A

## Concepts

- `inheritance`
- `objects`

## Prerequisites

- `classes`

Any data types used in this exercise (e.g. `strings`) should also be added as prerequisites.

### Hints

- [Java inheritance](https://docs.oracle.com/javase/tutorial/java/IandI/subclasses.html)

### After

Nothing to report

## Representer

This exercise does not require any specific representation logic to be added to the [representer](https://github.com/exercism/java-representer).

## Analyzer

This exercise does not require any specific analyzer logic to be added to the [analyzer](https://github.com/exercism/java-analyzer).

## Implementing

To implement this exercise, please [follow these instructions](https://github.com/exercism/v3/blob/master/languages/java/reference/implementing-a-concept-exercise.md).

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by himanshugoyal1065** [comment]
Hi @mirkoperillo,

I'll like to take up this exercise. :)

**Comment by mirkoperillo** [comment]
> The above link in your description is giving 404!
Sorry a typo, now it has been fixed.

@himanshugoyal1065 thank you, I assign it to you.

Feel free to ask for every doubt

**Comment by himanshugoyal1065** [comment]
Hi @mirkoperillo,

I was wondering if I can follow the same exercise as it is done by C#. (link: https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/inheritance/.docs/instructions.md)

I think it will be good to have this consistency.

What are your thoughts?
TIA

**Comment by mirkoperillo** [comment]
Yes @himanshugoyal1065 absolutely

**Comment by himanshugoyal1065** [comment]
Hi @mirkoperillo,

How to run Prettier on the instructions pages? I wasn't able to find much about it. Can you please point me to some page where it is described?

Also, as @iHiD has added hacktober tag, can we have that for this issue as well?

TIA.

**Comment by ynfle** [comment]
To run prettier from the command line/terminal, there are 2 scripts in the `bin` folder of the repo, `format.cmd` & `format.sh` for windows and posix respectively. From the root of the repo run `bin/format.cmd` or `bin\format.cmd` depending on you OS.

It can also be run from the PR directly by commenting with the text "/format".

**Comment by iHiD** [comment]
@himanshugoyal1065 You don't actually need the hacktober tag for it to count against your hacktober count 🙂

**Comment by himanshugoyal1065** [comment]
@iHiD, now you know that I'm participating for the first time :D
