### ISSUE TITLE
[C#] documentation

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#2006]
I thought we should consider cleaning up the concepts and their relationships.

I don't know what freedom of action we have or what technology is required so these ideas are a little unfocused.

Some issues to address:

- Concept descriptions are replicated. They occur in 3 places: _design.md_ under _Concept_, _design.md_ as _Learning Objectives_ and _csharp/references/README.md_.
- It is not clear what is the one-true-source for concept descriptions.
- It is not clear what is the concept's canonical name.
- It is difficult to trace concepts through the system to ensure we have comprehensive coverage.
- The _csharp/references/README.md_ document is fiddly to deal with.

I have not included a discussion of the _csharp/config.json_ document although there is overlap and consistency will be required.

[This](https://www.dropbox.com/s/3aeft08yiqhdvbe/Screenshot%202020-07-16%2000.51.57.png?dl=0) is the object model as I see it.

- Multiple concepts relate to a single exercise.
- Description of the concept is effectively a list of the learning objectives.
- Concepts are tied back to the original concepts document, _csharp/reference/README.md.

One approach would be to turn the above object model into a json document scraping the appropriate sections of the _design.md_ documents and adding in the links to issues and design documents and back references to the original concept document, _csharp/reference/README.md.  This could then be used to generate a replacement for the concept document, _csharp/reference/README.md_.

Or some variation of the above.

Or nothing.

Comments welcome.

**Comment by ErikSchierboom** [comment]
I think the object model as specified is correct. The current setup does indeed have issues, so some sort of automation could really be useful.

**Comment by ErikSchierboom** [comment]
Scraping does have some inherent disadvantages, but it could also help us point to mistakes.

**Comment by mikedamay** [comment]
My proposed replacement format for _csharp/reference/README.md_ is [here](https://github.com/mikedamay/v3/blob/csharp/interfaces/languages/csharp/reference/README.md).  Please have a look and let me know what you think.

cc: @ErikSchierboom

**Comment by ErikSchierboom** [comment]
I really like it! It is really helpful and informative. Some minor suggestions:

- Maybe list the Learning Objectives as a list?
- Maybe link to the exercise in which the Concept was implemented?

**Comment by mikedamay** [comment]
closed by #2162
