### ISSUE TITLE
[Go] Use consistent formatting for output in examples

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#2010]
Looking at the existing Go exercises, there is some inconsistency regarding the format used to show the result of calling a function in examples found in `instructions.md` files. I've found the following variants:

- `// Output: X`
- `// => X`
- `// Returns: X`

It would be good to standardize on one format. I have no preference, while noting that there are a couple of tracks that use `=>`. But it should use what makes sense most for Go.

**Comment by oanaOM** [comment]
I can look into this and make it consistent across all exercises.

**Comment by oanaOM** [comment]
I made the changes and it should be consistent across all exercises.

**Comment by ErikSchierboom** [comment]
Great!
