### ISSUE TITLE
[Swift] Improve Concept Exercise: arrays

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#2014]
- The example implementation uses an `if`, but its only prerequisite is the `basics` concept. I think the `conditionals` concept should also be added as a prerequisite.
- Typo in `after.md` and `introduction.md`: "thee" should be "the".
- The `after.md` file uses the `guard` in its example, but this syntax is not introduced in any of the prerequisite exercises. It looks like the `conditionals` concept explains this (I have some comments on that exercise later).

**Comment by wneumann** [comment]
> The example implementation uses an if, but its only prerequisite is the basics concept.

Yes. I believe the best option is to move `conditionals` up in front of `arrays`. That addresses both this if and the guard.

PR created to address these comments (https://github.com/exercism/v3/pull/2021).

**Comment by ErikSchierboom** [comment]
Excellent. I've left two small comments on the PR.

**Comment by wneumann** [comment]
Closed with merging of PR https://github.com/exercism/v3/pull/2021.
