### ISSUE TITLE
[Swift] Improve Concept Exercise: dictionaries

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#2016]
- There is no `config.json` entry for the exercise
- The stub file use `inout` parameters. Will this be covered in the `functions` prerequisite the `design.md` document mentions?
- The exercise uses default values. Will this be covered in the `functions` prerequisite the `design.md` document mentions?
- The exercise uses arrays, so the `arrays` concept should be a prerequisite (not mentioned in the `design.md` file)
- The exercise uses tuples, so the `tuples` concept should be a prerequisite (not mentioned in the `design.md` file)
- The exercise uses strings, so the `strings` concept should be a prerequisite (not mentioned in the `design.md` file)
- The exercise uses optional types in the introduction, so the `optionals` concept should be a prerequisite (not mentioned in the `design.md` file)
- Currently, the examples in the instructions don't have a way to display the contents of the dictionary. Instead, it does something like "// Adds "Dave Thomas" to the dictionary with a high score of 0." It might be worth coming up with some format to use, maybe something like "{ "Dave Thomas": 0 }" or something similar.
- The examples in the `introduction.md` are quite exhaustive. To make things more concise, maybe you could omit some of the examples.
- The `?.` operator is used in the introduction, which is not introduced in one of the prerequisites I think.
- The part about sorting dictionaries in the `introduction.md` can probably be removed from the `introduction`, as sorting is like another method and it does not introduce any new syntax. It fits the `after.md` better I feel.

**Comment by wneumann** [comment]
> Currently, the examples in the instructions don't have a way to display the contents of the dictionary. Instead, it does something like "// Adds "Dave Thomas" to the dictionary with a high score of 0." It might be worth coming up with some format to use, maybe something like "{ "Dave Thomas": 0 }" or something similar.

With this I've been wanting to draw a distinction between operations that return a non-void value versus operations that return void and are executed for their side effects as I don't want to confuse the students into thinking some other value is returned.  Using a notation like you listed might work, I just want there to be a clear, if not obvious difference between the two cases.

Also, regarding situations like these:
> The exercise uses arrays, so the arrays concept should be a prerequisite (not mentioned in the design.md file)

Should we be including prerequisites of prerequisites in the design.md document, or just the topologically nearest requirement? For example, `tuples` and `arrays` are prerequisites of `functions` and `functions` is a prerequisite of `dictionaries`. So should `dictionaries`' design.md contain all three, or just `functions`?

**Comment by ErikSchierboom** [comment]
> Should we be including prerequisites of prerequisites in the design.md document, or just the topologically nearest requirement? For example, tuples and arrays are prerequisites of functions and functions is a prerequisite of dictionaries. So should dictionaries' design.md contain all three, or just functions?

Excellent question. There are two schools of though here, either being very complete or using transitive prerequisites. I'm okay with whatever you prefer.

**Comment by wneumann** [comment]
This was closed with PR https://github.com/exercism/v3/pull/1961.
