### ISSUE TITLE
[Swift] Improve Concept Exercise: numbers

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#2017]
- The stub file requires the student to define the functions themselves. However, only the `basics` exercise should have the student define the functions from scratch. The other exercises should create stubs for the functions such that the student only has to worry about implementing the functions. The reason the `basics` exercise did not use stubs is that one of the goals of the `basics` exercise is too teach the student how to define a function. Having stubs with predefined functions goes against that, as learning is best done by doing :) That said, for all the other exercises, there should be a stub function. Note that for exercises that introduced new syntax (e.g. introducing the syntax to declare a class), you _would_ usually have a TODO and requiring the student to define something from scratch. All in all, the numbers exercise's stub should contain stubs for the functions.
- The `design.md` file mentions as one of its goals: "Know how to convert from one numeric type to another" The example implementation does not seem to do this. Instead, it just uses `Double` values everywhere. I expect some of the parameters should actually be `Int` values. The stub file should also contain `Int` parameters then.
- The `introduction.md` file contains example code for the type conversion functionality. In general, the `introduction.md` file should only use code examples when new syntax is introduced (see [the docs](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md#docsintroductionmd)). It looks like there is no new syntax introduced, as the conversions look like regular function calls (albeit with special names matching the type). As there is no syntax introduced, the code example should be removed. The text can then become something like that type conversions are functions named after the type they are converting to.
- You've opted to also mention the other floating-point type (`Float`) and that there are more signed and unsigned integer types. Out of curiosity: do you plan on having separate exercises for those new numeric types? For example, I could imagine an exercise that goes into detail about those different integer types and how they relate to each other.

Awesome work! I really, really like the `after.md` document too!

**Comment by wneumann** [comment]
> It looks like there is no new syntax introduced, as the conversions look like regular function calls (albeit with special names matching the type).

I guess this depends on how hair-splitty you want to get about what constitutes new syntax. `Int(3.14)` is sugar for `Int.init(3.14)` which is an initializer for an instance of an `Int` struct. So it's not really a function call, it's a sugared method call (and a special method call at that). Of course methods (in Swift) are essentially just functions that live inside a structure, so… And of course, none of this will get explained to the student for another 5-10 exercises.

I'm OK with pulling the code examples, but I'm just wondering roughly where the line is so I can be more careful in later exercises. For example, should the subscript access to dictionaries not have code examples because they are essentially the same syntax as subscript access to arrays? 

I assume that once you see enough of them it's a bit of a "you know it when you see it deal".

**Comment by wneumann** [comment]
Added PR https://github.com/exercism/v3/pull/2024 to address these comments.

**Comment by ErikSchierboom** [comment]
> I guess this depends on how hair-splitty you want to get about what constitutes new syntax. Int(3.14) is sugar for Int.init(3.14) which is an initializer for an instance of an Int struct. So it's not really a function call, it's a sugared method call (and a special method call at that). Of course methods (in Swift) are essentially just functions that live inside a structure, so… And of course, none of this will get explained to the student for another 5-10 exercises.

Yeah, this is a bit of a finicky point. That said, your argument that "Int(3.14) is sugar for Int.init(3.14)" does strike me as a valid one, so in this case you _could_ argue that it is new syntax, so I now vote to leave it in.

> I'm OK with pulling the code examples, but I'm just wondering roughly where the line is so I can be more careful in later exercises. For example, should the subscript access to dictionaries not have code examples because they are essentially the same syntax as subscript access to arrays?

The subscript access example is a great one. I'd argue that while the syntax here is the same, it is a different syntactical construct, although I'm hard pressed to see the explain why I think this. So in that particular case, I'd argue that you should include a code example for subscript access to dictionaries.

> I assume that once you see enough of them it's a bit of a "you know it when you see it deal".

Yeah I guess so. We'll probably not get this right everywhere and it's not a deal-breaker if we don't :)

**Comment by wneumann** [comment]
This was closed with PR 2024.
