### ISSUE TITLE
[Swift] Improve Concept Exercise: optionals

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#2018]
- The exercise uses strings, but `strings` is not listed as a prerequisite for the exercise.
- The example implementation uses tuples (I think) which is not listed as a prerequisite for the exercise.
- The `hints.md` file should use non-numeric lists (`-`) instead of numeric ones.
- The "Read about" text in the `hints.md` file in the "## General" section is missing the leading `-`
- Typos in the `hints.md` file: "whetheer" should be "whether", "thee" should be "the", "comparee" should be "comparee"
- Some of the hints give away the solution (e.g. `` You can use `if let` ``). As per [the docs](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md#docshintsmd): "The hints should not spell out the solution, but instead point to a resource describing the solution" The existing `numbers` exercise's hints are a great example on how to do this.
- The hints file refers to the `introduction.md` file of the `conditionals` exercise, but unfortunately this doesn't work, as the website or CLI won't have any notion of exercises being relative to each other and the link won't work.
- The instructions file is missing code examples.
- The tasks involve a bit of math. In general, we try to steer clear of using any math. You might get away with this by including the formulas used to calculate the various things that are required for the exercise. That way, students won't have to remember/google the math that is involved.
- The "An example of where optionals arise in Swift is..." part in the `introduction.md` could probably just be in the `after.md` document to trim the `introduction.md` down in size.
- The "## Using optionals" section looks like it contains some bits which are not strictly necessary to solve the exercise (judging by the example implementation). One example is the `!` operator, as I feel that the student shouldn't be using that to solve the exercise (correct me if I'm wrong though). If so, this should be removed from the `introduction.md` document and moved to the `after.md` document.
- Typo in `after.md`: "optionas" should be "options"

**Comment by wneumann** [comment]
> The exercise uses strings, but strings is not listed as a prerequisite for the exercise.

It uses strings only in that they are converted to optional numbers, which is covered in `optionals`. And optionals is included in the prerequisites. Hopefully that is enough, as currently `strings` has `optionals` as a prerequisite.

> The "An example of where optionals arise in Swift is..." part in the introduction.md could probably just be in the after.md document to trim the introduction.md down in size.

While I did cut out some of the other text, this portion and the newly added text re: comparing optionals are needed for the exercise as written, as the student will need to create a `Double?` from a String (and to compare two optional values).

**Comment by wneumann** [comment]
Added PR https://github.com/exercism/v3/pull/2050 to address these comments.

**Comment by ErikSchierboom** [comment]
> It uses strings only in that they are converted to optional numbers, which is covered in optionals. And optionals is included in the prerequisites. Hopefully that is enough, as currently strings has optionals as a prerequisite.

Hmmm, this is slightly problematic. @iHiD what do you think?

> While I did cut out some of the other text, this portion and the newly added text re: comparing optionals are needed for the exercise as written, as the student will need to create a Double? from a String (and to compare two optional values).

The latest version looks good to me!

**Comment by iHiD** [comment]
Any reason not to add strings as a prereq?

**Comment by iHiD** [comment]
Oh. I see.

**Comment by iHiD** [comment]
I think you're going to need to add something to the top of https://github.com/exercism/v3/blob/master/languages/swift/exercises/concept/optionals/.docs/introduction.md which explains in general terms what a String is. Something simple like "Strings in Swift are a series of characters". I think that'll be enough.

**Comment by wneumann** [comment]
As I noted in https://github.com/exercism/v3/pull/2022, I think the best option may be to create a more basic `strings-and-characters` concept exercise which would be a prerequisite of both this and `conditionals` and redo the current `strings` exercise as a follow-on concept that goes deeper into strings.

**Comment by ErikSchierboom** [comment]
> As I noted in #2022, I think the best option may be to create a more basic strings-and-characters concept exercise which would be a prerequisite of both this and conditionals and redo the current strings exercise as a follow-on concept that goes deeper into strings.

That sounds like a good plan! Maybe create GH issues to have this documented?

**Comment by wneumann** [comment]
This PR has been merged and the discussed changes to `strings` have been submitted as PRs, so I am closing this issue.
