### ISSUE TITLE
[Swift] Improve Concept Exercise: strings

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#2019]
- The `introduction.md` contains quite a bit of information. Some of it is not needed for the student to solve the exercise, and as such should be removed from the `introduction.md` document (see [the docs](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md#docsintroductionmd)). The `after.md` document can be used for any information that is good to know, but not needed to solve the exercise. Examples of things that the student does not need to know are the type conversion bits and as the example uses string interpolation, the `String.format` syntax is also not necessary to introduce.
- The "### Breaking strings apart" section in the `introduction.md` file seems more suited as a hint than something needing to be included in the `introduction.md` file.
- Typo in `introduction.md` and `after.md`: "indicies" should be "indices"
- I was slightly confused by the commented text in the introduction. This text will not be seen by anyone except people browsing the source. For whom is the commented text intended to be read?
- The "Some examples are "Hello, World!", "Weißwurst is a tasty sausage.", and "This is my family: 👨‍👩‍👦‍👦, this is our dog: 🐶" text could be removed I feel, as you also have the exact same examples in the same code.
- The stub file refers to the `Character` type, but I think this type is not yet introduced. I don't know if `Character` has enough going for it to warrant a separate (prerequisite) exercise, but otherwise you would have to introduce it in the `introduction.md` somewhere.
- The introduction mentions that the `first` and `last` methods can be used to access the first and last characters. However, looking at the example implementation, these methods actually return a nullable character (or whatever the correct name is in Swift). This basically introduces a new concept on the student, `nil`, which I feel warrants a completely separate exercise. Remember that the example implementation should [only use language features introduced by the exercise or its prerequisites](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md#example-implementation-file) (and their prerequisites, and so on). As such, I would remove the mentions of the `first` and `last` methods from the introduction and the example implementation. An alternative would be to remove/modify the method to not work with single characters or something like that. This is an example of how one part of an exercise can work in one language (JavaScript in this case), but less so in another language (Swift).
  An alternative would be to depend on the `optionals` exercise, which I believe introduces how to deal with optional values. However, it looks like the `optionals` exercise itself (should) depend on the `strings` concept, which of course is not possible due to circular references.

**Comment by wneumann** [comment]
The `strings` exercise has been refactored into a basic `strings-and-characters` exercise and a follow-on `string-components` exercise which addresses these issues and fixes the prerequisite cycles that existed previously.
