### ISSUE TITLE
[Swift] General improvement suggestions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#2020]
- All the exercises have a `README.md` file in their directory. I was wondering what the goal of these files are? Their contents seem to suggest a description of the exercise/package, but for that we already have the `.meta/design.md` file. Having a `README.md` file in the root of the directory will also conflict with the CLI-based approach, where the documents from the `.docs` folder will be merged into a `README.md` file that will be downloaded at the root.
- We've recently opted to remove any non-relevant text from `.meta/design.md` file. In particular this meant:
  - Removing the "The Concepts this exercise unlocks are:" text from "## Concepts" section
  - Removing the "This exercise's prerequisites Concepts are:" text from the "## Prerequisites" section
  - Removing the "## Representer" section if there are no custom representer rules specified
  - Removing the "## Analyzer" section if there are no custom analyzer rules specified
    Some of the exercises already do this, some of them don't. This is of course no big deal, but just wanted to let you know.
- I've seen two formats used to signify output of code: `// =>` and `# =>` I don't know which is the correct one, but it is probably best to standardize on one format.
- The `introduction.md` documents are in general fairly big. As per [the docs](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md#docsintroductionmd), they should be as short as possible:
  > "Only information that is needed to understand the fundamentals of the concept and solve the exercise should be provided. Extra information should be left for the after.md."
- The `after.md` documents are also quite big. This is not necessarily an issue as they can be more verbose than the `introduction.md` document, but in some cases it might be better to create a separate exercise to introduce a certain concept instead of only explaining it in the `after.md` document.
- In some of the stub files, the error message is slightly different from what other tracks have been using. E.g. instead of "splitOnNewlines not implemented -- replace this error with an implementation" could you do "Please implement the splitOnNewlines() function"?
- In the instructions, there are mentions of "Write a function X" and "define X", but in fact there is usually a stub available. In these cases, other tracks phrase this as "Implement function X".
- Typo in `instructions.md`: "thee" should be "the"

Related issues:

- #2014 Improve `arrays` exercise
- #2015 Improve `conditionals` exercise 
- #2016 Improve `dictionaries` exercise
- #2017 Improve `numbers` exercise
- #2018 Improve `optionals` exercise
- #2019 Improve `strings` exercise

**Comment by wneumann** [comment]
> All the exercises have a README.md file in their directory. I was wondering what the goal of these files are? 

These files are created by the Swift Package Manager when you set up a new project. I believe they are inspired by the standard README.md files found on GitHub and are supposed to be used as is usually seen on GitHub. In the V2 Swift track, they contain the instructions for each exercise ([for example](https://github.com/exercism/swift/tree/master/exercises/beer-song)), so I copied that practice over into V3.

If we don't want that, what is the best option? Leave the default README that the package manager creates? Leave it but  keep it as an empty file? Or just delete the README that is created?

**Comment by wneumann** [comment]
> The after.md documents are also quite big. 

Regarding this, I've seen and tried out the "key takeaways" after.md format that I had seen in some elixir exercises ([for example](https://github.com/exercism/v3/blob/master/languages/elixir/exercises/concept/maps/.docs/after.md)). Here's [one example](https://github.com/exercism/v3/blob/master/languages/swift/exercises/concept/dictionaries/.docs/after.md) I've tried with Swift.

It's more compact, though I'm not crazy about the look and feel. Any thoughts on the better direction to go?

**Comment by ErikSchierboom** [comment]
> In the V2 Swift track, they contain the instructions for each exercise (for example), so I copied that practice over into V3.

Yes, I assumed this was the reason. For v3 the README will be automatically generated based on the contents of the files in the `.docs` directory.

> If we don't want that, what is the best option? Leave the default README that the package manager creates? Leave it but keep it as an empty file? Or just delete the README that is created?

The last option, deleting the README, is the correct one.

**Comment by ErikSchierboom** [comment]
> It's more compact, though I'm not crazy about the look and feel. Any thoughts on the better direction to go?

To be honest, I'm also not crazy about the look and feel (tracks currently have some freedom in how to structure this file). I liked your existing `after.md` better actually. In some cases, you could try to merge some of the examples, but if you find this does not work, just ignore this comment for now.

**Comment by wneumann** [comment]
This was addressed in the four referenced PRs.
