### ISSUE TITLE
[ALL] Improve tree to check which exercises are actually implemented

### ISSUE THREAD

**Issue by tehsphinx** [exercism/v3#2031]
![image](https://user-images.githubusercontent.com/6624571/87859033-98f59300-c932-11ea-8ec1-3b61cf2649cf.png)

In Go we use the tree above to (https://v3.exercism.io/go/maintaining/tree) to build a reasonable tree of exercises. As a work in progress and discussion basis. But most of the grey exercises are not implemented yet.

It would be cool if the tool to generate the tree was able to check the file tree if a folder actually exists with that name. If that doesn't work maybe a "todo" flag in the `config.json` (which the tree is based on) could be used to set an exercise to "not implemented"?

**Comment by TheLostLambda** [comment]
I think I recall at some point discussing that unimplemented exercises could have a `null` UUID? I think that would be a reasonable approach. I do I like the idea of sketching out a tree like this for planning purposes. That's something I've been wanting to do as well.

**Comment by tehsphinx** [comment]
Testing this in #2035

**Comment by ErikSchierboom** [comment]
This now works in the latest release:

![image](https://user-images.githubusercontent.com/135246/88038856-12fe6580-cb47-11ea-933d-a91c8d136a16.png)

**Comment by iHiD** [comment]
Wahoo!

**Comment by tehsphinx** [comment]
Thx a lot, @neenjaw!
