### ISSUE TITLE
[Go] Complete Concept Exercise: structs

### ISSUE THREAD

**Issue by tehsphinx** [exercism/v3#2037]
This issue describes how to complete the `structs` concept exercise for the Go track.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before creating the issue, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

Please also watch the following video:

- [The Anatomy of a Concept Exercise](https://www.youtube.com/watch?v=gkbBqd7hPrA).

## Goal

Add the missing files on the `structs` exercise. Some of which are:
- tests
- introduction
- hints
- after.md
- etc.

Note: See the youtube video above and its description on youtube for details.

A PR just adding one of the missing parts is very welcome! Let us know in this issue which part you are interested in to avoid multiple people doing the same.

## Help

If you have any questions while improving the exercise, please post the questions as comments in this issue.

**Comment by tehsphinx** [comment]
@oanaOM: in case you are interested in picking this up. 😃

**Comment by oanaOM** [comment]
Yes! 😁 

This will be follow-up on https://github.com/exercism/v3/pull/2030
