### ISSUE TITLE
[Ruby] Improve Concept Exercise: `booleans`, `numbers`

### ISSUE THREAD

**Issue by neenjaw** [exercism/v3#2046]
## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before creating the issue, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

Please also watch the following video:

- [The Anatomy of a Concept Exercise](https://www.youtube.com/watch?v=gkbBqd7hPrA).

## Goal

Through the process of creating a concept exercise to teach about `instance-variables`, `nil` (#2023), and `booleans` (#2025).  We encountered that **normal** finding that it is very difficult to teach certain concepts in isolation without implicitly depending on other concepts, and that this process isn't straight-forward to predict.

In other tracks (Elixir, python) this has been the observed trajectory.  So the goal is to tweak the exercises involved in this collision.

## Problem

As observed in #2025:

> **@ihid:** One thing we need to decide is whether this exercises explains conditionals, or the [`numbers` exercise](https://github.com/exercism/v3/blob/master/languages/ruby/exercises/concept/numbers/.docs/introduction.md). [...]
> 
> **@neenjaw:** The numbers one could mostly stay the same as it is, but point to this one as its ancestor. This exercise doesn't really get into conditional branches, and they are one used in the introduction to explain the true/false truthiness concept.
> 
> **@ihid:** [...] Having thought on [@neenjaw's] comment more, I think we should probably remove all the `if/unless` stuff from [the `booleans` exercise] and keep that in [the] `numbers` [exercise], and leave [`booleans`] to explain the booleans and `&&` etc.

## Path to resolution

Most of the `if`/`else` discussion in the `booleans` exercise are in relation to discussing `truthiness` and its effect on control flow / conditional expressions.  So I think something like this would resolve this dependency issue:

1) Make `booleans` a prerequisite of `numbers`
2) Remove the `if`/`else` from the `booleans` intro/after, ensure the content appears in `numbers`
3) Remove `Boolean`-content from `numbers`, ensure the content appears in `booleans`
4) ~~Profit!~~ All done.

Steps 2 and 3 will need new examples drawn up to illustrate the concepts without the use of the other's concept.

Just as I see it, tell me what you think!

## Help

If you have any questions while improving the exercise, please post the questions as comments in this issue.

**Comment by neenjaw** [comment]
pinging: @iHiD (have I summarized this correctly), @biancapower (working on a separate booleans exercise), @pvcarrera (created the numbers exercise), @kotp (contributed with reviews for my PRs on #2023, #2025)

**Comment by neenjaw** [comment]
Also, since this affects #1904, I will mention that here.

**Comment by dvik1950** [comment]
I'll remove the part about conditionals from the `numbers` exercise if no one else started working on that yet.

**Comment by iHiD** [comment]
@dvik1950 Thanks. I think it's just the boolean content that needs to be removed. The stuff that explains `if/else` should stay, as I understand it.

**Comment by dvik1950** [comment]
@iHiD Uh right, sorry about that, I misread the issue. I'll remove the `booleans` part.

**Comment by neenjaw** [comment]
>1. Make booleans a prerequisite of numbers
>2. Remove the if/else from the booleans intro/after, ensure the content appears in numbers
>3. Remove Boolean-content from numbers, ensure the content appears in booleans

I think points 1 and 3 are complete, but I think point two remains incomplete.

**Comment by kayn1** [comment]
@neenjaw Could I create a PR for the 2nd point? 
_Remove the if/else from the booleans intro/after, ensure the content appears in numbers_

**Comment by neenjaw** [comment]
Sure!
