### ISSUE TITLE
[Common Lisp] Sameness Concept Exercise: can we link to exertal resources for the hints?

### ISSUE THREAD

**Issue by verdammelt** [exercism/v3#2067]
We often link to external resources in the hints file, to directly point students towards the right method/function to use (but without spoiling the solution in this file). Is there a document you could link to that contains information on the equality predicate that should be used?

This comment also applies to the other hints in this file.

_Originally posted by @ErikSchierboom in https://github.com/exercism/v3/pull/1823_

[@verdammelt: linking to the Hyperspec would be too specific and give the student the answer - but there is a page linked in the after.md which might be good for this]

**Comment by ErikSchierboom** [comment]
> linking to the Hyperspec would be too specific and give the student the answer

Just as an addendum: it is fine to give the student a link to a page that gives the answer. The idea for hints is that they provide enough information for a student to become unblocked. So they should point to resources that will give the student a clear idea what to do. In this case I can see why just linking to the Hyperspec would be too specific, so if there is another document to use, that is great. If there isn't, feel free to just link to the Hyperspec.
