### ISSUE TITLE
[v3] Update maintainers

### ISSUE THREAD

**Issue by samWson** [exercism/v3#2241]
@RoelofWobben, @macta, @bencoman, you are all listed as maintainers of the pharo-smalltalk track for v2. If you would like to still be [listed as maintainers](https://github.com/exercism/v3/blob/master/languages/pharo-smalltalk/maintainers.md) for v3 and continue contributing please let me know. Let me know if you want to be listed as a senior maintainer or a contributing maintainer.

**Comment by macta** [comment]
Hi Sam - at the moment, life has taken a turn where I need to spend a bit more time with family, so my contributions/time are greatly reduced and it doesn’t feel like I should be listed as a contributor at the moment. 

I will of course try to help where I can, and offer advice - and am pleased to see you keep the momentum going!

Tim

**Comment by RoelofWobben** [comment]
Hello Sam, 

What is the difference between a senior or contributing maintainer ?

**Comment by samWson** [comment]
@macta Thanks for the update and all the work you've done so far.

@RoelofWobben I haven't seen anything to describe the difference. At a guess senior maintainers decide the overall direction of work on the repo or are the most frequent contributors. Contributing maintainers would be less frequent and have less say in the direction of development.
