### ISSUE TITLE
[v3] List concepts for Pharo Smalltalk

### ISSUE THREAD

**Issue by samWson** [exercism/v3#2243]
I'll freely admit I'm not an expert in Pharo or Smatlltalk. I have however spent a lot of my spare time using the language and studying its history and origins.

It's worth looking at the [Ruby track concepts](https://github.com/exercism/v3/tree/master/languages/ruby/exercises/concept) for inspiration as it is the language that is most closely related to Smalltalk in terms of OOP semantics.

Other references include [Pharo books](http://books.pharo.org/), and the [Pharo wiki](https://github.com/pharo-open-documentation/pharo-wiki). We should definitely put a call out in the Pharo discord for review of this list.

Also check the general reference for [concept exercises](https://github.com/exercism/v3/blob/master/docs/maintainers/determining-concepts.md).

Given that Pharo is so well integrated with its IDE I believe concepts should also cover use of the IDE. This can include things like using Spotter to find classes and messages in the class library. This is quite important because the class libraries are not typically documented online like C# or Java for example, but are fully available and easy to explore from within the IDE. So effective use of the IDE is critical to getting the best experience of the language.

[Pharo by Example](http://books.pharo.org/updated-pharo-by-example/pdf/2018-09-29-UpdatedPharoByExample.pdf) will likely be an excellent reference for Pharo specific concepts, especially Chapter 6: The Pharo Object Model.

The output of this issue should be a list of concepts. From that we can short list 20 concepts to make exercises for.

Here is a rough list of possible concepts, some plucked from the [list of concepts](https://github.com/exercism/v3/blob/master/reference/concepts/README.md):
- Using the IDE (debugging, browsing, playground, searching)
- Object and message syntax
- Object Oriented Programming
- Classes
- Encapsulation
- Blocks
- Streams
- Objects
- Inheritance
- Traits
- Polymorphism
- Enumeration
- The Pharo Object Model

**Comment by RoelofWobben** [comment]
maybe start simpler :

numbers 
if then 
classes

**Comment by samWson** [comment]
- Object and message syntax
  - unary messages
  - binary messages
  - keyword messages
  - message precedence
  - keywords
- Pharo Object Model
  - Everything is an object
  - Every object is an instance of a class
  - Every class has a superclass
  - Everything happens by sending messages
  - Method lookup follows the inheritance chain (crossover with polymorphism)
- IDE
  - Browser
  - Spotter
  - Playground
  - Finder
    - Search methods by example
  - Debugger
    - Break points
    - Starting code in the debugger
    - Editing in the debugger
- Traits

**Comment by RoelofWobben** [comment]
oke, I do not know if for everything you have mentioned a concept exercise is or can be made easily 
As f ar as I know you have to build up with  subject. 

Like the rruby track is busy.
1) strings and basics are the begining.
2) instance variables . you learn to use instance variables with no knowlegde you have to have only the 1) exercises.
3) booleans , you learned booleans  but you have to learned instance variables 
4)  numbers you learn numbers and conditionals but you have to learn already booleans

but maybe you think about the big subjects where I already think about the detals. 
Im looking more at the c# track because they have already finisched all the documents. 
https://github.com/exercism/v3/tree/master/languages/csharp/reference

**Comment by samWson** [comment]
@RoelofWobben I'm just putting concepts that I think should be covered in this issue. Pharos object and message syntax is pretty unique among programming languages so it needs to be an early concept.

**Comment by RoelofWobben** [comment]
oke, then I hope we can find challenges for it and a way to build up knowlegde because the user learned more and more concepts

**Comment by ErikSchierboom** [comment]
Great work! Of the concepts that are listed, my only comments would be on the `IDE` category. The goal of the concepts list is to list the concepts that make up the language. The IDE category seems more like it is linked to the platform than the language. It would also be very tough to create exercises for those concepts. I would suggest not including them in the concepts list, but if you feel that it is important to list them somewhere, I would create a separate document to list the non-language concepts (the C# track has [done something similar](https://github.com/exercism/v3/blob/master/languages/csharp/reference/out-of-scope.md).

> oke, then I hope we can find challenges for it and a way to build up knowlegde because the user learned more and more concepts

Yes, this is the challenge when building a track: designing exercises that slowly, but gradually builds up the student's knowledge. But the above list is a great starting point! Much of the track's structuring only starts making sense when one actually starts building the exercises, so I'd recommend not spending _too_ much time on getting this list absolutely right.

**Comment by iHiD** [comment]
@samWson I can't move this as there is a @ghost user, so I'm closing it, but tagging you in case you want to manually copy/paste the stuff over.
