### ISSUE TITLE
[C#] Cyclic Dependency Bug

### ISSUE THREAD

**Issue by neenjaw** [exercism/v3#2282]
Hey there exercism csharper's!

While browsing through the [dashboard](v3.exercism.io) I noticed the maintenance page showing the tree is throwing an error, complaining of a cyclic concept dependency.  See picture:

![Screenshot from 2020-10-02 22-11-08](https://user-images.githubusercontent.com/8953691/94982981-402ea300-04fc-11eb-8b67-13c41cb8c9d5.png)

Seems there is some cycle occurring including the dependency from `exceptions` to `overflow`.

The graph will show as expected when it is resolved.

**Comment by valentin-p** [comment]
Let me know if my PR solves the issue (Note: I did not succeed to run the v3 dashboard on my local machine yet)

**Comment by neenjaw** [comment]
I'm not a maintainer for the csharp track, so I'll ping @ErikSchierboom and @mikedamay to be able to verify. @ErikSchierboom probably won't take a look at it before tuesday. :)

**Comment by ErikSchierboom** [comment]
I'll add my comments to the PR! Thanks for looking into this @valentin-p and for reporting it @neenjaw

**Comment by valentin-p** [comment]
Superseded by #2314

**Comment by ErikSchierboom** [comment]
This has been fixed.

**Comment by valentin-p** [comment]
Reopening. Same issue.
![image](https://user-images.githubusercontent.com/3833193/98467993-bba90180-21d8-11eb-8683-300ac5370ee3.png)
