### ISSUE TITLE
[C#] exceptions exercise improvement

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#2314]
Change the story on the `exceptions` exercise as follows: We could use the NotImplementedException and come up with a story around working with another department's library that is still being implemented. The story could be to get a progress report or something like that, in which the student checks which features are "complete" (as in: implemented).

This follows the discussion on PR #2287.

**Comment by valentin-p** [comment]
Concepts overflow (hyperinflation-hits-hyperia) and exception (calculator-conundrum) are depending on each other in the config file, creating a cyclic dependency. 

![image](https://user-images.githubusercontent.com/3833193/98468075-1b9fa800-21d9-11eb-9388-3ab388462869.png)
