### ISSUE TITLE
[C#] Improve Concept Exercise: enums. Cyclic Dependency Bug

### ISSUE THREAD

**Issue by valentin-p** [exercism/v3#2322]
This issue describes how to improve the `enums` concept exercise for the C# track.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before creating the issue, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

Please also watch the following video:

- [The Anatomy of a Concept Exercise](https://www.youtube.com/watch?v=gkbBqd7hPrA).

## Goal

Remove Cyclic Dependency Bug from C# concept exercises. 
The slug enums depends on switch-statements and the opposite too.

## Help

We could simplify the enums exercise to avoid using a switch statement, because the track has a dedicated switch-statements exercise.
Option 1: Keep current exercise but solve it with if/else
Option 2: Write a simpler enum for example converting ranges of integer to Grades: A/B/C; Priorities: Low, Medium, High; 

## Bug

The dashboard is broken when clicking on the tree view:
https://v3.exercism.io/csharp/maintaining/list
![image](https://user-images.githubusercontent.com/3833193/95976293-93b3c180-0e17-11eb-9080-0c95eee82933.png)

**Comment by mikedamay** [comment]
It is straightforward to drop the enum from the switch-statements story.  It plays only a minor part.

My only reservation is that `enum` seems to me to be a more fundamental concept than `switch` but I can live with it.

**Comment by ErikSchierboom** [comment]
> It is straightforward to drop the enum from the switch-statements story. It plays only a minor part.
> 
> My only reservation is that enum seems to me to be a more fundamental concept than switch but I can live with it.

I agree with the above.
