### ISSUE TITLE
Ask a question: Hierarchical concepts

### ISSUE THREAD

**Issue by dector** [exercism/v3#249]
Should we implement some kind of hierarchical ontology for concepts?

Motivation: smaller concept can be grouped together and can be referred in more agile way.

For example (non-exhaustive list),

```
Collections
    - Modifying
        - Adding
        - Shuffling
    - Search
        - Searching element index
    - Fetching data
        - Fetching single element
        - Fetching multiple elements
        - Sub-collection
        - Windowing
    - Sorting
        - Asc
        - Desc
        - Random
    - Transformations
        - Mapping
        - Zipping
    - Filtering
    - Folding
    - Slicing
```

instead of big concept `collections` or `collections-basic` + `collection-advanced`.

This will increase number of concepts in general but they can be represented in a fine-granular way and will allow us to include link exercises with a particular aspect of concept.

What do you think?

**Comment by SleeplessByte** [comment]
Hierarchy makes sense if you know what you're looking for, or if you know what something belongs to. In the precursor of this repository we had hierarchy and chose to forego it.

That said, if you make a flat list, the concepts _can_ and _could_ definitely be split in smaller concepts. We already do this! There is a concept about _encoding_, about _utf_ and about _utf8_ and _utf7_. It's absolutely fine to split up concepts and have multiple files. 

I would absolutely vote _against_ the hierarchy tho.

**Comment by ErikSchierboom** [comment]
Personally I don't see that much of a benefit of having a big hierarchy. For example, I wouldn't mind to have "collections-sorting" as a concept, but I feel like including Asc, Desc, Random is a bit too fine-grained. The concept you've chosen (collections) is one that has many facets, so there it makes sense to use some sort of sub-division of concepts, as you don't want to teach everything in a single exercise probably.

I'd try to keep things relatively flat though, so no deeply nested hierarchies?

**Comment by angelikatyborska** [comment]
We have been developing v3 for a whole year now _without_ any plans for nested concept hierarchies, so I'm considering this issue as closed - won't do.
