### ISSUE TITLE
Adding links.json

### ISSUE THREAD

**Issue by iHiD** [exercism/v3#2499]
We are adding a `links.json` file to all concepts. The purpose of this file is provide helpful links that provide more reading or information about a concept. These might be official docs, a great tutorial, the PR that added it to the language, etc.

They will be rendered something like this:
<img width="780" alt="Screenshot 2020-10-16 at 15 50 43" src="https://user-images.githubusercontent.com/286476/96273662-80dfef00-0fc7-11eb-8acf-12589b69b53d.png">

These links do not replace the more contextual links within an `about.md`, but provide a quick set of overarching reference points for a student.

---

Each link needs:
- A `url`
- A `description`, as the link text. 

You will notice in the screenshot we show an icon next to the link. We will use the site's favicon for this, but you may override it by providing an optional `icon_url`.

**Comment by iHiD** [comment]
> Question: Could we add an optional author link to link to their website or whatever if they want

No, credit to the authors of the exercise works through. a different mechanism.

**Comment by SaschaMann** [comment]
I think we're talking about different authors. The authors of those post are probably not on Exercism?

**Comment by iHiD** [comment]
> I think we're talking about different authors. The authors of those posts are probably not on Exercism?

Then no, I don't think we should credit those authors. The authors should be credited on the sites we link to (e.g. if we link to MS docs or Wikipedia pages, those sites should credit their own authors)

**Comment by angelikatyborska** [comment]
Will backticks in the link's description be interpreted as "please write this in a monospace font"?

**Comment by iHiD** [comment]
Yes. But you may have to remind me of this when I forget and it doesn't work 😀

**Comment by SaschaMann** [comment]
Will additional fields be accepted but ignored? I'd like to add a comment of why I think the link belongs to a concept for other maintainers since it's not obvious without following and reading it.

**Comment by iHiD** [comment]
Yep. That's fine. Maybe start the key with `__` to imply that it shoudn't ever be read by the system.

**Comment by iHiD** [comment]
(@ErikSchierboom You might want to move this to configlet repo)
