### ISSUE TITLE
[Elixir] Do string literals warrant a separate concept?

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3#2514]
This topic of discussion was brought up in https://github.com/exercism/v3/pull/2510

`string-literals` are introduced by the `lists` (`LanguageList`) concept exercise. It was necessary to have them there to have any kind of meaningful list exercise idea (otherwise it would have to be based on numbers only).

`strings` is a concept that has its own exercise, and it covers string interpolation, concatenation, the heredoc syntax, and all kinds of modification with the `String` module. That exercise requires `tuples` and `lists`, so it cannot come before the `lists` exercise.

This structure made sense when the concept _exercises_, not concept themselves, were the main focus of v3.

Now, that each concept will be prominently displayed and needs its own `about.md` file with a description, there is doubt if `string-literals` should be its own concept as it is very tiny.

My fear is that including tiny concepts like this one will:
- inflate the tree, and a big concept tree might scare some students and give them a false believe that Elixir is difficult 😉 
- disappoint students that expected each concept to be a fun challenge

Possible solutions:

1. Keep `string-literals` as its own concept and try to write more than one sentence about them. E.g. explain how single-quotes do not create strings, but charlists, mention UTF-8.
2. Remove the `string-literals` concept and instead modify the `basics` concept (`Lasagna` exercise) to include them. For example, add a step:
	> 5 . Create a notification that will tell you when the lasagna is ready
	>
	> ```elixir
	> Lasagna.alarm()
	> # => "Ding! ding! ding!"
	> ```
3. Other ideas that would require @iHiD's input, for example have a concept that is invisible to students, but can still be used for unlocking concept exercises (currently not possible).

**Comment by jwarwick** [comment]
I like the idea of rolling string literals into the `Basics` exercise. I think expanding the complexity of `string-literals` would be more confusing this early in tree.

**Comment by jwarwick** [comment]
I'll take a shot at working it into the `Lasagna` exercise.

**Comment by angelikatyborska** [comment]
Resolved by https://github.com/exercism/v3/pull/2616
