### ISSUE TITLE
[CI] In some PRs, the link checker verifies all files

### ISSUE THREAD

**Issue by SaschaMann** [exercism/v3#2519]
Example: https://github.com/exercism/v3/pull/2474/checks?check_run_id=1265404504
All of the recent mass PRs were affected it seems.

Full logs in case they disappear: https://gist.github.com/SaschaMann/efa0097faadefd23d875f66bb532ec40

**Comment by ErikSchierboom** [comment]
@SaschaMann I think I know why this is the case, and it is actually working as designed. If you look at https://github.com/exercism/v3/blob/master/.github/workflows/valid-links.yml#L31, it has two checks:

1. It checks if it is a push to master
1. It checks if any files were deleted or renamed

Obviously, the first clause doesn't match, however the second one does. Having one or more files deleted or renamed does indeed require more files to be checked than just the files in the PR, as there might have been references to that deleted/renamed file in files that are not in the PR.

**Comment by SaschaMann** [comment]
Ahh, makes sense. Thanks for looking into it :)
