### ISSUE TITLE
[Elixir] Improve Concept Description: `lists`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3#2520]
Extend `languages/elixir/concepts/lists/about.md` so that it explains that lists are not arrays.

Mention:
- random access vs sequential access
- appending to a list in a loop is an anti-pattern, prepend and reverse instead

It doesn't have to be a lot or very detailed, but students should understand that they can't just use lists in Elixir like they would arrays in other languages.

**Comment by neenjaw** [comment]
Agreed, I see this a lot when mentoring rna-transcription and the lists exercises

**Comment by tushartyagi** [comment]
Submitted a PR: https://github.com/exercism/v3/pull/2530
