### ISSUE TITLE
Cross-linking between v3 documents

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#2527]
With our recent exploding of the `after.md` documents into individual concept documents (see [this issue](https://github.com/exercism/v3/issues/2293)), one question we've been asked several times is how to link between documents. An example being wanting to link to the `if-statements` document from the `switch-statements` document. As of right now, we don't have a way of doing that, but we plan on allow some special Markdown to support cross-linking between documents. Note that while our primary focus right now is linking to concept documents, we might at some point also want to support linking to exercises or tracks.

Let's use this issue to discuss the spec for these special Markdown references. One suggestion that was made was something like 
 `[[concept:booleans]]`. The two most important things to consider are:

1. How easy it is to use: ideally it should be simple for users to use.
1. How easy is it to parse: it has to be unambiguous and not conflict with existing Markdown formatting.

**Comment by SleeplessByte** [comment]
Can we use a special reference, and put a GitHub link in so that we can still navigate in our browsers?

**Comment by iHiD** [comment]
To be clear, the cross-linking will be between pages on Exercism. So you could write:

```
This is a little like how a [[concept:switch-statement]] works.
```

And on Exercism we would render a nice "Switch Statement" widget, that can be hovered over to show the blurb of that concept, with a link to whether you've learnt that concept or not, etc.

The key question here is what format we should use for that thing (so is `[[..]]` a good or awful choice, etc).

> put a GitHub link in so that we can still navigate in our browsers

We could do. It would get stripped at Exercism's end though.

**Comment by SleeplessByte** [comment]
> We could do. It would get stripped at Exercism's end though. 

yes fine with me

> The key question here is what format we should use for that thing (so is [[..]] a good or awful choice, etc).

Steal mediawiki: https://www.mediawiki.org/wiki/Help:Links

```
[[concept:switch-statement]]
[[concept:switch-statement|about switch statements]]

# Recommend the ones below so we can still browse on Github
[[[concept:switch-statement]]](https://example.org)
[[[concept:switch-statement|about switch statements]]](https://example.org)
```

[[concept:switch-statement]]
[[concept:switch-statement|about switch statements]]

_Recommend the ones below so we can still browse on Github_
[[[concept:switch-statement]]](https://example.org)
[[[concept:switch-statement|about switch statements]]](https://example.org)

**Comment by ErikSchierboom** [comment]
We've done a bit of work on this spec and wrote it down in https://github.com/exercism/v3-docs/blob/master/anatomy/tracks/cross-linking.md. Some of the constraints we had was that it had to be easy to parse, adhere to the commonmarker spec (no new, custom elements) and also be easy to write/remember. We ended up with the following:

Concept links will use the following format: `[concept:<track-slug>/<concept-slug>]()` As can be seen, it is just a regular link, but one in which the link text uses a predefined format. We'll then dynamically replace this with the widget that will display the concept. The URL part can be empty, but you can also populate it: `[concept:<track-slug>/<concept-slug>](https://exercism.io/tracks/ruby/concepts/if-statements)` The website will ignore the link, but it can be helpful when viewing a document in GitHub or your editor.
