### ISSUE TITLE
[C#] Extract Concepts from v2 exercise: grade-school

### ISSUE THREAD

**Issue by shaynuhcon** [exercism/v3#256]
Extract the list of concepts required to solve the v2 C# exercise: grade-school. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches. The goal of this task is to help determine the total list of concepts that make up C#.

The list of concepts should be stored in the following document: `languages/csharp/reference/exercise-concepts/grade-school.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/csharp/reference/exercise-concepts/grade-school.md

**Comment by ErikSchierboom** [comment]
As @shaynuhcon has indicated not being able to work on this further, I'll assign this to myself.
