### ISSUE TITLE
[C#] rename exercises with interesting names

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#2589]
- [arrays](https://github.com/exercism/v3/tree/master/languages/csharp/exercises/concept/arrays/.docs/instructions.md) bird-watcher
- [basics](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/basics/.docs/instructions.md) lasagna
- [booleans](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/booleans/.docs/instructions.md) annalyn’s-infiltration
- [casting](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/casting/.docs/instructions.md) football-club-security
- [chars](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/chars/.docs/instructions.md) hygenic-developer
- [classes](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/classes/.docs/instructions.md) remote-control-car
- [constants](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/constants/.docs/instructions.md) authentication-system
- [constructors](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/constructors/.docs/instructions.md) need-for-speed
- [datetimes](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/datetimes/.docs/instructions.md) beauty-salon
- [dictionaries](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/dictionaries/.docs/instructions.md) dialing-codes
- [enums](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/enums/.docs/instructions.md) log-lines
- [equality](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/equality/.docs/instructions.md) log-in-with-facial-recognition
- [exceptions](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/exceptions/.docs/instructions.md) simple-calculator
- [expression-bodied-members](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/expression-bodied-members/.docs/instructions.md) weather-station
- [flag-enums](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/flag-enums/.docs/instructions.md) account-permissions
- [floating-point-numbers](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/floating-point-numbers/.docs/instructions.md) savings-account
- [inheritance](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/inheritance/.docs/instructions.md) wizard-and-warriors
- [integral-numbers](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/integral-numbers/.docs/instructions.md) telemetry-bandwidth
- [interfaces](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/interfaces/.docs/instructions.md) remote-control-competition
- [lists](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/lists/.docs/instructions.md) favorite-programming-languages
- [method-overloading](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/method-overloading/.docs/instructions.md) wizard-and-warriors-2
- [namespaces](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/namespaces/.docs/instructions.md) remote-control-meets-darwin
- [nested-types](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/nested-types/.docs/instructions.md) remote-control-cleanup
- [nullability](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/nullability/.docs/instructions.md) name-badges
- [numbers](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/numbers/.docs/instructions.md) assembly-line
- [object-initializers](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/object-initializers/.docs/instructions.md) special-treatment-for-senior-developers
- [operator-overloading](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/operator-overloading/.docs/instructions.md) two-currencies-for-hyperia
- [overflow](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/overflow/.docs/instructions.md) hyperinflation-hits-hyperia
- [parameters](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/parameters/.docs/instructions.md) remote-control-gets-sponsorship
- [properties](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/properties/.docs/instructions.md) weighing-machine
- [randomness](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/randomness/.docs/instructions.md) roll-the-die
- [regular-expressions](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/regular-expressions/.docs/instructions.md) parsing-log-files
- [resource-cleanup](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/resource-cleanup/.docs/instructions.md) object-relational-mapping
- [resource-lifetime](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/resource-lifetime/.docs/instructions.md) orm-in-one-go
- [string-formatting](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/string-formatting/.docs/instructions.md) high-school-sweethearts
- [strings](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/strings/.docs/instructions.md) log-levels
- [structs](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/structs/.docs/instructions.md) land-grab-in-space
- [switch-statements](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/switch-statements/.docs/instructions.md) football-match-reports
- [time](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/time/.docs/instructions.md) beauty-salon-goes-global
- [tuples](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/tuples/.docs/instructions.md) phone-number-analysis
- [user-defined-exceptions](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/user-defined-exceptions/.docs/instructions.md) instruments-of-texas

**Comment by taiyab** [comment]
Other than `annalyn’s-infiltration` probably needing to be `annalyns-infiltration`, this is good as a first pass.

I'll spend some time reviewing and coming up with potentially more interesting names.

**Comment by taiyab** [comment]
**WIP**

* [arrays](https://github.com/exercism/v3/tree/master/languages/csharp/exercises/concept/arrays/.docs/instructions.md) bird-watcher
* [basics](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/basics/.docs/instructions.md) lasagna
* [booleans](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/booleans/.docs/instructions.md) annalyns-infiltration
* [casting](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/casting/.docs/instructions.md) secure-munchester-united
* [chars](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/chars/.docs/instructions.md) squeaky-clean
* [classes](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/classes/.docs/instructions.md) elons-tiny-toys
> * [constants](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/constants/.docs/instructions.md) authentication-system
> * [constructors](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/constructors/.docs/instructions.md) need-for-speed
> * [datetimes](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/datetimes/.docs/instructions.md) beauty-salon
> * [dictionaries](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/dictionaries/.docs/instructions.md) dialing-codes
> * [enums](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/enums/.docs/instructions.md) log-lines
> * [equality](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/equality/.docs/instructions.md) log-in-with-facial-recognition
> * [exceptions](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/exceptions/.docs/instructions.md) simple-calculator
> * [expression-bodied-members](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/expression-bodied-members/.docs/instructions.md) weather-station
> * [flag-enums](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/flag-enums/.docs/instructions.md) account-permissions
> * [floating-point-numbers](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/floating-point-numbers/.docs/instructions.md) savings-account
> * [inheritance](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/inheritance/.docs/instructions.md) wizard-and-warriors
> * [integral-numbers](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/integral-numbers/.docs/instructions.md) telemetry-bandwidth
> * [interfaces](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/interfaces/.docs/instructions.md) remote-control-competition
> * [lists](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/lists/.docs/instructions.md) favorite-programming-languages
> * [method-overloading](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/method-overloading/.docs/instructions.md) wizard-and-warriors-2
> * [namespaces](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/namespaces/.docs/instructions.md) remote-control-meets-darwin
> * [nested-types](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/nested-types/.docs/instructions.md) remote-control-cleanup
> * [nullability](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/nullability/.docs/instructions.md) name-badges
> * [numbers](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/numbers/.docs/instructions.md) assembly-line
> * [object-initializers](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/object-initializers/.docs/instructions.md) special-treatment-for-senior-developers
> * [operator-overloading](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/operator-overloading/.docs/instructions.md) two-currencies-for-hyperia
> * [overflow](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/overflow/.docs/instructions.md) hyperinflation-hits-hyperia
> * [parameters](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/parameters/.docs/instructions.md) remote-control-gets-sponsorship
> * [properties](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/properties/.docs/instructions.md) weighing-machine
> * [randomness](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/randomness/.docs/instructions.md) roll-the-die
> * [regular-expressions](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/regular-expressions/.docs/instructions.md) parsing-log-files
> * [resource-cleanup](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/resource-cleanup/.docs/instructions.md) object-relational-mapping
> * [resource-lifetime](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/resource-lifetime/.docs/instructions.md) orm-in-one-go
> * [string-formatting](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/string-formatting/.docs/instructions.md) high-school-sweethearts
> * [strings](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/strings/.docs/instructions.md) log-levels
> * [structs](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/structs/.docs/instructions.md) land-grab-in-space
> * [switch-statements](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/switch-statements/.docs/instructions.md) football-match-reports
> * [time](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/time/.docs/instructions.md) beauty-salon-goes-global
> * [tuples](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/tuples/.docs/instructions.md) phone-number-analysis
> * [user-defined-exceptions](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/user-defined-exceptions/.docs/instructions.md) instruments-of-texas

**Comment by SleeplessByte** [comment]
> hello-its-tim-from-marketing

This is the best

**Comment by taiyab** [comment]
Bird Watcher
Lucian's Luscious Lasagna
Annalyn's Infiltration
Secure Munchester United
Squeaky Clean
Elon's Tiny Toys
Authentication System
Need for Speed
Booking up for Beauty
International Calling Connoisseur
Log, logs, logs!
Face ID 2.0
Calculator Conundrum
The Weather in Deather
Attack of the Trolls
Interest is Interesting
Wizards and Warriors
Hyper-optimized Telemetry
Remote Control Competition
Tracks on Tracks on Tracks
Wizards and Warriors 2.0
Red vs. Blue: Darwin Style
Remote Control Cleanup
Hello, it's Tim from Marketing
Cars, Assemble!
Why Can't I Push to Master?
Hyperia Forex
Hyperinflation Hits Hyperia
Building Telemetry
Weighing Machine
Roll the Die!
Parsing Log Files
Object Relational Mapping
Orm in One Go
High School Sweethearts
Log Levels
Land Grab in Space
Football Match Reports
Beauty Salon Goes Global
Phone Number Analysis
Instruments of Texas

**Comment by msomji** [comment]
I am unclear what changes would be needed to be made here, is the idea here to update [this config.json](https://github.com/exercism/v3/blob/master/languages/fsharp/config.json) with the new slugs under `exercises["concept"]` and update the folder names to match the same in https://github.com/exercism/v3/tree/master/languages/fsharp/exercises/concept ?

**Comment by ErikSchierboom** [comment]
@msomji The changes will be done by a script of me. We'll show you the end result :)

**Comment by iHiD** [comment]
A couple of suggested changes
- Tim from Marketing (shorter)
- Why Can't I Push To Main (Master -> Main)
