### ISSUE TITLE
[C#] where appropriate rename classes in line with story rename

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3#2725]
Below is a list of C# exercises and the main class names (immediately following the story name).  The purpose of this issue is to align class names with the stories.

I recommend 
- we change bird-watcher to bird-count
- we change the class name HighSchoolSweetheart to HighSchoolSweethearts (but note the variation with Elixir)
- we change the story name why-cant-i-push-to-main to be something more relevant e.g. access-all-areas but I am interested in other views or suggestions as to whether this is necessary.
- no other changes are required.

[annalyns-infiltration](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/annalyns-infiltration/.docs/instructions.md) QuestLogic
[attack-of-the-trolls](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/attack-of-the-trolls/.docs/instructions.md) Permissions
[authentication-system](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/authentication-system/.docs/instructions.md) Authenticator and Identity
[beauty-salon-goes-global](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/beauty-salon-goes-global/.docs/instructions.md) Appointment
[bird-watcher](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/bird-watcher/.docs/instructions.md) BirdCount - we should rename exercise bird-count in line with Elixir etc.
[booking-up-for-beauty](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/booking-up-for-beauty/.docs/instructions.md) Appointment
[building-telemetry](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/building-telemetry/.docs/instructions.md) RemoteControlCar
[calculator-conundrum](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/calculator-conundrum/.docs/instructions.md) SimpleCalculator
[cars-assemble](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/cars-assemble/.docs/instructions.md) AssemblyLine
[elons-toys](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/elons-toys/.docs/instructions.md) RemoteControlCar
[faceid-2](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/faceid-2/.docs/instructions.md) Authenticator
[football-match-reports](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/football-match-reports/.docs/instructions.md) PlayAnalyzer
[high-school-sweethearts](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/high-school-sweethearts/.docs/instructions.md) HighSchoolSweetheart - change to HighSchoolSweetHearts - note that exlir names the exercise high-school-sweetheart (singular)
[hyper-optimized-telemetry](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/hyper-optimized-telemetry/.docs/instructions.md) TelemetryBuffer
[hyperia-forex](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/hyperia-forex/.docs/instructions.md) CurrencyAmount
[hyperinflation-hits-hyperia](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/hyperinflation-hits-hyperia/.docs/instructions.md) CentralBank
[instruments-of-texas](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/instruments-of-texas/.docs/instructions.md) CalculatorTestHarness
[interest-is-interesting](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/interest-is-interesting/.docs/instructions.md) SavingsAccount
[international-calling-connoisseur](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/international-calling-connoisseur/.docs/instructions.md) DialingCodes
[land-grab-in-space](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/land-grab-in-space/.docs/instructions.md) ClaimsHandler
[log-levels](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/log-levels/.docs/instructions.md) LogLine
[logs-logs-logs](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/logs-logs-logs/.docs/instructions.md) LogLine
[lucians-luscious-lasagna](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/lucians-luscious-lasagna/.docs/instructions.md) Lasagna
[need-for-speed](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/need-for-speed/.docs/instructions.md) RemoteControlCar
[object-relational-mapping](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/object-relational-mapping/.docs/instructions.md) Orm
[orm-in-one-go](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/orm-in-one-go/.docs/instructions.md) Orm
[parsing-log-files](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/parsing-log-files/.docs/instructions.md) LogParser
[phone-number-analysis](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/phone-number-analysis/.docs/instructions.md) PhoneNumber
[red-vs-blue-darwin-style](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/red-vs-blue-darwin-style/.docs/instructions.md) RemoteControlCar
[remote-control-cleanup](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/remote-control-cleanup/.docs/instructions.md) RemoteControlCar
[remote-control-competition](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/remote-control-competition/.docs/instructions.md) TestTrack
[roll-the-die](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/roll-the-die/.docs/instructions.md) Player
[secure-munchester-united](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/secure-munchester-united/.docs/instructions.md) SecurityPassMaker
[squeaky-clean](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/squeaky-clean/.docs/instructions.md) Identifier
[the-weather-in-deather](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/the-weather-in-deather/.docs/instructions.md) WeatherStation
[tim-from-marketing](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/tim-from-marketing/.docs/instructions.md) Badge
[tracks-on-tracks-on-tracks](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/tracks-on-tracks-on-tracks/.docs/instructions.md) Languages
[weighing-machine](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/weighing-machine/.docs/instructions.md) WeighingMachine
[why-cant-i-push-to-main](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/why-cant-i-push-to-main/.docs/instructions.md) Authenticator - the title seems a bit of a stretch.  The story concerns a generic authentication system.
[wizards-and-warriors](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/wizards-and-warriors/.docs/instructions.md) Warrior
[wizards-and-warriors-2](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/wizards-and-warriors-2/.docs/instructions.md) GameMaster and Character

**Comment by ErikSchierboom** [comment]
Yes, this list looks good to me actually 👍 I do agree that `Authenticator` might be up for a tweak.

**Comment by mikedamay** [comment]
The name bird-watcher has been left unchanged as it was agreed at the Hackathon.

Class name BirdCount has been left unchanged as it is more appropriate given the method names and behaviour of the class.

**Comment by mikedamay** [comment]
class `HighSchoolSweetheart` has been renamed to `HighSchoolSweethearts` in PR #2731.

**Comment by mikedamay** [comment]
Created PR rename exercise to developer-privileges #2815

**Comment by mikedamay** [comment]
No other changes were required
