### ISSUE TITLE
[CI] Automatically push updated Docker images to dockerhub

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#2727]
The [v3 development environment](https://github.com/exercism/development-environment/) uses Docker images from Docker Hub for all the tooling (although you can overwrite this). Each tooling repo should have a workflow to automatically push to Docker Hub whenever something is merged to master.

**Comment by saurabh896** [comment]
@ErikSchierboom Can we use the GH action with the manual trigger?

**Comment by ErikSchierboom** [comment]
@saurabh896 I don't think you can at the moment. You'd have to create a PR to add that feature.

**Comment by ErikSchierboom** [comment]
Will be superseded by new PRs. See #2969
