### ISSUE TITLE
[Tooling] Update the bot PRs instead of opening new ones

### ISSUE THREAD

**Issue by SaschaMann** [exercism/v3#2752]
The Pull Request view of this repo is spammed with bot PRs. It would be nicer if the bot would look for an existing, unmerged PR and then push to that branch instead of opening a new PR.

Otherwise it's a lot harder to keep track of what's actually going on or find recent PRs, e.g. because you accidentally unsubscribed from a notification like I just did.

**Comment by ErikSchierboom** [comment]
Nice idea. Don't know when I have time for this though.

**Comment by angelikatyborska** [comment]
I believe this issue is no longer relevant after we explode the v3 repo back into track repos and deprecate this one.
