### ISSUE TITLE
feature request: allow mentors to see diffs between students' various iterations

### ISSUE THREAD

**Issue by coriolinus** [exercism/v3#2773]
I have a student who's submitted three different solutions to an exercise. At first glance, the solutions are all very similar. Right now, the only thing I can easily say about the difference is that they have gotten consistently shorter: the first solution is 317 lines, then second 301, the third 295. 

I can't easily view the diffs offline: `exercism download` doesn't offer an `iteration` flag I could use to manually diff them. That's a separate, lower-priority issue.

What I really want is a UI like github's, where within a PR, I can select an arbitrary commit or range of commits to see the changes. A similar thing would be great among the iterations: select a single iteration to see its full status, or any two iterations to see the diff between them.

**Comment by angelikatyborska** [comment]
This feature is coming to v3! See: https://exercism-team.slack.com/archives/CR91YFNG3/p1611007451042900

**Comment by iHiD** [comment]
It is yes. Although it might not come quite at launch. But we have all the design work done for it :)
