### ISSUE TITLE
[Python] Update Exercises Table on `../python/exercises/README.md`

### ISSUE THREAD

**Issue by Limm-jk** [exercism/v3#2874]
- The language this question applies to Python / Exercise Readme

Readme file for exercises was not updated while various python issues were added to V3.
If you don't mind, I would like to update including the current problems.

Thanx!

![image](https://user-images.githubusercontent.com/57378834/100522754-95cab780-31ee-11eb-9d49-8bfffd60a32d.png)

**Comment by BethanyG** [comment]
@Limm-jk  - Sure!  ⭐   We'd love to have you submit a PR to update the exercise table with the concept exercises we've completed thus far.  Thank you for logging this issue and pointing that out!  🎉

**Comment by BethanyG** [comment]
Just let us know if you have any questions or issues with it.

**Comment by BethanyG** [comment]
@Limm-jk   I was in this repo to add an exercise prerequisite tree, so updated the table while I was doing that.

**Comment by Limm-jk** [comment]
Thank you.
I'll try to make other better contributions!
