### ISSUE TITLE
[Elixir] Add missing "name" field to config.json

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#2890]
Elixir's [config.json file](https://github.com/exercism/v3/blob/master/languages/elixir/config.json#L14) has some concept exercises for which the `name` property is not set. This prevents the `config.json` from being imported in the v3 sync script I'm building.

**Comment by ErikSchierboom** [comment]
FYI @exercism/elixir

**Comment by angelikatyborska** [comment]
@ErikSchierboom I thought the `name` field is optional and only needs to be set if a nice name cannot be generated from the `slug`.

**Comment by ErikSchierboom** [comment]
Hmmm, I can't remember. I'll check

**Comment by ErikSchierboom** [comment]
Having discussed this, we do want to make the name compulsary, but we'll auto-generate them all from the slug at the Big Bang if it they're not specified. So let's close this.
