### ISSUE TITLE
[Elixir] Improve concept exercises by ensuring that single tests are self-contained

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/v3#2894]
The PR https://github.com/exercism/elixir-test-runner/pull/23 introduces extracting the content of a test block (anything inside `test do ... end`) as part of the test metadata that will be presented to the student using the web editor when the test fails. For the student to be able to understand why the test failed, the test block needs to provide all information that makes up the test. This is because concept exercises will not show the test suite in the web editor (source: https://github.com/exercism/elixir-test-runner/pull/23#issuecomment-739317478).

This means that in concept exercise tests, we need to avoid using aliases, module attributes, or setup blocks if possible. That might force us to write more repetitive code than we're used to.

Tests that need fixing:
- ~`basketball_website_test.exs`~ https://github.com/exercism/v3/pull/2957
- ~`boutique_suggestions_test.exs`~ https://github.com/exercism/v3/pull/2956
- ~`high_score_test.exs`~ https://github.com/exercism/v3/pull/2955
- ~`kitchen_calculator_test.exs` (just the alias)~ https://github.com/exercism/v3/pull/2954
- ~`language_list_test.exs`~ https://github.com/exercism/v3/pull/2953
- ~`remote_control_car_test.exs`~ https://github.com/exercism/v3/pull/2952
- ~`rpn_calculator/output_test`.exs~ https://github.com/exercism/v3/pull/2934
- ~`wine_cellar_test.exs`~ https://github.com/exercism/v3/pull/2933

This can be split into many PRs done by different people. Feel free to pick one and fix it.

After changing the tests, make sure that the example solution still passes them.

**Comment by neenjaw** [comment]
In the case of [`rpn_calculator/output_test.exs`](https://github.com/exercism/v3/blob/master/languages/elixir/exercises/concept/rpn-calculator-output/test/rpn_calculator/output_test.exs) this should also just be the module attributes to reuse values, not the `open/1` or `close/1` function.

**Comment by neenjaw** [comment]
- [`basketball_website_test.exs`](https://github.com/exercism/v3/blob/master/languages/elixir/exercises/concept/basketball-website/test/basketball_website_test.exs)
- [`boutique_suggestions_test.exs`](https://github.com/exercism/v3/blob/master/languages/elixir/exercises/concept/boutique-suggestions/test/boutique_suggestions_test.exs)
- [`high_score_test.exs`](https://github.com/exercism/v3/blob/master/languages/elixir/exercises/concept/high-score/test/high_score_test.exs)
- [`kitchen_calculator_test.exs`](https://github.com/exercism/v3/blob/master/languages/elixir/exercises/concept/kitchen-calculator/test/kitchen_calculator_test.exs) (just the alias)
- [`language_list_test.exs`](https://github.com/exercism/v3/blob/master/languages/elixir/exercises/concept/language-list/test/language_list_test.exs)
- [`remote_control_car_test.exs`](https://github.com/exercism/v3/blob/master/languages/elixir/exercises/concept/remote-control-car/test/remote_control_car_test.exs)
- [`rpn_calculator/output_test.exs`](https://github.com/exercism/v3/blob/master/languages/elixir/exercises/concept/rpn-calculator-output/test/rpn_calculator/output_test.exs)
- [`wine_cellar_test.exs`](https://github.com/exercism/v3/blob/master/languages/elixir/exercises/concept/wine-cellar/test/wine_cellar_test.exs)

**Comment by angelikatyborska** [comment]
Done!
