### ISSUE TITLE
[Scala] Extract Concepts from v2 exercise: <Hamming>

### ISSUE THREAD

**Issue by ricemery** [exercism/v3#295]
Extract the list of concepts required to solve the v2 Scala exercise: `Hamming`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/scala/exercises/hamming/solutions`). The goal of this task is to help determine the total list of concepts that make up `hamming`.

The list of concepts should be stored in the following document: `languages/scala/reference/exercise-concepts/hamming.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/scala/reference/exercise-concepts/hamming.md

**Comment by ErikSchierboom** [comment]
Closed by #399.
