### ISSUE TITLE
[Elixir] Extract Concepts from v2 exercise: bank-account

### ISSUE THREAD

**Issue by filalex77** [exercism/v3#300]
Extract the list of concepts required to solve the v2 Elixir exercise: `bank-account`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/elixir/exercises/bank-account/solutions`). The goal of this task is to help determine the total list of concepts that make up `bank-account`.

The list of concepts should be stored in the following document: `languages/elixir/reference/exercise-concepts/bank-account.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/elixir/reference/exercise-concepts/bank-account.md

**Comment by neenjaw** [comment]
@filalex77 is there a PR for this yet?

**Comment by filalex77** [comment]
@neenjaw Just pushed a PR #1296.
