### ISSUE TITLE
[Elixir] Extract Concepts from v2 exercise: word-count

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/v3#302]
Extract the list of concepts required to solve the v2 Elixir exercise: `word-count`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/elixir/exercises/word-count/solutions`). The goal of this task is to help determine the total list of concepts that make up `word-count`.

The list of concepts should be stored in the following document: `languages/elixir/reference/exercise-concepts/word-count.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/elixir/reference/exercise-concepts/word-count.md

**Comment by neenjaw** [comment]
@Cohen-Carlisle is there a PR for this yet?

**Comment by Cohen-Carlisle** [comment]
There is now :slightly_smiling_face:
See https://github.com/exercism/v3/pull/851
