### ISSUE TITLE
[Julia] Extract Concepts from v2 exercise: robot-name

### ISSUE THREAD

**Issue by SaschaMann** [exercism/v3#324]
Extract the list of concepts required to solve the v2 julia exercise: [`robot-name`](https://github.com/exercism/julia/tree/master/exercises/robot-name). For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches ([published community solutions](https://exercism.io/tracks/julia/exercises/robot-name/solutions)). The goal of this task is to help determine the total list of concepts that make up `robot-name`.

The list of concepts should be stored in the following document: `languages/julia/reference/exercise-concepts/robot-name.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/julia/reference/exercise-concepts/robot-name.md

---

**v2 Metadata**

```
core
  → true

difficulty
  → 5

topics
  → randomness
  → strings
  → structs
```

**Comment by SaschaMann** [comment]
@ErikSchierboom The project tracks the status so unless it's an absolute must-have, I'd rather not duplicate that info in the labels.

**Comment by ErikSchierboom** [comment]
@SaschaMann I understand that the information is duplicated, but the thing is that not all tracks use the project feature and I'd like to have have at least one consistent way in which people can find out open issues. Makes sense?
