### ISSUE TITLE
[Go] Implement new Concept Exercise: numbers

### ISSUE THREAD

**Issue by tehsphinx** [exercism/v3#371]
This issue describes how to implement the `numbers` concept exercise for the Go track.

## Goal

The goal of this exercise is to teach the student how to deal with numbers in Go.

## Things to teach

- This should introduce the `int` and `float64` types (be basic number types in Go).
- It should introduce operations with numbers like multiplication, division, etc.
- This should also introduce the concept of `zero values`.
- should introduce the increment `++` and operators like `+=`, `-=`, etc.

My suggestion is to copy C# `numbers` exercise: https://github.com/exercism/v3/tree/master/languages/csharp/exercises/concept/numbers

## Concepts

- `numbers`

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by DavyJ0nes** [comment]
I'd like to tackle this exercise if it's ok?

**Comment by tehsphinx** [comment]
Sure :) I assigned you, but feel free to do that yourself.

You can then also move it on the project dashboard to `in-progress` column and remove `help-wanted` status and add `in-progress` status. I'll do that on this one for you

**Comment by tehsphinx** [comment]
Now it's all yours 😄

**Comment by DavyJ0nes** [comment]
Nice one thank you. :smiley: 

I couldn't seem to assign myself to the ticket, think it's most likely that I haven't got a contribution yet into the project. I'll put up a PR adding myself to the maintainers list, which should sort that out!

**Comment by tehsphinx** [comment]
You also need to add yourself in the Go repo to the `maintainers.json`: https://github.com/exercism/go/blob/master/config/maintainers.json

**Comment by DavyJ0nes** [comment]
I've put an initial PR up for this exercise: https://github.com/exercism/v3/pull/480 but I currently can't modify the labels on the PR to add`track/go` to it, which is most likely related to needing the `maintainers.json` PR needing reviewed and merged (have opened that as well: https://github.com/exercism/go/pull/1330)

**Comment by tehsphinx** [comment]
Nice!

exercism/go#1330 is merged now :)
