### ISSUE TITLE
[Go] Extract Concepts from v2 exercise: Raindrops

### ISSUE THREAD

**Issue by ZoltanOnody** [exercism/v3#379]
Extract the list of concepts required to solve the v2 Go exercise: `raindrops`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/go/exercises/raindrops/solutions`). The goal of this task is to help determine the total list of concepts that make up `raindrops`.

The list of concepts should be stored in the following document: `languages/go/reference/exercise-concepts/raindrops.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/go/reference/exercise-concepts/raindrops.md

**Comment by tehsphinx** [comment]
@ZoltanOnody: can we close this one? Seems like a duplicate of #380. If you still need this just reopen it.
