### ISSUE TITLE
[Python] Extract Concepts from v2 exercise: book-store

### ISSUE THREAD

**Issue by cmccandless** [exercism/v3#381]
Extract the list of concepts required to solve the v2 Python exercise: `book-store`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/Python/exercises/book-store/solutions`). The goal of this task is to help determine the total list of concepts that make up `book-store`.

The list of concepts should be stored in the following document: `languages/Python/reference/exercise-concepts/book-store.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/Python/reference/exercise-concepts/book-store.md

**Comment by BethanyG** [comment]
@cmccandless  - can we close this, or do you still need to do additional work on it?

**Comment by cmccandless** [comment]
> do you still need to do additional work on it?

Technically, yes, but...

> can we close this

yes, unless there's a v3 requirement that _every_ v2 exercise needs Concept extraction. My understanding was that the Concept extraction was only to generate a list of Concepts. That list seems sufficient to me now, without extraction of the remaining exercises.
