### ISSUE TITLE
[Python] Extract Concepts from v2 exercise: zipper

### ISSUE THREAD

**Issue by cmccandless** [exercism/v3#382]
Extract the list of concepts required to solve the v2 Python exercise: `zipper`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/python/exercises/zipper/solutions`). The goal of this task is to help determine the total list of concepts that make up `zipper`.

The list of concepts should be stored in the following document: `languages/python/reference/exercise-concepts/zipper.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/python/reference/exercise-concepts/zipper.md

**Comment by BethanyG** [comment]
@cmccandless  - can we close this as done or no longer relevant?

**Comment by cmccandless** [comment]
See https://github.com/exercism/v3/issues/381#issuecomment-663159575
