### ISSUE TITLE
[Python] Extract Concepts from v2 exercise: variable-length-quantity

### ISSUE THREAD

**Issue by DavidGerva** [exercism/v3#390]
Extract the list of concepts required to solve the v2 Python exercise: `variable-length-quantity`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/Python/exercises/variable-length-quantity/solutions`). The goal of this task is to help determine the total list of concepts that make up `variable-length-quantity`.

The list of concepts should be stored in the following document: `languages/Python/reference/exercise-concepts/variable-length-quantity.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/Python/reference/exercise-concepts/variable-length-quantity.md

**Comment by yawpitch** [comment]
Closed by #700
