### ISSUE TITLE
[Python] Extract Concepts from v2 exercise: tree-building

### ISSUE THREAD

**Issue by DavidGerva** [exercism/v3#391]
Extract the list of concepts required to solve the v2 Python exercise: `tree-building`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/Python/exercises/tree-building/solutions`). The goal of this task is to help determine the total list of concepts that make up `tree-building`.

The list of concepts should be stored in the following document: `languages/Python/reference/exercise-concepts/tree-building.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/Python/reference/exercise-concepts/tree-building.md

**Comment by BethanyG** [comment]
@cmccandless  - do we still need this to be open?

**Comment by cmccandless** [comment]
See https://github.com/exercism/v3/issues/381#issuecomment-663159575
