### ISSUE TITLE
[C#] Extract Concepts from v2 exercise: isbn-verifier

### ISSUE THREAD

**Issue by bmeverett** [exercism/v3#397]
Extract the list of concepts required to solve the v2 C# exercise: `isbn-verifier`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/csharp/exercises/isbn-verifier/solutions`). The goal of this task is to help determine the total list of concepts that make up `isbn-verifier`.

The list of concepts should be stored in the following document: `languages/csharp/reference/exercise-concepts/isbn-verifier.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/csharp/reference/exercise-concepts/isbn-verifier.md

**Comment by ErikSchierboom** [comment]
@bmeverett Small bump to notify you that this issue is assigned to you.
