### ISSUE TITLE
[Java] Extract Concepts from v2 exercise: Hamming

### ISSUE THREAD

**Issue by joshiraez** [exercism/v3#412]
Extract the list of concepts required to solve the v2 Java exercise: `Hamming`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/Java/exercises/Hamming/solutions`). The goal of this task is to help determine the total list of concepts that make up `Hamming`.

The list of concepts should be stored in the following document: `languages/Java/reference/exercise-concepts/Hamming.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/Java/reference/exercise-concepts/Hamming.md

**Comment by mirkoperillo** [comment]
This issue can be closed.

The list of concepts has been extracted taking the C# one as reference.
