### ISSUE TITLE
[Go] Implement new Concept Exercise: maps

### ISSUE THREAD

**Issue by tehsphinx** [exercism/v3#427]
This issue describes how to implement the `maps` concept exercise for the Go track.

## Goal

The goal is to introduce the student to `maps`.

## Things to teach

- initializing `maps`, empty and with values.
- `nil` map will `panic`
- settings key/value pairs
- reading a key, non-existent key returns `zero value` of value type
- using `ok` to check if the key existed

## Things not to teach

- iterate over map

## Concepts

- `maps`

## Prerequisites

- `numbers`
- `conditionals`
- `functions`

## Implementing

Here you can find the [Implementation Guide](https://github.com/exercism/v3/blob/master/languages/go/docs/implementing-a-concept-exercise.md).

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by ilknarf** [comment]
I can work on this

**Comment by tehsphinx** [comment]
@ilknarf Welcome! We appreciate this a lot! Let me know if you need any help.

I assigned this issue to you and set the status to in-progress. It's all yours now! 😄

**Comment by oanaOM** [comment]
concept exercise merged. Closing this.
