### ISSUE TITLE
[Rust] Extract Concepts from v2 exercise: robot-simulator

### ISSUE THREAD

**Issue by filalex77** [exercism/v3#442]
Extract the list of concepts required to solve the v2 Rust exercise: `robot-simulator`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/rust/exercises/robot-simulator/solutions`). The goal of this task is to help determine the total list of concepts that make up `robot-simulator`.

The list of concepts should be stored in the following document: `languages/rust/reference/exercise-concepts/robot-simulator.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/rust/reference/exercise-concepts/robot-simulator.md

**Comment by efx** [comment]
@filalex77 howdy :wave: ! are you still working on this or shall we open it up for other contributors?

**Comment by filalex77** [comment]
@efx Thanks for reminding me! I'll try to do this tomorrow (seems like very little work), if not - I'll let you know. :)

**Comment by efx** [comment]
sure thing @filalex77. Thank you!
