### ISSUE TITLE
[Java] Extract Concepts from v2 exercise: Leap

### ISSUE THREAD

**Issue by pdmoore** [exercism/v3#445]
Extract the list of concepts required to solve the v2 Java exercise: `leap`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/java/exercises/leap/solutions`). The goal of this task is to help determine the total list of concepts that make up `leap`.

The list of concepts should be stored in the following document: `languages/java/reference/exercise-concepts/leap.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/java/reference/exercise-concepts/leap.md

**Comment by mirkoperillo** [comment]
Fixed by PR #628
