### ISSUE TITLE
[Java] Extract Concepts from v2 exercise: rotational-cipher

### ISSUE THREAD

**Issue by pdmoore** [exercism/v3#446]
Extract the list of concepts required to solve the v2 Java exercise: `rotational-cipher`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/java/exercises/rotational-cipher/solutions`). The goal of this task is to help determine the total list of concepts that make up `rotational-cipher`.

The list of concepts should be stored in the following document: `languages/java/reference/exercise-concepts/rotational-cipher.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/java/reference/exercise-concepts/rotational-cipher.md

**Comment by zefsar-7seQsi-kocvan** [comment]
Please

**Comment by mirkoperillo** [comment]
This issue can be closed.

The list of concepts has been extracted taking the C# one as reference.
