### ISSUE TITLE
[Clojure] Implement new concept exercise: numbers

### ISSUE THREAD

**Issue by porkostomus** [exercism/v3#457]
This issue describes a new `numbers` concept exercise for the Clojure track.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before diving into the implementation, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

## Goal

The goal of this exercise is to teach the student how numbers are implemented in Clojure. Since they are generally represented as per Java, and the [official reference docs](https://clojure.org/reference/reader) provide little additional insight, care should be taken to be concise but also comprehensive. While Clojure is a hosted language, it must not be assumed that the student is familiar with the host language's concepts, in this case Java numbers,

## Things to teach

After completing this exercise, the student should:

- Know how numbers are represented in Clojure
- Know the range of Longs, BigInts, Doubles and BigDecimals and their notation
- Know the existence of ratios and how to use them
- Know which number types are "contagious" across their operations

## Things not to teach

The following things are outside the scope of this exercise:

- Arithmetic operations
- Querying/manipulating data

## Concepts

This Concepts Exercise's Concepts are:

- `number`
- `big_integer`
- `decimal number`
- `double`
- `floating_point_number`
- `integer`
- `long`

## Prerequisites

Numbers are language primitives, therefore this exercise should be reasonably self-explanatory. It would not be fair to assume prior knowledge beyond simple counting.

### Hints

- [Clojure cheatsheet](https://clojure.org/api/cheatsheet)
- [Clojure reference](https://clojure.org/reference/data_structures)

### After

- [Java Longs](https://docs.oracle.com/javase/8/docs/api/java/lang/Long.html)
- [Java Doubles](https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html)
- [Java BigDecimals](https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html)

## Representer

This exercise does not require any specific representation logic to be added to the representer.

## Analyzer

This exercise does not require any specific logic to be added to the analyzer.

## Implementing

To implement a Clojure concept exercise, the following files must be created:

```
languages
└── clojure
    └── exercises
        └── concept
            └── <SLUG>
                ├── .docs
                |   ├── instructions.md
                |   ├── introduction.md
                |   ├── hints.md
                |   └── after.md (optional)
                ├── .meta
                |   |── design.md
                |   └── Example.clj
                ├── <NAME>.clj
                └── <NAME>_test.clj
```

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by bemself** [comment]
@porkostomus thank you for this new concept issue, very nice! 

I have a few things to discuss with you, regarding things to teach, I feel like this is a bit too much in one concept, how about we limit to a few very commonly used ones, like integer, double etc, and leave others in the After? 

>  number
    big_integer
    decimal number
    double
    floating_point_number
    integer
    long

And for those not to teach, I'd also suggest adding some basic operations with numbers, like addition, compare, convert etc. The idea behind this is, once a person learns a concept, put it into use immediately to strengthen it, even though we have practice exercises later:-)

**Comment by porkostomus** [comment]
I agree, I have wildly rethought my approach to Concepts since writing this. This was to be expected, and will be addressed by breaking this up into 2 (or more) exercises.

**Comment by porkostomus** [comment]
Finished, see #1807
