### ISSUE TITLE
Track documentation difficult to find on website

### ISSUE THREAD

**Issue by cmccandless** [exercism/v3#498]
Since the switch to v2, I've had difficulty locating various [track documentation] on exercism.io. The only consistent way I've found of reaching these pages is from an in-progress (i.e. started, but not submitted yet) exercise; from the exercise page in this state, the links are in the sidebar.

I have trouble finding these docs even though I know they are on the site. It's little wonder I see issues reported every couple of months by beginners to the site that could probably answer their own question if the docs were more accessible.

The only action I can suggest from this issue is that any UI redesign that takes place for v3 makes the track documentation easier to find. Perhaps all pages under the track have links to the docs in the page footer, as well as more visible links where appropriate?

**Comment by cmccandless** [comment]
Additional datapoint: The above currentlyu only applies to a track that is in **Practice Mode**.

**Comment by iHiD** [comment]
We will be having a comprehensive docs area in v3 that pulls in the relevant docs from all the repos into one space :)

Track-specific data is something we should also put clear links to on the Track Overview page, or at least a link to "Read the Exercism Ruby docs" on there, which takes you to the Ruby bit of the general docs.

(cc @taiyab)
