### ISSUE TITLE
[Elixir] Need maintainers.md created/populated

### ISSUE THREAD

**Issue by neenjaw** [exercism/v3#52]
In response to [the steps towards v3 for elixir](https://github.com/exercism/v3/blob/master/languages/elixir/README.md#preparation-status), we need a `maintainers.md` created in this repo at `exercism/v3/languages/elixir/maintainers.md`

This would be a good PR to complete if it's one of your first in the exercism ecosystem.

As it states in the readme, see the [C# maintainers.md](https://github.com/exercism/v3/blob/master/languages/csharp/maintainers.md) for the pattern to follow.

Ping: @nathanchere, @fireproofsocks, or anyone else.  Please reference this issue in the PR

**Comment by aimorris** [comment]
#114
