### ISSUE TITLE
[Elixir] Add Elixir issues link to README.md

### ISSUE THREAD

**Issue by neenjaw** [exercism/v3#53]
## Description

In response to [the steps towards v3 for elixir](https://github.com/exercism/v3/blob/master/languages/elixir/README.md#preparation-status), we need to add a link to elixir's v3 issues in the [main v3 readme file](https://github.com/exercism/v3/blob/master/README.md) 

This would be a good PR to complete if it's one of your first in the exercism ecosystem.

### Contributing

- fork the repo, in a branch make the changes needed to the [README.md](https://github.com/exercism/v3/blob/master/README.md), submit a PR for the changes to the master.

## Help

If you have any questions while adding the reference document, please post the questions as comments in this issue.

Ping: @nathanchere, @fireproofsocks, or anyone else.  Please reference this issue in the PR

**Comment by aimorris** [comment]
#69
