### ISSUE TITLE
[Elixir] Extract Concepts from v2 exercise: roman-numerals

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/v3#616]
Extract the list of concepts required to solve the v2 Elixir exercise: `roman-numerals`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/elixir/exercises/roman-numerals/solutions`). The goal of this task is to help determine the total list of concepts that make up `roman-numerals`.

The list of concepts should be stored in the following document: `languages/elixir/reference/exercise-concepts/roman-numerals.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/elixir/reference/exercise-concepts/roman-numerals.md

**Comment by neenjaw** [comment]
@chriseyre2000 is there a PR for this yet?

**Comment by chriseyre2000** [comment]
Not yet.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Tim Austin <notifications@github.com> Date: 29/02/2020  20:36  (GMT+00:00) To: exercism/v3 <v3@noreply.github.com> Cc: Christopher Eyre <chriseyre2000@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [exercism/v3] [Elixir] Extract Concepts from v2 exercise: roman-numerals (#616) @chriseyre2000 is there a PR for this yet?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/exercism/v3/issues/616?email_source=notifications\u0026email_token=AAIMRX37NMD2WC7IRJFPWBTRFFYU3A5CNFSM4KR2HKZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENMFNNI#issuecomment-592991925",
"url": "https://github.com/exercism/v3/issues/616?email_source=notifications\u0026email_token=AAIMRX37NMD2WC7IRJFPWBTRFFYU3A5CNFSM4KR2HKZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENMFNNI#issuecomment-592991925",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by neenjaw** [comment]
Ok, I don't know if you have reviewed: https://github.com/exercism/v3/blob/master/languages/elixir/reference/README.md

If you don't think there might be extra concepts to add, it may not be necessary to do this concept mapping exercise if they are already likely covered.

**Comment by neenjaw** [comment]
One milestone which was communicated in the v3 update is that we have approx 3 weeks to map out 20ish concept exercises (sans implementation) so that when @ihid does the research all-call that we can piggyback off of that momentum

**Comment by chriseyre2000** [comment]
I have been busy with a few other things the last few weeks.

I may be able to add to the concepts list today.

**Comment by chriseyre2000** [comment]
I have added a few suggestions and sent a PR
