### ISSUE TITLE
[C#] Extract Concepts from v2 exercise: rna-transcriptions

### ISSUE THREAD

**Issue by maurelio1234** [exercism/v3#623]
Extract the list of concepts required to solve the v2 C# exercise: `rna-trascriptions`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/csharp/exercises/rna-trascriptions/solutions`). The goal of this task is to help determine the total list of concepts that make up `rna-trascriptions`.

The list of concepts should be stored in the following document: `languages/csharp/reference/exercise-concepts/rna-trascriptions.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/csharp/reference/exercise-concepts/rna-trascriptions.md

**Comment by maurelio1234** [comment]
@ErikSchierboom  can you assign this issue to me?

**Comment by ErikSchierboom** [comment]
@maurelio1234 Done.

**Comment by ErikSchierboom** [comment]
Closed by #626
