### ISSUE TITLE
[C#] Extract Concepts from v2 exercise: leap

### ISSUE THREAD

**Issue by fpetru** [exercism/v3#627]
Extract the list of concepts required to solve the v2 C# exercise: `leap`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/csharp/exercises/leap`). The goal of this task is to help determine the total list of concepts that make up `leap`.

The list of concepts should be stored in the following document: `languages/csharp/reference/exercise-concepts/leap.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/csharp/reference/exercise-concepts/leap.md

**Comment by fpetru** [comment]
@ErikSchierboom - please assign this issue to me. Thank you

**Comment by ErikSchierboom** [comment]
Closed by #640.
