### ISSUE TITLE
[JavaScript] Extract Concepts from v2 exercise: resistor-color-duo

### ISSUE THREAD

**Issue by Calamari** [exercism/v3#634]
Extract the list of concepts required to solve the v2 JavaScript exercise: `resistor-color-duo`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/resistor-color-duo/exercises/resistor-color-duo/solutions`). The goal of this task is to help determine the total list of concepts that make up `resistor-color-duo`.

The list of concepts should be stored in the following document: `languages/JavaScript/reference/exercise-concepts/resistor-color-duo.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/JavaScript/reference/exercise-concepts/resistor-color-duo.md

**Comment by aimorris** [comment]
@Calamari Is this still in-progress?

**Comment by aimorris** [comment]
https://github.com/exercism/v3/blob/master/languages/javascript/reference/exercise-concepts/resistor-color-duo.md
