### ISSUE TITLE
[JavaScript] Extract Concepts from v2 exercise: Pangram

### ISSUE THREAD

**Issue by hayashi-ay** [exercism/v3#653]
Extract the list of concepts required to solve the v2 JavaScript exercise: `Pangram`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/JavaScript/exercises/Pangram/solutions`). The goal of this task is to help determine the total list of concepts that make up `Pangram`.

The list of concepts should be stored in the following document: `languages/JavaScript/reference/exercise-concepts/Pangram.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/JavaScript/reference/exercise-concepts/Pangram.md

**Comment by aimorris** [comment]
@hayashi-ay is this still in-progress/are you still working on it?

**Comment by hayashi-ay** [comment]
@aimorris No. I created PR(#1048) and it was merged.

**Comment by aimorris** [comment]
#1048
