### ISSUE TITLE
[Python] Extract Concepts from v2 exercise: reverse-string

### ISSUE THREAD

**Issue by khoivan88** [exercism/v3#656]
Extract the list of concepts required to solve the v2 Python exercise: `reverse-string`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/python/exercises/reverse-string/solutions`). The goal of this task is to help determine the total list of concepts that make up `reverse-string`.

The list of concepts should be stored in the following document: `languages/python/reference/exercise-concepts/reverse-string.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/python/reference/exercise-concepts/reverse-string.md

**Comment by yawpitch** [comment]
Closed by #700
