### ISSUE TITLE
[Roadmap] Concepts definition

### ISSUE THREAD

**Issue by tehsphinx** [exercism/v3#706]
This is feedback on the v3 roadmap (#690).

---

> What do we mean by concepts?
> By concepts we mean things that a programmer would need to understand to be fluent in a language. We care specifically about how languages are different. What do I need to learn differently about numbers in Haskell to numbers in Ruby to be able to work with numbers in those languages. Two questions that we have felt useful to ask to establish this are:
> If someone learnt Ruby, and someone learnt Haskell, what are the things that the two people learnt that are different?
> If a Ruby programmer learnt Haskell, what new concepts would they have to learn, what knowledge would they have to disregard, and what syntax would they have to remap?
> By teaching concepts we aim to teach fluency.

1. To me this dosen't define concepts.
2. The question of what is different in languages is a n! (faculty) problem. Not sure if that is helpful.
3. And I can't really see how I should factor that into the concepts / concept exercises. It would mean I can only write concept exercises for people coming from that specific language. But that is not what we are trying to do.

**Comment by iHiD** [comment]
>  It would mean I can only write concept exercises for people coming from that specific language. But that is not what we are trying to do.

The aim is that we design exercises considering the minimum knowledge of someone who can program but knows very different paradigms to the language in question.

By asking ourselves that question, I think we'll find the right level to pitch the exercise at. e.g.

- What does a high-level developer need to learn/remap/unlearn to be able to do something in C?
- What does someone in C need to not worry when learning C#?

I'm very happy to have a better way of defining this, but I've not found a more useful way for myself of working out the right granularity of this yet.

@efx yesterday defined concepts as "practical units for learners of a language that interlock for increased fluency." - I liked that too.

**Comment by tehsphinx** [comment]
Yes, I saw that definition and liked it.

To me this whole paragraph talks about language differences instead of trying to explain what a concept is. If the 'language differences'-section should be used to explain what a concept is, then the conclusion is missing (at least for me).

> We care specifically about how languages are different

I wonder if sending people down that path of language differences is the right approach to concepts and concept exercises. Language differences can exist on many levels: from functional vs OOP languages, to concepts that exist in one language but not the other to different implementation details of the same concept. I'm not sure how that helps to know what a concept is.

**Comment by efx** [comment]
@tehsphinx clarifying question for me: what does "n! (faculty) problem" mean? Is this an unbounded problem? As in having such a wide variety of potential solutions it is not necessarily feasible or quantified.

> Language differences can exist on many levels: from functional vs OOP languages

That distinction came up in the thread and it is something I've been wondering about too. @ErikSchierboom and @SleeplessByte defined it as a group of concepts / paradigm. I do think the FP / OOP distinction and similar groupings require auxiliary approaches to define and teach effectively. I think of them like domain knowledge; mastery requires extended or intensive exposure to the theoretical basis and practical applications.

**Comment by tehsphinx** [comment]
> Is this an unbounded problem? As in having such a wide variety of potential solutions it is not necessarily feasible or quantified.

Yes. n! grows to fast and with the 50+ languages we have it would be an enormous task to consider all possible language combinations. E.g. what is different from C# to Python, what is different from C# to Javascript, what is different from Python to JS, etc. (50! is a number with 64 digits!)

**Comment by angelikatyborska** [comment]
It's been almost a year without activity on this issue, so I am going to assume that it's more clear by know what a "concept" is. A new definition that doesn't mention any comparisons to other languages can be found in https://github.com/exercism/docs/blob/main/product/concept-exercises.md#concept-exercises
