### ISSUE TITLE
[Roadmap] Credits for analyzers and exercises?

### ISSUE THREAD

**Issue by tehsphinx** [exercism/v3#708]
This is feedback on the v3 roadmap (#690).

---

> For example, users with a high reputation for mentoring will be able to take on mentoring requests with higher "bounties", and they will be able to write automated feedback on representations, which then generates more Credits for them every time that feedback is provided to a user in the future.

What about credits for the analyzer on a concept exercise / practice exercise? Will they also generate credits each time they provide feedback?

Or the exercise itself? Will it create credits for those that created it?

**Comment by iHiD** [comment]
I'm not sure of how the credits will accumulate on a recurring or one off basis for things like analyzers or exercises, but you will definitely get credits and reputation for them, yes. The challenge with code contributions on a recurring basis is that it's hard to measure how those credits should be assigned between all the people who have worked on that thing. A credit-per-commit system with some weighting for significant contributions might therefore be more sane.

Open to ideas! :)

**Comment by tehsphinx** [comment]
I would also apply a credit per solution system to the above quoted example. A good answer to a representation that gets answered 100 times a week is not more worth than a good answer to a representation that is only hit once a month.

**Comment by iHiD** [comment]
How would you split the credits between the people that right the copy for the analyzer and any contributions to the analyzer? Presuming that analyzers don't have a single maintainer a year from now. That's the bit that's unclear to me.

**Comment by SleeplessByte** [comment]
Something that might not be fair but would be rather straightforward to implement is to git blame the analyser repository as a whole, and the copy _language folder_ as a whole. Now equate a line of code to a line of copy. Distribute accordingly.

I would probably suggest brackets if this is what we'll do:

0-1%: 1 point
1-7%: 2 points
7-23%: 5 points
23-59%: 8 points
Over 59%: 13 points

- This will favour small contributions but they won't count a lot.
- This will slowly replace maintainers who disappear.
- This does NOT favour more used or more popular exercises.

This is just one of many systems we could do ahha.
