### ISSUE TITLE
[C#] Extract concepts from v2 exercise: resistor-color

### ISSUE THREAD

**Issue by fpetru** [exercism/v3#719]
Extract the list of concepts required to solve the v2 C# exercise: `resistor-color`. 

For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/csharp/exercises/resistor-color/solutions`). The goal of this task is to help determine the total list of concepts that make up `resistor-color`.

The list of concepts should be stored in the following document: `languages/csharp/reference/exercise-concepts/resistor-color.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/csharp/reference/exercise-concepts/resistor-color.md

**Comment by senal** [comment]
Hi @fpetru,
I'm happy to take this task but I need more information as I'm new.
Would be nice if you can please;
1. Eloborate bit on the context for this issue.
2. Provide a reference to a similar work done in V3.
3. Conventions guidance that we should follow.

Appreciate your support in this regard.

**Comment by batibot323** [comment]
> Hi @fpetru,
> I'm happy to take this task but I need more information as I'm new.
> Would be nice if you can please;
> 
> 1. Eloborate bit on the context for this issue.

As we move from v2 to v3, we wanted to have a more structured path of learning a language such that we'll start off with the basic Concepts first so we can better understand more advanced Concepts. Compare this to v2, which is a bit more exercise-centric, we're moving to focus more on the Concepts.

To help on the move from v2 to v3, we would want to extract the Concepts for each v2 exercise so we can better plan the restructure to v3.

**Comment by fpetru** [comment]
Welcome @senal ,

> 3. Conventions guidance that we should follow.

I would add a comment on this point. Please check the `Readme` file [https://github.com/exercism/v3/blob/master/languages/csharp/reference/README.md](https://github.com/exercism/v3/blob/master/languages/csharp/reference/README.md) for a common list of concepts to start with.

**Comment by senal** [comment]
Thanks @batibot323 and @fpetru !

**Comment by senal** [comment]
@ErikSchierboom ,
Can we close this issue? I reckon we have merged the solition into master.
Do you think we need to revisit this issue?
Please advice

**Comment by ErikSchierboom** [comment]
@senal You are correct! Closing this.
