### ISSUE TITLE
[Go] Status Update

### ISSUE THREAD

**Issue by tehsphinx** [exercism/v3#72]
@ErikSchierboom: I would like to update the check boxes on https://github.com/exercism/v3/tree/master/languages/go.

Just to make sure:
- Go Test Runner can be considered finished, right?
- Go Test Runner can also be considered deployed?
- Go Analyzer: finished and deployed? Or is this another analyzer this document is talking about? Or is support for all concept exercises a criteria? Another criteria?

**Comment by ErikSchierboom** [comment]
> Go Test Runner can be considered finished, right?

Yes. There are open issues, but the basics are fully working.

> Go Test Runner can also be considered deployed?

Yep. I think it has been verified to work in the research experiment. I'll check to be certain, but I'm fairly sure.

> Go Analyzer: finished and deployed? Or is this another analyzer this document is talking about? Or is support for all concept exercises a criteria? Another criteria?

This is the analyzer that you created last year: https://github.com/exercism/go-analyzer IIRC that analyzer was finished and deployed, right?

**Comment by tehsphinx** [comment]
Correct, analyzer is deployed and running. I wouldn't consider it finished as there is always things to improve... Kind of why I'm asking. But I'll mark it as finished for now.

**Comment by tehsphinx** [comment]
If anyone wants to check those off accordingly, feel free.

**Comment by aimorris** [comment]
#165

**Comment by tehsphinx** [comment]
@aimorris thanks! Forgot to reference it.
