### ISSUE TITLE
[C#] Extract Concepts from v2 exercise: high-scores

### ISSUE THREAD

**Issue by fpetru** [exercism/v3#721]
Extract the list of concepts required to solve the v2 C# exercise: `high-scores`. 

For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/csharp/exercises/high-scores/solutions`). The goal of this task is to help determine the total list of concepts that make up `high-scores`.

The list of concepts should be stored in the following document: `languages/csharp/reference/exercise-concepts/high-scores.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/csharp/reference/exercise-concepts/high-scores.md

**Comment by maurelio1234** [comment]
Should we close this ticket?

**Comment by fpetru** [comment]
yes, I'm marking the ticket as closed.
