### ISSUE TITLE
[Clojure] Implement new Concept Exercise: `vectors`

### ISSUE THREAD

**Issue by porkostomus** [exercism/v3#724]
This issue describes how to implement the `vectors` concept exercise for the Clojure track.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before diving into the implementation, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

## Goal

The goal of this exercise is to teach the student how vectors are used in Clojure.
This is also the first major point of departure from Lisps which use lists primarily, providing a clean distinction between _code_ (i.e. lists, which always represent a function call and are _executed_), and _data_, which is not. Vectors have tremendous utility and are extremely common, and used to designate local bindings, arglists and destructuring syntax.

## Things to teach

- Vectors, like all Clojure collections are immutable and [persistent](https://en.wikipedia.org/wiki/Persistent_data_structure)
- Sequential (ordered), integer indexed
- Items are `conj`ed onto the end
- Implement IFn interface (i.e. vectors are functions of their indices)
- `get`, `assoc`

## Things not to teach

No knowledge of functions is assumed at this point, but it should probably be mentioned that vectors _are_ functions which retrieve their elements by their index.

## Concepts

- `collection`
- `array`
- `immutability`
- `function`
- `structural sharing`
- `sequences`

## Prerequisites

This is a root-level concept and not dependent upon any others.

### Hints

- [Learn Clojure - Sequential collections](https://clojure.org/guides/learn/sequential_colls#_vectors)

### After

- [Clojure reference](https://clojure.org/reference/data_structures#Vectors)

## Representer

No special requirements are needed for this exercise.

## Analyzer

No special requirements are needed for this exercise.

## Implementing

To implement a concept exercise, the following files must be created:

```
languages
└── clojure
    └── exercises
        └── concept
            └── <SLUG>
                ├── .docs
                |   ├── instructions.md
                |   ├── introduction.md
                |   ├── hints.md
                |   └── after.md (optional)
                ├── .meta
                |   |── design.md
                |   └── Example.clj
                ├── <NAME>.clj
                └── <NAME>_test.clj
```

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by bemself** [comment]
@porkostomus very nicely explained, I learned a lot also! I have a quick question, apart from vectors is a function in Clojure, I feel like it's quite similar to Java List or Array, am I right?

The vector concepts unlocks quite some concepts below, I'm kind of lost how we handle this in the implementation of this concept vector, do we explain them individually or simply link to some references?

- `collection`
- `array`
- `immutability`
- `function`
- `structural sharing`
- `sequences`

**Comment by porkostomus** [comment]
I think the main difference with arrays is the way they are implemented. I think arrays are usually contiguous blocks in memory, but Clojure's vectors are actually the same "hash-array map tries" as in Clojure maps.

**Comment by porkostomus** [comment]
Finished, see #1835
