### ISSUE TITLE
[Docs] Repository Structure

### ISSUE THREAD

**Issue by tehsphinx** [exercism/v3#73]
https://github.com/exercism/v3/blob/master/docs/maintainers/repository-structure.md

Above document seems slightly outdated:

> Each track has it's own directory containing a README.md that outlines the concepts that are necessary to learn to become fluent in those languages

The Readme now contains the bootstrapped "track progress" file.

The concepts are now in `README.md.old` -- at least on the Go track. Should we explain that in the above document as well? Rename to `Concepts.md`?

@ErikSchierboom: I can adjust the document if the points mentioned are ok with you?

**Comment by ErikSchierboom** [comment]
@tehsphinx Good point. I've submitted #107 to address this.

**Comment by tehsphinx** [comment]
@ErikSchierboom: now we have 2 different `README.md` file descriptions... one needs renaming, even if it's just for now.

**Comment by ErikSchierboom** [comment]
@tehsphinx Can this issue be closed? The relevant file was updated, and hopefully fixes this issue.

**Comment by tehsphinx** [comment]
Yes!
