### ISSUE TITLE
[Elixir] Extract Concepts from v2 exercise: forth

### ISSUE THREAD

**Issue by nathanchere** [exercism/v3#735]
Extract the list of concepts required to solve the v2 Elixir exercise: `forth`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/elixir/exercises/forth/solutions`). The goal of this task is to help determine the total list of concepts that make up `forth`.

The list of concepts should be stored in the following document: `languages/elixir/reference/exercise-concepts/forth.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/elixir/reference/exercise-concepts/forth.md

**Comment by neenjaw** [comment]
@nathanchere is there a PR for this yet?

**Comment by neenjaw** [comment]
Also, I left a more detailed comment on #737 -- <https://github.com/exercism/v3/issues/737#issuecomment-592992006> which if you haven't had time to do this yet, upon review on #839 and #842 it might be better to move to the next phase of the v3 bootstrapping guide.
