### ISSUE TITLE
[CI] action to close an issue does not remove status/in-progress label

### ISSUE THREAD

**Issue by efx** [exercism/v3#755]
First off, the automation with actions is excellent! Thank you for building it :smile: 

I created concept extraction issues like (#667) and added the `status/in-progress`
Upon merging the PR (#679), the issue was closed but retained the in progress label.

As a maintainer, I expect that label to be removed for the issue.

- should this be addressed?
- does this happen for any kind of issue?

**Comment by ErikSchierboom** [comment]
Excellent suggestion. We're aiming to work on the CI stuff in the next couple of weeks, so this is also something we could look at.

**Comment by efx** [comment]
I'm closing since the core v3 development will migrate to track specific repositories.
