### ISSUE TITLE
[ALL] Ask a question: *.md files naming

### ISSUE THREAD

**Issue by yawpitch** [exercism/v3#827]
Can we standardize on _one_ character set for the various "*.md" files in references, docs, etc?

The reference/concepts/prototype_based-programming.md file uses both underscores and a hyphen (and the hyphen doesn't even make sense). But we've also got reference/tooling/dotnet-assemblies.md and all the languages/[LANG]/reference/implementing-a-concept-exercise.md files, but most everything else is underscores.

Exercise slugs are standardized to hyphens, which I get because they're processed by other processes, but I'm having a hell of a time with large-scale reorganization of concepts due to mismatches on punctuation in paths.

If a standard exists I don't see it [here](https://github.com/exercism/v3/blob/master/docs/maintainers/repository-structure.md).

**Comment by efx** [comment]
Great idea!
I've used [fd](https://github.com/sharkdp/fd) to quickly analyze the different counts:
| kind   |      count      | 
|----------|:-------------:|
|dashes | 89 (`fd '.*-.*.md'`) |
| underscores |    95 (`fd '.*_.*.md'`)   |

**Comment by yawpitch** [comment]
Yeah ... I noticed by a different route (finding just the unique filenames, to avoid _lots_ of duplicates of the same template file) that there's currently 56 unique filenames with a dash and 61 with an underscore ... thankfully there's just 1 with _both_.

I don't care which we go with, but mixing them is going to be a long-term (or long_term) PITA.

**Comment by iHiD** [comment]
I'm going to close this and let tracks make their own decisions now we're exploding.
