### ISSUE TITLE
[PureScript] Setup PureScript for V3

### ISSUE THREAD

**Issue by aimorris** [exercism/v3#83]
Can PureScript be created for v3. I'd like to help maintain it.

**Comment by tehsphinx** [comment]
Note:  Help wanted is for contributors who want to help out.

**Comment by aimorris** [comment]
I think it automatically put that label there.

**Comment by tehsphinx** [comment]
Ok, I put it back

**Comment by tehsphinx** [comment]
@ErikSchierboom: offtopic: what is `help wanted` for? Maybe a better explanation here: https://github.com/exercism/v3/blob/master/docs/maintainers/repository-structure.md

Help wanted from who?

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom: offtopic: what is help wanted for? Maybe a better explanation here: https://github.com/exercism/v3/blob/master/docs/maintainers/repository-structure.md

It means: help wanted from anyone who wants to help. It is basically a marker that says the issue can be worked on.

**Comment by ErikSchierboom** [comment]
@aimorris PR #105 bootstraps the track.
