### ISSUE TITLE
[Go] add links to existing exercises to reference

### ISSUE THREAD

**Issue by tehsphinx** [exercism/v3#837]
Example Link to C# implementation: https://github.com/exercism/v3/blob/master/reference/types/number.md

Add links to the correct documents in the `/reference` folder (and subfolders) to the 3 existing Go exercise implementations:
- numbers
- basic-strings
- basic-slices

**Comment by oanaOM** [comment]
I can help with this.

**Comment by tehsphinx** [comment]
@oanaOM: just ask here or on Slack if you have any questions!

**Comment by oanaOM** [comment]
Hey @tehsphinx ,couldn't find a reference to slices under https://github.com/exercism/v3/tree/master/reference/types. Is it ok if I just add it to the list?

**Comment by tehsphinx** [comment]
@oanaOM: You can add that and then we can ask for @ErikSchierboom and other peoples opinion in the PR. They might feel that we should link to e.g. list instead. We will see :)

**Comment by ErikSchierboom** [comment]
I'm fairly certain a slice is different from a list (although they can be used together), and yes: creating a new document under `reference/types` would be brilliant!

**Comment by oanaOM** [comment]
Sure thing. I've just added the slice.md under `reference/types ` in my PR.

**Comment by tehsphinx** [comment]
@oanaOM: Can this issue be closed or is there still something open?

**Comment by oanaOM** [comment]
@tehsphinx sorry for the delay response. All done for now, this can be closed.
