### ISSUE TITLE
[Elixir] Concept Exercises

### ISSUE THREAD

**Issue by neenjaw** [exercism/v3#839]
> This is a blatant port of @tehsphinx's excellent working document in issue #212 

# Elixir Concept Exercises

## Exercise Flow

> Replace with current graph when able

## Exercise Status

**Icon Legend**
- ✅ exercise implemented
- 🛠 is being implemented
- 📙 exercise specification issue created
- 🔴 not started
- ❓ to be filled
- 👤 not assigned

### basics

focus: very basic introduction programming in elixir - named functions, integers, implicit return, math operators
prerequisite concepts: none
unlocks: basics
status: ✅
pull request: #1118
assigned: @neenjaw 

### booleans

focus: very basic introduction to the boolean type and strict boolean operators
prerequisite concepts: basics
unlocks: booleans
status: ✅
pull request: #1132 
assigned: @neenjaw

### conditionals

focus: introduction to the `cond/1` function 
prerequisite concepts: booleans
unlocks: conditionals, atoms
status: ✅
branch: merged
pull request: #1129 
assigned: @neenjaw 

### multiple-clause-functions

focus: intro to the multiple-clause functions, guards, default params
pre-req: conditionals
unlocks: multiple-clause-functions, guards, default-parameters
status: ✅
branch: merged
pull request: #1365
assigned: @neenjaw 

### tuples

focus: introduction to tuples
prerequisite concepts: atoms
unlocks: tuples, pattern-matching
status: ✅
branch: merged
pull request: #1484
assigned: @neenjaw 

### lists

focus: introduction to lists, string literals
prerequisite concepts: booleans
unlocks: lists, string-literals
status: ✅
pull request: #1203
assigned: @neenjaw

### anonymous-functions

focus: introduction to anonymous-functions
prerequisite concepts: basics
unlocks: anonymous-functions, closures, bit-manipulation
status: ✅
branch: merged
pull request: #1335
assigned: @neenjaw 

### maps

focus: introduction to maps
prerequisite concepts: lists, tuples, anonymous-functions, default-arguments
unlocks: maps, module-attributes-as-constants
status: ✅
branch: merged
pull request: #1336
assigned: @neenjaw 

### pattern-matching

focus: introduction to pattern-matching
prerequisite concepts: tuples, maps
unlocks: pattern-matching-basic
status: 🛠
branch: [elixir-concept-pattern-matching](https://github.com/exercism/v3/tree/elixir-concept-pattern-matching)
pull request: #1357 
assigned: @fireproofsocks 

### tail-recursion

focus: introduction to tail-recursion
prerequisite concepts: lists, pattern-matching-basic
unlocks: tail-recursion
status: 📙 exercise specification issue created (#1359)
branch: TBD
pull request: TBD
assigned: @fireproofsocks 

### strings

focus: introduction to strings
prerequisite concepts: lists, pattern-matching
unlocks: strings
status: ✅
branch: merged
pull request: #1468
assigned: @angelikatyborska   

### numbers

focus: integers vs floats
prerequisite concepts: basics
unlocks: integers, floating-point-numbers
status: ✅
branch: merged
pull request: #1492
assigned: @angelikatyborska   

### recursion

focus: working with lists using recursion
prerequisite concepts: lists, pattern-matching, multiple-clause-functions, guards
unlocks: recursion
status: ✅
branch: merged
pull request: #1515
assigned: @angelikatyborska   

### nil

focus: nil as a special atom, if, truthiness
prerequisite concepts: strings, booleans
unlocks: nil, if-conditional
status: ✅
branch: merged
pull request: #1543
assigned: @angelikatyborska

### charlists

focus: charlists as lists, code points, case
prerequisite concepts: lists, recursion, pattern-matching, guards
unlocks: charlists, case
status: ✅
branch: merged
pull request: #1560
assigned: @angelikatyborska

### binary-matching

focus:
prerequisite concepts: bitstrings, pattern-matching, strings, if-conditional
unlocks: charlists, case
status: 🛠
branch: binaries
pull request: #1506
assigned: @neenjaw

### access-behavior

focus:
prerequisite concepts: maps, strings, recursion, nil
unlocks: access-behavior
status: ✅
branch: merged
pull request: #1575
assigned: @neenjaw 

### enum

focus:
prerequisite concepts: lists, maps, atoms, tuples, nil, anonymous-functions
unlocks: enum
status: ✅
branch: merged
pull request: #1587
assigned: @angelikatyborska

**Comment by neenjaw** [comment]
@exercism/elixir is all welcome to participate as well, just couldn't add as assignees

**Comment by neenjaw** [comment]
Please feel free to edit the top level comment if you have concepts to add.

If you would like to tackle one of the exercises, please leave a comment

**Comment by neenjaw** [comment]
Updated for basics, booleans, conditionals

**Comment by neenjaw** [comment]
added lists and tuples

**Comment by angelikatyborska** [comment]
Added strings, numbers, recursion, nil, charlists, binary-matching, access-behavior. Updates the state of the rest.

**Comment by angelikatyborska** [comment]
Is this issue actually helpful to us? Do we want to close it, or maybe re-phrase?

The list of concept exercises here is severely out of date, and I am not sure if there is a point of updating it. If I need to know which exercises are implemented, I would just look into the repo.

**Comment by neenjaw** [comment]
Ya, let's close it.
