### ISSUE TITLE
[Common-Lisp] Implement new Concept Exercise: sexpr

### ISSUE THREAD

**Issue by verdammelt** [exercism/v3#852]
This issue describes how to implement the `sexpr` concept exercise for the Common Lisp track.

## Goal

The goal for this exercise is to get the student familiar with the basics of s-expressions. That is to say - that all s-expressions (sexpr from here on) are either atoms or cons pairs). We will teach this via the use of `atom` and `consp` along with `car` and `cdr` (with additional tests showing that `first` and `rest` are good "modern" names).

## Learning objectives

- Know about atoms, conses and lists.
- Know about the basic functions `car` and `cdr` (`first` and `rest`).

## Out of scope

- Full exploration of conses and lists is beyond the scope of this exercises.
- Further exploration of sexpr and their use in code manipulation/generation (e.g. macros) is also out of scope.

## Concepts

- sexpr
- lists (basic)

## Representer

(Unsure - we don't yet have a representer...)

## Analyzer

(Unsure... we don't yet have an analyzer)

**Comment by TheLostLambda** [comment]
Looking like a really good start! Was the implementing section trimmed out here?

I think Erik has left it in, but I'm not sure if it's vital: https://github.com/exercism/v3/issues/815

**Comment by verdammelt** [comment]
I see what was done on that other issue - that seems redudant to the https://github.com/exercism/v3/blob/master/languages/common-lisp/reference/implementing-a-concept-exercise.md doc though.

I was thinking that 'implementing' might have some notes/details about how to implement the exercise, not the *instructions* of how to add an exercise to the repo.

But created this without doing a survey of the "state of the art" or "best practices" already being done in other tracks.

**Comment by TheLostLambda** [comment]
That's a valid point actually. I do think that the implementation stuff has been slightly updated since we wrote that file, but it's no use repeating it here.

With that being said I've heard from some others on the slack that we can use the implementation section to give details on the sort of excercise we have in mind. We don't need to outline every detail, but we can somewhat describe the task.
