### ISSUE TITLE
[csharp] Ask a question: enums-basic

### ISSUE THREAD

**Issue by efx** [exercism/v3#854]
The first task in [instructions](https://github.com/exercism/v3/blob/c25b0e612202c1751f9be7c60da1282bf727ab93/languages/csharp/exercises/concept/enums/.docs/instructions.md) states there are 3 log levels and to create an `enum` to model this.
But the 2 task says to add a new element `Unknown`.
I see the value to extending your original definition, but shouldn't we caveat that text because we will end up with an enum that has 4 elements? e.g. saying it is only has 3 actually is incorrect by the end of the exercise

**Comment by batibot323** [comment]
Where do you plan to add this caveat? I think it's clear enough that `LogLevel` enum will increase by 1 when you reach the second question.

**Comment by efx** [comment]
@batibot323 I may be overthinking this. I would've added it to the Rust enums documentation but I'll hold off for now.
