### ISSUE TITLE
[ALL] Ask a question: can we delete unused labels?

### ISSUE THREAD

**Issue by efx** [exercism/v3#858]
[repository-structure](https://github.com/exercism/v3/blob/master/docs/maintainers/repository-structure.md) helpfully describes the labels to use.

As a maintainer, I find relevant labels quite helpful to categorize work. I noticed we still have some of GitHub's default labels: https://github.com/exercism/v3/issues/labels. `documentation` is one example.

Can we delete the unused labels to prevent confusion / repetitive categorizing?

**Comment by efx** [comment]
@ErikSchierboom could you weigh here? I am definitely nitpicking but would love explanation of how to use the stock GH labels or removing those. Thanks!

**Comment by ErikSchierboom** [comment]
@efx I like the idea of either explaining or removing the stock labels. I'll assign this to myself.

**Comment by ErikSchierboom** [comment]
@efx A [PR has been opened](#1313) to fix this.
