### ISSUE TITLE
[ALL] Ask a question: can we add a minimal editorconfig to encourage whitespace uniformity?

### ISSUE THREAD

**Issue by efx** [exercism/v3#863]
This pertains to how we manage contributions to the v3 repository.

Can we add a minimal [editorconfig](https://editorconfig.org/) file?

As a contributor I would like whitespace standards encouraged while editing markdown and other files. #857 demonstrates one case that editorconfig seeks to prevent. (extraneous whitespace changes). I see this as reducing churn.

Given the variety of languages in the project I would say we start with a small one. Perhaps just targeting markdown files at first and letting track maintainers determine the need in the respective trees.

If you are a contributor weigh in! 
Comment, 👍 or 👎 . Thanks!

**Comment by workingjubilee** [comment]
Concern: I have used at least one code snippet inside a .md file, I would expect it to use the PL's formatting preferably. Would the `editorconfig` be smart enough to detect that?

**Comment by efx** [comment]
> Concern: I have used at least one code snippet inside a .md file for presenting the desired format for a boilerplate snippet that has to be in every repo.

Great point. This is a key risk. My understanding is that your editor's implementation of editorconfig. So we would want to create a few test markdown files and then see how it behaves.

**Comment by workingjubilee** [comment]
It's at least worth experimenting with then, yeah.

**Comment by efx** [comment]
I tested it in Vim using the [editorconfig plugin](https://github.com/editorconfig/editorconfig-vim). it does not touch the whitespace of code blocks.
![editorconfig-vim](https://user-images.githubusercontent.com/472721/78407943-f0663200-75d3-11ea-812e-d116969e4052.png)

**Comment by efx** [comment]
Another alternative is we introduce `markdown-lint` with a very small configuration: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md009.
That said, I've mostly experience with editorconfig but I like the non-modifying behavior of a linter,

**Comment by workingjubilee** [comment]
That adds a dependency on Node, which is reasonable on the server but unreasonable to expect of all maintainers. I think the `.editorconfig` is ironically less invasive.

**Comment by ErikSchierboom** [comment]
> That adds a dependency on Node, which is reasonable on the server but unreasonable to expect of all maintainers. I think the .editorconfig is ironically less invasive.

Well, we _can_ do both. What if we set the editorconfig settings such that they conform to prettier's markdown setting?

There are a couple of things that I really like about prettier:

- Great editor integration (includes Vim, Atom, VS Code, and more). Works great with VS Code's "Format on Save" feature.
- Can easily be setup in a CI environment to verify the markdown
- Is easy to run as a script to update all markdown.

What do you think about combining both?

**Comment by workingjubilee** [comment]
That sounds good, actually. I just prefer being able to verify a PR is good before I submit it and, having wrangled some packaging hells before, I am conscious that "just install Node!" is... not that for many people, so the compatibility can sometimes be more theoretical than actual.

**Comment by workingjubilee** [comment]
I would like to hear more about @NobbZ's speculation that whitespace may be relevant given that the Prettier markdown formatter, judging by my experimentation, [does trim trailing whitespace](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAFTgDxgOnQB0oNs9D10BDEqsuAZxgEsoBzfEgA14CtGJAGYBXKGFbR0AdwAWLeIwAO1MHAAUASnTAqddACc4MEQajoAJhAD6zEUKFaA3FXQB6N1iYESAXx68IAA0IBBKklCMyKDUBgYQ0gAKsQhRKNQANtLUAJ5RIQBGBqoA1sYAyipgbOzIMAYicCGyMAC2GQDq8opVcOWpCiwAbgo5yOCM+SBsjHAGMInF7K3UyEKZsyECOABCxWBlMOXUrXAAMmxwaxtNINvlNRlwAIoiEPDXGZsgKgazBuMVgYSlZpFBgj8DGwYB0WBYYLJkAAOAAMISU8VmHWKSnGGKYcyGVxCAEc3vBFmE0iBqIxUFA4HALEyIUYySwjItqMtVkh1l9brNWiw6g1BY8XuSrnybiEYNQCrD4YikAAmOXFFgZGoAYQgrRW4yYAFYISJZpgFWl+d8ho0AJJQZmwcpgKHhACCTvKMByT0+s18viAA).

**Comment by NobbZ** [comment]
As I said, in a *codeblock* it is significant, depending on the language, I even gave an example, the [Whitespace](https://en.wikipedia.org/wiki/Whitespace_(programming_language)) language.

And on the other hand side, I explicitely said, that outside of a codeblock I prefer to *not* have trailing whitespace, but use `<br>` instead.

So

```md
To_be<br>
or_not_to_be<br>
```

Is to be prefered over

````md
To_be_
or_not_to_be_
````

**Comment by workingjubilee** [comment]
...oh, a PL actually named Whitespace. OK.
Well, the Prettier formatter does not respect that within inline code blocks. It seems to ignore whitespace, however, if it is formatting ``` code blocks for a a language it does not recognize (it formats js, for instance, but not other things).

**Comment by efx** [comment]
Prettier respects a [subset](https://prettier.io/docs/en/api.html) of editorconfig's options. From a quick read, they do not apply to trailing whitespace. The issue Jubilee linked above do give me pause on wholesale usage with Markdown.
So I'll keep considering how we can integrate the two approaches to Markdown consistency.

**Comment by ErikSchierboom** [comment]
I does indeed turn out that prettier does not respect trailing whitespace in code blocks. That said, I do think this is very much an edge case (we don't have a whitespace track at the moment). And even if we did, there is one way to have prettier not format the code block, and that is to prefix it with `<!-- prettier-ignore -->`. So yes, prettier is not optimal, but I still think it is an excellent tool for 99.9% of our files.

**Comment by SleeplessByte** [comment]
My two cents:

1. Please add _both_ .editorconfig ánd `prettier`: the first for users and IDE integration, the second for automatic git-hook and/or CLI check. 

2. Use `<!-- prettier-ignore -->` in front of codeblocks with white-space significant content. The amount of languages where we _require_ trailing whitespace is so little that it's not worth NOT using this at all. If `whitespace` becomes a supported language, we can always turn off prettier for _those subtrees_.

2 cents indeed.

**Comment by ErikSchierboom** [comment]
So the best approach seems to be a combination of prettier and .editorconfig. I'll try and create a PR for this.

**Comment by ErikSchierboom** [comment]
I've just created PR #1252 that adds a `.editorconfig` file, a `.prettierignore` file and to scripts to batch update all the markdown files using prettier. In #1253 you can see what that would look like.

**Comment by ErikSchierboom** [comment]
I've also add #1256 that will add CI checks to verify the format. It depends on #1252 and #1253 being merged.
