### ISSUE TITLE
[Common Lisp] - update track docs for new design of exersses

### ISSUE THREAD

**Issue by verdammelt** [exercism/v3#876]
From discussion in #853 we realize we should change the design of our exercises.

Currently we are designing exercises to contain two ASDF systems in an ASDF file , two packages in a package file, a test file and a student submission file.

While we feel that using ASDF and this setup would show 'good practice' we feel it would actually be cumbersome to use in practice (especially due to ASDF's lack of easy flexibility about where to find its files).

Our plan is to change to a v2 style of design with the following files in the exercise directory:

* `<slug>-test.lisp` - contains the tests along with `<slug>-test` package definition. Will also `(ql:quickload "fiveam")`. It will `load` the `<slug>.lisp` file. It will contain a test suite: `<slug>-suite` of tests. This file will also be set up to auto-run the test suite.
* `<slug>.lisp` - area for students code. Will contain stub code not limited to package definition and stub function(s)

**Comment by TheLostLambda** [comment]
Out of curiosity, you mentioned that the auto-running of the tests caused some issues when building, what sort of complications came from that?

**Comment by verdammelt** [comment]
The test runner I was thinking of was the one run during the builds of the track. The test runner we will build to run the student's submissions may be fine with the test file auto-running.

It complicates the build because then when trying to run the tests in the build (to check that the example code is good) we need to circumvent or somehow work around the auto running. In v2 we had reader macros that kept the test file from loading the stub solution file and auto-running the tests. I think that the reader macros add noise to the test file and I'd like to see them not there.

**Comment by TheLostLambda** [comment]
Yeah, if it takes reader macros just to work around that problem, I'd rather just remove the auto-running. It shouldn't be too much extra work for the students to run the tests (it can still be one-lined from the command-line and shouldn't be any extra effort from the REPL).

As an implementation detail, do you think that we could have the `(<slug>-test:run)` function reload the `<slug>.lisp` file on every call? That way students don't need to reload their code every time they want test code changes. Might not be best practice, but could be convenient.
