### ISSUE TITLE
[C] Extract Concepts from v2 exercise: resistor-color

### ISSUE THREAD

**Issue by wolf99** [exercism/v3#915]
Extract the list of concepts required to solve the v2 C exercise: [`resistor-color`](https://github.com/exercism/c/tree/master/exercises/resistor-color). For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches ([published community solutions](https://exercism.io/tracks/c/exercises/resistor-color/solutions)). The goal of this task is to help determine the total list of concepts that make up `resistor-color`.

The list of concepts should be stored in the following document: `languages/c/reference/exercise-concepts/resistor-color.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/c/reference/exercise-concepts/resistor-color.md

---

**v2 Metadata**

```
core
  → true

difficulty
  → 1

topics
  → enums
  → arrays
  → pointers
```

**Comment by mayurdw** [comment]
Hello @wolf99 ,

Are we looking into how changing how the exercise currently exists? I have had a lot of feedback from students asking me what is the point of this exercise and I do agree with them a little. I can elaborate if needed.

**Comment by wolf99** [comment]
Hi @mayurdw ,

Not exactly. This is part of the version 3 remake of Exercism. In broad terms, the exercises based curriculum is being changed to a concept based one. The concept extraction issues are intended to help us learn what concepts are present in existing exercises to help us formulate the concepts that should be represented in the new curriculum.

🙂

**Comment by mayurdw** [comment]
Alright thanks! Will checkout your prs.
