### ISSUE TITLE
[ALL? || Rust] Would an example folder be more appropriate than a file?

### ISSUE THREAD

**Issue by workingjubilee** [exercism/v3#991]
Currently, the concept exercise directory structure for the Rust track specifies an `example.rs`.

However, as mentioned in https://github.com/exercism/rust/issues/658, Rust programs often favor being in multiple files for the sake of readability and abstraction. I expect concept exercises to be easier to handle and more concise, but I do not expect this concern will magically disappear. In addition, I expect concept exercises and practice exercises to use very similar directory structures, so I think talking about it now would be better.

Would an entire folder be more appropriate? Would this cause problems with the test runners and frameworks? Do other tracks already use entire folders for example solutions? I know at least a few don't, but I haven't looked at all of them.

**Comment by ErikSchierboom** [comment]
> However, as mentioned in exercism/rust#658, Rust programs often favor being in multiple files for the sake of readability and abstraction. 

I understand, but it might be good to consider what the goal of the `example.rs` file is. Its sole purpose is to verify that there is _a_ solution to the exercise. The `example.rs` file thus does not have to adhere to any advanced code standards or code quality rules. It can of course, but it definitely is not required and won't in many cases. Does that help?

**Comment by workingjubilee** [comment]
Yes, I do understand this. But nonetheless those standards exist for the ease of maintenance and the tests do change for a given exercise, requiring updating them, bringing us face to face with the problems that arise from a lack of code standards or quality. Or potentially, at least! Obviously not all exercises, not all languages, et cetera.

**Comment by ErikSchierboom** [comment]
I see your point, but even then I really think this is not very much an issue. Being a maintainer myself, I never found this to be an issue. If we assume that the exercise has the correct structure in place for a student to work on (it should), updating an example file should be just a case of either replacing the stub file's contents or copying it in the right place. Besides, tests are not updated that often.

**Comment by workingjubilee** [comment]
Hmm, alright. It still seems like something that would be worth doing in case the practice exercises ever get truly interesting, as making this change now seems easier than making it later, but I must acknowledge that the 350 line behemoth that is the example solution there is fairly uncommon currently and will likely be for some time.

**Comment by coriolinus** [comment]
In [Slack discussion](https://exercism-team.slack.com/archives/CC48Y3H1B/p1586735931005700), we're talking about potentially adding a rust concept for procedural macros. In the course of that discussion, we noted in passing that having a single `example.rs` file wouldn't work: due to language requirement, procecural macros need to be in their own crate, which needs to live in its own folder.

It's not certain that having an example folder would actually solve this problem. What is clear is that the next best option, if we do build this exercise, is to have the actual implementation somewhere in `.meta`, along with some packaging which generates an appropriate `examples.rs` which contains a big base64 string, and knows how to un-base64 it, un-gzip the next output, and unpack the contents into the appropriate package. Going to those lengths feels silly.

**Comment by ErikSchierboom** [comment]
Right. So if I understand correctly, there are technical limitations to having a single `example.rs` file. Would having a `.meta/example` folder help with those?

**Comment by ErikSchierboom** [comment]
Or is that you need multiple stubs files to work with?

**Comment by coriolinus** [comment]
Yes, you understand correctly. In the specific case of procecural macros, a `.meta/example` folder would work very well, so long as for testing purposes, we can pretend that the contents of that folder are actually the project root; they can't all (for example) get copied into the `src/` directory.

That said, we're not entirely sure that we want to create a procedural macros exercise yet. It would be premature to do work enabling it, before we've decided that we really need it.

**Comment by ErikSchierboom** [comment]
> It would be premature to do work enabling it, before we've decided that we really need it.

This sounds like a good idea! Thanks for explaining.
